### ISSUE TITLE
Can not build on Windows.

### ISSUE THREAD

**Issue by katalonne** [angular/universal#430] opened 2016-06-06 11:14 UTC
I do an `npm install` in the root folder and can't get the dependencies installed.

These are the errors : http://pastebin.com/BYx55Cyw

Any help please?

**Comment by MarkPieszak** [comment] 2016-06-06 11:25
Duplicate of #369 

Kat, are you trying to get started with Universal? [Here you can find NodeJS & .NET Core example repos](https://github.com/angular/universal#getting-started). Those should work on Windows without a problem!

**Comment by katalonne** [comment] 2016-06-06 11:30
@MarkPieszak So, How do I install the dependencies? I must do an `npm install` as always but I get undesirable errors...
I followed this simple guide.
https://github.com/angular/universal-starter#installation

**Comment by MarkPieszak** [comment] 2016-06-06 11:31
The errors happened on the Starter repo? I'll take a look this morning on my other machine & get back to you!

**Comment by katalonne** [comment] 2016-06-06 11:35
@MarkPieszak No, the errors happen on this repo `https://github.com/angular/universal/` !!!

**Comment by MarkPieszak** [comment] 2016-06-06 13:44
Oh okay, you can close the issue out it's a duplicate of #369.
I'll try and spend some time today to see if I can fix it! Thanks Kat

**Closed** 2016-06-11 19:46 UTC
