### ISSUE TITLE
How to set dynamic Meta tags(Data for Meta tags from a REST API) in a component

### ISSUE THREAD

**Issue by mailtovinay** [angular/universal#1048] opened 2018-08-03 17:32 UTC
I tried using the angular routing resolve to get the data for meta tags. But my meta tags doesnot add to the page source even the code excutes. Please help me in these. Im struggling 

my Resolver : 

resolve(route: ActivatedRouteSnapshot) {
    // return this.hnService.getNewsDetailDataforResolver(route.paramMap.get('id')).catch(() => {
    //   return Observable.empty();
    // });

        const newsId = route.paramMap.get('id');
        const NEWS_KEY = makeStateKey<any>('news-' + newsId);

        if (this.transferState.hasKey(NEWS_KEY)) {

          const course = this.transferState.get<any>(NEWS_KEY, null);

          this.transferState.remove(NEWS_KEY);

          return of(course);
        }
        else {
            return this.hnService.getNewsDetailDataforResolver(newsId)
            .pipe(
              first(),
              tap(course => {
                 // if (isPlatformServer(this.platformId)) {
                      this.transferState.set(NEWS_KEY, course);
                  //}
              })
          );
        }

Components.ts : 

```

  let res = this.route.snapshot.data.message;
     let data = res['_body'];

setOgTags(data){
    this.title.setTitle(data.title);
    this.meta.addTag({name: 'og:locale', content :'en-US'});
    this.meta.addTag({name: 'og:image', content :data.thumbnail});
    this.meta.addTag({name: 'og:title', content :data.title});
    this.meta.addTag({name: 'og:url', content :"http://gallery.digitalsena.org/news-detail/"+btoa(data.sequence)});
    this.meta.addTag({name: 'og:description', content :data.title});
      this.meta.addTag({name: 'twitter:title', content: data.title});
      this.meta.addTag({name: 'twitter:description', content: data.title});
      this.meta.addTag({name: 'twitter:text:description', content: data.title});
      this.meta.addTag({name: 'twitter:image', content: data.thumbnail});
      this.meta.addTag({name: 'fb:app_id', content :"XXXXXXXXXX"});

  }

```

**Comment by Gorniv** [comment] 2018-08-20 06:56
look https://github.com/Angular-RU/angular-universal-starter
we use https://github.com/Gorniv/ngx-transfer-http for HTTP, because it is more simple

**Comment by CaerusKaru** [comment] 2018-11-02 02:15
If @Gorniv's fix worked, please close this issue, otherwise we will need a minimal reproduction repository to investigate.

**Comment by CaerusKaru** [comment] 2019-02-09 23:18
It's been months, so we're closing this issue. We can reopen if needed.

**Closed by CaerusKaru** 2019-02-09 23:18 UTC
Labels: state: Need repro
