### ISSUE TITLE
Relative URLs are not converted to absolute URLs in angular universal.

### ISSUE THREAD

**Issue by TheJLifeX** [angular/universal#1994] opened 2021-02-13 20:06 UTC
# 🐞 Bug report

#### What modules are related to this issue?
- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine

### Is this a regression?
no

### Description
According to the [official angular documentation](https://angular.io/guide/universal#using-absolute-urls-for-http-data-requests-on-the-server), when running on the server, _relative_ URLs such as `api/heroes` should be automatically converted to absolute URLs (for example, `https://my-server.com/api/heroes` in production and (I guess) `http://localhost:4200/api/heroes` in development), if you are using one of the @nguniversal/*-engine packages (such as @nguniversal/express-engine). 
**But this is not the case** (for the @nguniversal/express-engine package that I tested).

For the following request, when running on the server (see `Minimal Reproduction` below),
```ts
this.httpClient.get('api').subscribe((res) => {
  console.log(res);
});
```
we got the following error.
```
ERROR NetworkError 
  at XMLHttpRequest.send (...)
  at Observable._subscribe (...)
  at Observable._trySubscribe (...)
  ...
```

**Thank you in advance for considering this issue.**

### Clone [this minimal GitHub repository](https://github.com/TheJLifeX/bug-relative-urls-are-not-converted-to-absolute-urls-ssr)
```sh
npm install
```

```sh
npm run dev:ssr
```

### Or if you want to reproduce it manually step by step.
```sh
npm install @angular/cli@11.2.0 -g
```

```sh
ng new my-app
```

Navigate to the newly created app.
```sh
cd my-app
```

[Add angular universal](https://angular.io/guide/universal).
```sh
ng add @nguniversal/express-engine
```

Copy and paste all changes made in [this commit](https://github.com/TheJLifeX/bug-relative-urls-are-not-converted-to-absolute-urls-ssr/commit/f684c0ae5bb149634b5329880d5d014de109f281).

Run the app then open `http://localhost:4200/` on your browser and look at the console **on the server**.
```sh
npm run dev:ssr
```

## 🔥 Exception or Error
<pre><code>
ERROR NetworkError 
  at XMLHttpRequest.send (...)
  at Observable._subscribe (...)
  at Observable._trySubscribe (...)
  ...

</code></pre>

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.0
Node: 12.16.1
OS: win32 x64

Angular: 11.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server 
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------       
@angular-devkit/architect       0.1102.0
@angular-devkit/build-angular   0.1102.0
@angular-devkit/core            11.2.0
@angular-devkit/schematics      11.2.0
@nguniversal/builders           11.1.2
@nguniversal/express-engine     11.1.2
@schematics/angular             11.2.0
@schematics/update              0.1102.0
rxjs                            6.6.3
typescript                      4.1.5
</code></pre>

**Comment by alan-agius4** [comment] 2021-02-13 20:55
Duplicate of https://github.com/angular/universal/issues/1826

**Closed by alan-agius4** 2021-02-13 20:55 UTC

**Comment by alan-agius4** [comment] 2021-02-13 21:02
Thanks for the reproduction and detailed report anyways.

Much appreciated that you took time doing a good report. It’s unfortunate that you didn’t find the duplicate issue before posting.

**Comment by neilhem** [comment] 2021-02-25 15:18
The same problem with @nguniversal/express-engine@11.2.0
