### ISSUE TITLE
after 1 post request no get request is beeing cached

### ISSUE THREAD

**Issue by lutzk** [angular/universal#855] opened 2017-11-29 14:32 UTC
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
```
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [ ] express-engine
- [ ] hapi-engine
- [x] common
```

* **Do you want to request a *feature* or report a *bug*?**
bug i think - not sure

* **What is the current behavior?**

when i use the `TransferHttpCacheModule` and the `BrowserTransferStateModule` in an universal app and do a HttpClient.get the request and all later get requests to diffrent urls/ enpoints are cached in the TransferState and transfered to the browser from gthe server - so far so good

but if i do a HttpClient.post request none of the later requests is cached regardless if its a HttpClient.get or not

when i add a else block in
 [https://github.com/angular/universal/blob/master/modules/common/src/transfer_http.ts#L51](https://github.com/angular/universal/blob/master/modules/common/src/transfer_http.ts#L51)
and set cache to active again it works also for get requests done after a post request

```
if (req.method !== 'GET' && req.method !== 'HEAD') {
            this.isCacheActive = false;
            this.invalidateCacheEntry(req.url);
        } else {
            this.isCacheActive = true;
        }
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 5.0
- Browser: [Chrome 62]
- Language: [TypeScript 2.6 ]
- OS:  [Mac OS X  ]
- Platform: [NodeJs]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by patrickmichalina** [comment] 2017-11-29 18:08
Does your ApplicationRef.isStable ever return true?

**Comment by lutzk** [comment] 2017-11-30 10:06
yes i think so - i logged the value of `isStable` from:
`...node_modules/@nguniversal/common/src/transfer_http.js`

```
toPromise_1.toPromise
  .call(first_1.first.call(filter_1.filter.call(appRef.isStable, function (isStable) {
  console.log('___IS_STABLE__', isStable); <--- is true here
  return isStable;
})))
```
wich maps to [https://github.com/angular/universal/blob/master/modules/common/src/transfer_http.ts#L42](https://github.com/angular/universal/blob/master/modules/common/src/transfer_http.ts#L42)

**Comment by Toxicable** [comment] 2018-03-07 08:39
This is intended. Once you do some mutation for example POST, then on the client we have no idea if the data we currently have stored is still valid, therefore we cannnot continue caching it since it may be invalid

**Comment by Toxicable** [comment] 2018-04-14 04:34
closing as this is the expected behavior.

**Closed by Toxicable** 2018-04-14 04:34 UTC
