### ISSUE TITLE
Problem with main.js file

### ISSUE THREAD

**Issue by APoska** [angular/universal#1043] opened 2018-07-24 10:26 UTC
# Bug Report
Hi, i have problem with SSR on my project. When i run command 

`ng run project:server` 

It's generating main.js file in ./dist/server folder but when i run command 

`webpack --config webpack.server.config.js --progress --colors` 

it causes this error:

`ERROR in ./dist/server/main.js
Module not found: Error: Can't resolve '.' in 'C:\Projects\my-project\dist\server'
 @ ./dist/server/main.js 81:17-29
 @ ./server.ts`.

Line that causes error:
![image](https://user-images.githubusercontent.com/12261839/43132430-0f50e014-8f3c-11e8-92c6-bbe0694abf85.png).
When i manually delete this line, webpack command runs correctly.

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

```
Angular CLI: 6.0.8
Node: 8.11.3
OS: win32 x64
Angular: 6.0.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.4.0
@angular/cli                      6.0.8
@angular/material                 6.4.0
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3
```

**Comment by iamtracy** [comment] 2018-08-02 21:48
I was experiencing this problem on Node 10.8.0, solved it by installing node 8.11.3.

**Comment by CaerusKaru** [comment] 2018-11-02 02:19
Can you provide a minimal reproduction issue? This looks like an issue with our schematics on Windows, but I can't be sure without a reproduction.

**Comment by adriwicked** [comment] 2018-11-13 20:35
Same problem here

**Comment by adriwicked** [comment] 2018-11-13 21:09
> Can you provide a minimal reproduction issue? This looks like an issue with our schematics on Windows, but I can't be sure without a reproduction.

Hi, I have the same problem. Here you have my log. I hope it can helps:

`npm run build:ssr

> clupik-app-front@0.0.0 build:ssr /home/adrian/Documentos/clupik/dev/clupik-app-front
> npm run build:client-and-server-bundles && npm run webpack:server

npm WARN npm npm does not support Node.js v10.9.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> clupik-app-front@0.0.0 build:client-and-server-bundles /home/adrian/Documentos/clupik/dev/clupik-app-front
> node --max_old_space_size=8048 ./node_modules/@angular/cli/bin/ng build --prod && ng run clupik-app-front:server

                                                                                           
Date: 2018-11-13T21:04:49.562Z
Hash: 4803cb9881b9c04f7f9d
Time: 232078ms
chunk {scripts} scripts.24bd2a219e68f4886791.js (scripts) 400 kB  [rendered]
chunk {0} runtime.ec2944dd8b20ec099bf3.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main.af58c615a6d2bb4b390d.js (main) 7.36 MB [initial] [rendered]
chunk {2} polyfills.5814e1750eb4aecd5ed7.js (polyfills) 144 kB [initial] [rendered]
chunk {3} styles.c044436299e2255d4391.css (styles) 1.45 MB [initial] [rendered]

WARNING in Circular dependency detected:
src/app/core/components/navigation/vertical/nav-collapse/nav-vertical-collapse.component.ngfactory.js -> src/app/core/components/navigation/vertical/nav-group/nav-vertical-group.component.ngfactory.js -> src/app/core/components/navigation/vertical/nav-collapse/nav-vertical-collapse.component.ngfactory.js

WARNING in Circular dependency detected:
src/app/core/components/navigation/vertical/nav-group/nav-vertical-group.component.ngfactory.js -> src/app/core/components/navigation/vertical/nav-collapse/nav-vertical-collapse.component.ngfactory.js -> src/app/core/components/navigation/vertical/nav-group/nav-vertical-group.component.ngfactory.js
                                                                                           
Date: 2018-11-13T21:05:40.941Z
Hash: 1a24077d332666ab9f4f
Time: 48417ms
chunk {main} main.js, main.js.map (main) 9.84 MB [entry] [rendered]

WARNING in Circular dependency detected:
src/app/core/components/navigation/vertical/nav-collapse/nav-vertical-collapse.component.ngfactory.js -> src/app/core/components/navigation/vertical/nav-group/nav-vertical-group.component.ngfactory.js -> src/app/core/components/navigation/vertical/nav-collapse/nav-vertical-collapse.component.ngfactory.js

WARNING in Circular dependency detected:
src/app/core/components/navigation/vertical/nav-group/nav-vertical-group.component.ngfactory.js -> src/app/core/components/navigation/vertical/nav-collapse/nav-vertical-collapse.component.ngfactory.js -> src/app/core/components/navigation/vertical/nav-group/nav-vertical-group.component.ngfactory.js
npm WARN npm npm does not support Node.js v10.9.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> clupik-app-front@0.0.0 webpack:server /home/adrian/Documentos/clupik/dev/clupik-app-front
> webpack --config webpack.server.config.js --progress --colors

Hash: 0bc7620a2f5b6f12ff2d                                                                  
Version: webpack 4.19.1
Time: 22733ms
Built at: 2018-11-13 22:06:04
    Asset      Size  Chunks             Chunk Names
server.js  23.8 MiB       0  [emitted]  server
Entrypoint server = server.js
  [0] ./server.ts 1.79 KiB {0} [built]
  [2] external "events" 42 bytes {0} [built]
  [3] external "fs" 42 bytes {0} [built]
  [4] external "timers" 42 bytes {0} [optional] [built]
  [5] external "crypto" 42 bytes {0} [built]
[214] ./src lazy namespace object 160 bytes {0} [built]
[219] external "url" 42 bytes {0} [built]
[282] external "http" 42 bytes {0} [built]
[283] external "https" 42 bytes {0} [built]
[284] external "os" 42 bytes {0} [built]
[292] external "path" 42 bytes {0} [built]
[309] external "net" 42 bytes {0} [built]
[403] (webpack)/buildin/module.js 497 bytes {0} [built]
[425] ./dist/server/main.js 9.84 MiB {0} [built]
[826] ./node_modules/moment/locale sync ^\.\/.*$ 2.91 KiB {0} [optional] [built]
    + 1406 hidden modules

ERROR in ./dist/server/main.js
Module not found: Error: Can't resolve '.' in '/home/adrian/Documentos/clupik/dev/clupik-app-front/dist/server'
 @ ./dist/server/main.js 96:17-29
 @ ./server.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! clupik-app-front@0.0.0 webpack:server: `webpack --config webpack.server.config.js --progress --colors`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the clupik-app-front@0.0.0 webpack:server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/adrian/.npm/_logs/2018-11-13T21_06_04_477Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! clupik-app-front@0.0.0 build:ssr: `npm run build:client-and-server-bundles && npm run webpack:server`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the clupik-app-front@0.0.0 build:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/adrian/.npm/_logs/2018-11-13T21_06_04_487Z-debug.log`

**Comment by Farqual** [comment] 2018-11-17 22:50
Does this issue could be same one as this one : https://github.com/swimlane/ngx-datatable/issues/1568#issue-367434230 ?

You can find a repository to reproduce this error there : https://github.com/Muhammad-Soban/ngx-datatable-ssr-issue.git

**Comment by APoska** [comment] 2018-11-28 09:38
I have found problem what is the problem, in my i18n.pipe I have `import * as Dictionary from '.';`
only changing this to `import * as Dictionary from './index';` resolved this problem

**Comment by ericel** [comment] 2018-12-03 14:36
Same here, hope someone comes alone with a fix for this soon!

```
ERROR in ./dist/app-server/main.js
Module not found: Error: Can't resolve '.' in 'E:\websites\app\dist\app-server'
 @ ./dist/app-server/main.js 96:17-29
 @ ./dist sync ^\.\/.*\-server\/main$
 @ ./server.ts
```

**Comment by williamdes** [comment] 2020-04-23 23:00
Removing `"outputHashing": "bundles",`  from my `angular.json` file did solve this issue.
Or setting it to `"outputHashing": "none",`

```diff
                "server": {
                    "builder": "@angular-devkit/build-angular:server",
                    "options": {
                        "progress": false,
                        "outputPath": "dist/server",
                        "main": "server.ts",
                        "tsConfig": "src/tsconfig.server.json"
                    },
                    "configurations": {
                        "production": {
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.prod.ts"
                                }
                            ],
                            "optimization": true,
-                           "outputHashing": "bundles",
+                           "outputHashing": "none",
                            "sourceMap": false,
                            "namedChunks": false,
                            "extractLicenses": true,
                            "vendorChunk": false,
                            "vendorSourceMap": false
                        },
                        "staging": {
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.staging.ts"
                                }
                            ],
                            "optimization": true,
-                           "outputHashing": "bundles",
+                           "outputHashing": "none",
                            "sourceMap": false,
                            "namedChunks": false,
                            "extractLicenses": true,
                            "vendorChunk": false,
                            "vendorSourceMap": false
                        }
                    }
                },
```

**Comment by alan-agius4** [comment] 2022-08-09 12:26
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.

**Closed by alan-agius4** 2022-08-09 12:26 UTC
Labels: P1: required, need: investigation, comp: express-engine
