### ISSUE TITLE
Return a 404 or 500 status code

### ISSUE THREAD

**Issue by TisLars** [angular/universal#969] opened 2018-04-25 20:15 UTC
* **I'm submitting a ...**
```
- [ ] bug report
- [x] feature request
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
When the user ends up on a non-existing page, the browser returns a 200 http status code.

* **What is the expected behavior?**
I'd would like to be able to return a 404 or 500 status code.

* **What is the motivation / use case for changing the behavior?**
For SEO it is important to return correct status codes.

* **Please tell us about your environment:**
```
 - Angular version: 4
 - Browser: all
 - Language: Typscript
 - OS:  Mac OS X
 - Platform: NodeJS
```

* **Other information**
I followed [this solution](https://github.com/angular/universal/issues/667#issuecomment-363720665) from a previous reported issue. However, my `server.ts` differs from theirs, as mine is the same as the official repository' one.

**Comment by Gorniv** [comment] 2018-05-06 19:34
you can use https://github.com/Angular-RU/angular-universal-starter/blob/master/src/app/not-found/not-found.component.ts and https://github.com/Angular-RU/angular-universal-starter/blob/d993c2541e8208d8c74ff3a47fd1691b28a7a0f4/src/app/not-found/not-found.service.ts for 404 status code

**Comment by Toxicable** [comment] 2018-05-18 04:17
duplicate of https://github.com/angular/universal/issues/827

**Closed by Toxicable** 2018-05-18 04:17 UTC
Labels: comp: common, effort2: days, state: Needs Design
