### ISSUE TITLE
Failed to parse SourceMap: http://localhost:3000/dist/client/toSubscriber.js.map

### ISSUE THREAD

**Issue by jesussobrino** [angular/universal#343] opened 2016-04-01 11:41 UTC
**I'm submitting a ...**
- [x] bug report

I'm running the https://github.com/angular/universal-starter app and I'm getting the following error in my console:

> Failed to parse SourceMap: http://localhost:3000/dist/client/toSubscriber.js.map

I think it's a bootStrapping client issue, because if I comment [client.ts][client-url]

**Github repo** 

- https://github.com/angular/universal-starter
- And it also failing in my current project.

**Environment:**

- Angular version: 2.0.0-beta.13
- Angular-universal version: 0.84.2
- NodeJS version: 4.4.0
- Browser: [Chrome 49.0.2623.110 ]
- Language: [TypeScript 1.8.9]

Thanks again for your work.
Jesús.

[client-url]: https://github.com/angular/universal-starter/blob/master/src/client.ts

**Comment by jesussobrino** [comment] 2016-04-05 08:24
After updating to **Angular-universal version: 0.85.1** I got theses console error:

![Uploading angular-universal-0.85.1.jpg…]()

I hope it helps.

Thanks again.

**Environment:**

- Angular version: 2.0.0-beta.13
**- Angular-universal version: 0.85.1**
- Browser: [Chrome 49.0.2623.110 ]
- Language: [TypeScript 1.8.9]

**Comment by jesussobrino** [comment] 2016-04-05 08:25
After updating to **Angular-universal version: 0.85.1** I got theses console error:

![angular-universal-0 85 1](https://cloud.githubusercontent.com/assets/4729067/14275590/8bb05a8c-fb18-11e5-8298-072b93d37890.jpg)

I hope it helps.

Thanks again.

**Environment:**

- Angular version: 2.0.0-beta.13
**- Angular-universal version: 0.85.1**
- Browser: [Chrome 49.0.2623.110 ]
- Language: [TypeScript 1.8.9]

**Comment by MarkPieszak** [comment] 2016-04-06 16:38
Related to issue #350 . I put some additional debugging details and stacktrace info there.
Removing the `http.get.json()` line in **app.component.ts** seems to solve the problem. There seems to be a conflict with RxJS going on here.

**Comment by MarkPieszak** [comment] 2016-04-07 14:39
Thanks to Mega in slack it looks like this is a Zone issue itself not on us.
Reverting down to 0.6.8 fixes this issue.

Zone issue here : angular/zone.js#310

**Comment by jeffwhelpley** [comment] 2016-05-06 20:56
OK, I found the root cause here, but just thinking about the fix to make. This comes from the RxJS package.

**Comment by jeffwhelpley** [comment] 2016-05-06 21:20
@gdi2290 hey, Mr. Webpack Master Jedi...these annoying warnings in the browser console are due to the fact that the rxjs code all has references pointing to an associated source map. We need to either strip out the source map references in the JavaScript files or make sure we pull the source maps from node_modules/rxjs to the local app/client dir. I would think we want to do the former (i.e. strip out), but I am not sure how to do this with webpack. Let me know what you think.

**Comment by MarkPieszak** [comment] 2016-05-28 00:03
I can take care of this one if you point me in the right direction mr jedi :P @gdi2290 
Stripping it out sounds like something that would need to be done on the RxJs level though isn't it.

The toSubscribe map issue is gone I now see `trycatch.js.map` failed to parse (in universal-starter for example) which is in rxjs/utils

**Comment by gdi2290** [comment] 2016-05-28 08:08
yeah the problem is rxjs sourcemaps we need to instal source-map-loader and ignore rxjs
see 
https://github.com/AngularClass/angular2-webpack-starter/blob/8fbfd28ea677317fe4825fadfae54cc93808ef28/config/webpack.common.js#L115...L125

**Comment by MarkPieszak** [comment] 2016-05-28 14:46
`exclude`, of course ... what was I thinking 🐓  thanks!

**Comment by gdi2290** [comment] 2016-06-30 18:36
closing as no one is fixing their source maps

**Closed by gdi2290** 2016-06-30 18:36 UTC
