### ISSUE TITLE
innerHTML throws ERROR ReferenceError: Node is not defined

### ISSUE THREAD

**Issue by bellizio** [angular/universal#982] opened 2018-05-08 18:46 UTC
## I'm submitting a ...
```
- [X] bug report <!-- Please search GitHub for a similar issue or PR before submitting -->
- [ ] feature request
- [ ] Support request => Please do not submit support request here, instead see https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question
```

## What modules are related to this Issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [X] express-engine
- [ ] hapi-engine
- [X] module-map-ngfactory-loader
```

## Current behavior?
Binding [innerHTML] to an element in a component template throws the following server-side error when serving an angular universal app:
```
Node server listening on http://localhost:4000
Running on the server with appId=tour-of-heroes
ERROR ReferenceError: Node is not defined
    at isTemplateElement (/Users/dbellizio/Dev/angular/universal/dist/server.js:12053:28)
    at getTemplateContent (/Users/dbellizio/Dev/angular/universal/dist/server.js:12048:65)
    at _sanitizeHtml (/Users/dbellizio/Dev/angular/universal/dist/server.js:12040:28)
    at DomSanitizerImpl.sanitize (/Users/dbellizio/Dev/angular/universal/dist/server.js:82748:92)
    at setElementProperty (/Users/dbellizio/Dev/angular/universal/dist/server.js:12999:61)
    at checkAndUpdateElementValue (/Users/dbellizio/Dev/angular/universal/dist/server.js:12951:13)
    at checkAndUpdateElementInline (/Users/dbellizio/Dev/angular/universal/dist/server.js:12898:24)
    at checkAndUpdateNodeInline (/Users/dbellizio/Dev/angular/universal/dist/server.js:15234:20)
    at checkAndUpdateNode (/Users/dbellizio/Dev/angular/universal/dist/server.js:15200:16)
    at prodCheckAndUpdateNode (/Users/dbellizio/Dev/angular/universal/dist/server.js:15744:5)
```
## Expected behavior?
The server-side error should not occur and the app should render normally as expected.
## Minimal reproduction with instructions
1. Download and unzip the universal sample app from Angular [here](https://angular.io/generated/zips/universal/universal.zip)
2. Run `npm install` in the universal directory
3. Open **app.component.ts** and change the title property to the following: 
`title = '<h1>Tour of Heroes</h1>';`
4. Open **app.component.html**, remove the h1 tag, and add the following in its place:
`<div [innerHTML]="title"></div>`
5. Run `npm run build:ssr`
6. Run `npm run serve:ssr`
7. Navigate to localhost:4000
8. Observe the error code pasted above in the terminal console
## Environment:
**@nguniversal versions**
  - express-engine: 6.0.0-rc.2
  - module-map-ngfactory-loader: 6.0.0-rc.2
```
Your global Angular CLI version (6.0.0) is greater than your local
version (6.0.0-rc.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.0-rc.4
Node: 8.11.1
OS: darwin x64
Angular: 6.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.13
@angular-devkit/build-angular     0.5.13
@angular-devkit/build-optimizer   0.5.13
@angular-devkit/core              0.5.13
@angular-devkit/schematics        0.5.6
@angular/cli                      6.0.0-rc.4
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.0-rc.11
@schematics/angular               0.5.6
@schematics/update                0.5.6
rxjs                              6.0.0-uncanny-rc.7
typescript                        2.7.2
webpack                           4.6.0
```

## Other information (optional)
The error occurs on the official 6.0.0 release of Angular / Angular CLI / Angular Universal as well.

**Comment by Toxicable** [comment] 2018-05-09 08:20
I was able to reproduce this.
From my inital look it appears that it only happens when using `npm` to install
If you use `yarn` instead then you wont get this error

**Comment by m98** [comment] 2018-05-09 12:04
I reported the same issue on Angular repo
https://github.com/angular/angular/issues/23741

**Comment by Toxicable** [comment] 2018-05-09 20:46
@bellizio Ill double check when I get home this afternoon.
Meanwhile, did you do a clear of your node_modules? then reinstall?

**Comment by Toxicable** [comment] 2018-05-10 08:44
ah yes I am able to reproduce it with `yarn`
I must have made a mistake earlier.
Thanks for reporting this, i'll investigate further

**Comment by nginx17** [comment] 2018-05-11 19:17
same issue with me

Angular CLI: 6.0.1
Node: 8.11.1
OS: linux x64
Angular: 6.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
angular-devkit/architect         0.6.1
angular-devkit/build-angular     0.6.1
angular-devkit/build-optimizer   0.6.1
angular-devkit/core              0.6.1
angular-devkit/schematics        0.6.1
schematics/angular               0.6.1
schematics/update                0.6.1
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.2
 
> nguniversal

- "nguniversal/express-engine": "^6.0.0",
- "nguniversal/module-map-ngfactory-loader": "^6.0.0",

reproduce with "npm" and "yarn" get same problem

> ERROR ReferenceError: Node is not defined

**Comment by m98** [comment] 2018-05-11 20:25
The same issue reported on Angular repository
https://github.com/angular/angular/issues/23741

**Comment by Toxicable** [comment] 2018-05-12 21:11
Thanks @m98 
This is an issue with the core platformServer, so ill be closing this as a duplicate of https://github.com/angular/angular/issues/23741

**Closed by Toxicable** 2018-05-12 21:11 UTC
Labels: comp: core

**Comment by sherinisat** [comment] 2018-07-30 05:12
Your global Angular CLI version (6.1.1) is greater than your local
version (6.0.0-rc.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
