### ISSUE TITLE
@HostListener will cause ReferenceError: Event is not defined

### ISSUE THREAD

**Issue by wpcfan** [angular/universal#847] opened 2017-11-16 16:59 UTC
* **I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [ ] aspnetcore-engine
- [x] express-engine
- [ ] hapi-engine

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
add `@HostListener('keyup', ['$event'])` to a directive and run `npm run build:ssr && npm run serve:ssr`, will get an error

```
> ng-universal-demo@0.0.0 serve:ssr /Users/wangpeng/workspace/ng/universal-starter
> node dist/server

/Users/wangpeng/workspace/ng/universal-starter/dist/server.js:105027
!function(e,n){for(var t in n)e[t]=n[t]}(exports,function(e){function n(o){if(t[o])return t[o].exports;var r=t[o]={i:o,l:!1,exports:{}};return e[o].call(r.exports,r,r.exports,n),r.l=!0,r.exports}var t={};return n.m=e,n.c=t,n.d=function(e,t,o){n.o(e,t)||Object.defineProperty(e,t,{configurable:!1,enumerable:!0,get:o})},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){returne};return n.d(t,"a",t),t},n.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},n.p="",n(n.s=0)}({"+ZWX":function(e,n,t){"use strict";function o(e){return l.\u0275vid(0,[(e()(),l.\u0275eld(0,0,null,null,1,"h3",[],null,null,null,null,null)),(e()(),l.\u0275ted(1,null,["",""]))],null,function(e,n){e(n,1,0,n.component.message)})}function r(e){return l.\u0275vid(0,[(e()(),l.\u0275eld(0,0,null,null,1,"home",[],null,null,null,o,a)),l.\u0275did(1,114688,null,0,u.HomeComponent,[],null,null)],function(e,n){e(n,1,0)},null)}var l=t("OQ0P"),u

ReferenceError: Event is not defined
    at /Users/wangpeng/workspace/ng/universal-starter/dist/server.js:105027:14201
    at Object.nvKn (/Users/wangpeng/workspace/ng/universal-starter/dist/server.js:105027:14317)
    at n (/Users/wangpeng/workspace/ng/universal-starter/dist/server.js:105027:149)
    at Object.aR8+ (/Users/wangpeng/workspace/ng/universal-starter/dist/server.js:105027:10267)
    at n (/Users/wangpeng/workspace/ng/universal-starter/dist/server.js:105027:149)
    at Object.bNRb (/Users/wangpeng/workspace/ng/universal-starter/dist/server.js:105027:10873)
    at n (/Users/wangpeng/workspace/ng/universal-starter/dist/server.js:105027:149)
    at Object.JwoV (/Users/wangpeng/workspace/ng/universal-starter/dist/server.js:105027:1956)
    at n (/Users/wangpeng/workspace/ng/universal-starter/dist/server.js:105027:149)
    at Object.Zq8w (/Users/wangpeng/workspace/ng/universal-starter/dist/server.js:105027:9886)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng-universal-demo@0.0.0 serve:ssr: `node dist/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng-universal-demo@0.0.0 serve:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wangpeng/.npm/_logs/2017-11-16T16_50_33_855Z-debug.log
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

you can clone `https://github.com/wpcfan/universal-starter.git` to try it out. I only added a directive in this repo

* **What is the expected behavior?**
There should not be any error when using HostListener

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 5.0.1
- Browser: [ Chrome 61 ]
- Language: [TypeScript 2.6  ]
- OS:  [ Mac OS X  ]
- Platform: [NodeJs]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Toxicable** [comment] 2017-11-18 06:46
duplicate of https://github.com/angular/universal/issues/844

**Closed by Toxicable** 2017-11-18 06:46 UTC
