### ISSUE TITLE
legend+* -> Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by lightbulb110** [angular/universal#2811] opened 2022-09-07 16:20 UTC
<--
Please follow the below issue template. Issues not following the issue template will be closed.
Please provide _as much detail as possible_ in as minimal a reproduction as possible. This means no/only one third-party
libraries, no application-specific code, etc. Essentially, we're looking for an `ng new` project with maybe one
additional file/change. If this is not possible, please look deeper into your issue or post it to StackOverflow
for support. This is a bug/feature tracker, meaning that something is actively _missing or broken_ in Angular Universal.
Anything else does not belong on this forum.

For very common issues when using Angular Universal, please see [this doc](docs/gotchas.md). This includes
issues for `window is not defined` and other hiccups when adopting Angular Universal for the first time.
-->

# 🐞 Bug report

#### What modules are related to this issue?

?

- [ ] builders
- [ ] common
- [ ] express-engine

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

Whenever I add bootstrap.min.css to styles within angular.json I receive the following error in the console whenever the page loads: 
**1 rules skipped due to selector errors:
  legend+* -> Cannot read properties of undefined (reading 'type')**

## 🔬 Minimal Reproduction

Add the latest version of bootstrap with npm and then add the css file to styles in angular.json. serve with dev:ssr and then browse.

## 🔥 Exception or Error

legend+* -> Cannot read properties of undefined (reading 'type')

</code></pre>

## 🌍 Your Environment

<pre><code>

</code></pre>

**Comment by lightbulb110** [comment] 2022-09-07 16:21
Angular CLI: 14.2.1
Node: 16.15.0
Package Manager: npm 8.5.5
OS: win32 x64

Angular: 14.2.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.1
@angular-devkit/build-angular   14.2.1
@angular-devkit/core            14.2.1
@angular-devkit/schematics      14.2.1
@angular/cli                    14.2.1
@schematics/angular             14.2.1
rxjs                            7.5.6
typescript                      4.7.4

**Comment by alan-agius4** [comment] 2022-09-07 18:09
Duplicate of https://github.com/angular/angular-cli/issues/22694

**Closed by alan-agius4** 2022-09-07 18:09 UTC
