### ISSUE TITLE
Issue with angular 11 SSR and mac os catalina

### ISSUE THREAD

**Issue by harikrishnancu** [angular/universal#2219] opened 2021-07-26 14:47 UTC
Hi i am facing an issue with angular 11.
I have created a sample application with angular 11 with SSR but that website is not accessible in Mac OS Catalina
works perfectly in all other OS including Mac BigSur. Any idea?

**Comment by alan-agius4** [comment] 2021-07-27 13:05
NSPOSIXErrorDomain error is a protocol error message that appears when in Safari. 

I tried to look at the reproduction, but there are a number of missing files, are you able to replicate this issue on a `ng new` application?

**Comment by alan-agius4** [comment] 2021-08-03 13:15
Closing since no further feedback provided.

**Closed by alan-agius4** 2021-08-03 13:15 UTC
Labels: need: repro steps
