### ISSUE TITLE
Page Loader Code Ignored by the Universal Compile

### ISSUE THREAD

**Issue by netlander** [angular/universal#931] opened 2018-03-15 11:57 UTC
**Note: for support questions, please use one of [these channels][Channels]**. This repository's issues are reserved 
for feature requests and bug reports. Also, **Preboot has moved** [here][preboot] - please make preboot-related issues 
there.

* **I'm submitting a ...**
```
- [ X ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [ ] common
- [ X ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Page loader code that's in index.html (inside the <app-root></app-root> tag) is ignored by the Universal compiler.

* **If the current behavior is a bug**, please provide the steps to reproduce and if possible a minimal demo of the 
problem by creating a github repo.

Page loader implemented by adding the loader markup inside the <app></app> tag as well as css styling, in the index.html of the Angular 5.2 project.

The code inside the application tag is supposed to be replaced by the Angular app when it has finished bootstrapping.

This implementation works fine in normal deployment. However, in SSR the code is completely ignored by the compiler.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 5.2
- Browser: [all ]
- Language: [all ]
- OS:  [all]
- Platform: [All]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us 
to have context, eg. stackoverflow, gitter, etc)

[Channels]: https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question
[preboot]: https://github.com/angular/preboot

**Comment by Toxicable** [comment] 2018-03-16 21:07
By your description I do not understand what Page Loader is or how you're using it.
Could you provide a minimal reproduction of your issue?

**Comment by netlander** [comment] 2018-03-17 10:03
Have a look at [this example](https://github.com/tomastrajan/angular-ngrx-material-starter/blob/master/src/index.html). A running demo ca be found [here](https://tomastrajan.github.io/angular-ngrx-material-starter#/about).

The main idea is to put a spinner in front of the user before the bootstrapping process is completed and the app is loaded.

**Comment by netlander** [comment] 2018-03-29 11:51
@Toxicable if you are not able to look into the example I pointed to maybe you could share some info on the best way to include a page loader/spinner along the lines of [NgxSpinner](https://napster2210.github.io/ngx-spinner/).

**Comment by Toxicable** [comment] 2018-04-01 03:45
The content inside your root tag on your index.html will be removed by Universal and replaced with the rendered version of your app, so it never has a chance to appear.
I'd suggest implementing this as part of your app not in your index.html
Im closing this since it isn't an issue with Universal

**Closed by Toxicable** 2018-04-01 03:45 UTC
Labels: state: Need repro
