### ISSUE TITLE
Router + Toastr Undefined

### ISSUE THREAD

**Issue by jcjp** [angular/universal#1053] opened 2018-08-16 16:00 UTC
# BUG REPORT

**What is the current behavior?**

toastr is undefined and router is undefined whenever they are called.

**What is the expected behavior?**

toastr and router should function when called, and not throw a logs of error in the console.

**Steps to reproduce**

Use the library toastr and router in Angular 6 universal application.

I have a completed Angular 6 universal application build , however I am receiving an error of toastr is undefined. I tried commenting out everything related to toastr but then router becomes undefined.

```
import { Injectable } from '@angular/core';
import { Router, CanActivate } from '@angular/router';
import { AuthenticationService } from './authentication.service';
import { ToastrService } from 'ngx-toastr';

@Injectable()
export class AuthGuardService implements CanActivate {

    constructor(private auth: AuthenticationService, private router: Router, private toastr: ToastrService) { }

    canActivate(): Promise<boolean> {
        return new Promise(function (resolve) {
            if(...) {
                if (...) {
                ...
                } else {
                    this.toastr.error("Please login...", "Unauthorized");
                    this.router.navigate(['/login']);
                    resolve(false);
                }
            } else {
                this.toastr.error("Please login...", "Unauthorized");
                this.router.navigate(['/login']);
                resolve(false);
            }
        });
    }
}
```

Here is what is in my **app.module.ts** file:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { HttpClientModule } from '@angular/common/http';
import { RouterModule } from '@angular/router';
import { ReactiveFormsModule } from '@angular/forms';
import { ToastrModule } from 'ngx-toastr';
import { FormsModule } from '@angular/forms';
...
@NgModule({
  declarations: [...],
  imports: [
    BrowserAnimationsModule,
    AppRoutingModule,
    HttpClientModule,
    RouterModule,
    ReactiveFormsModule,
    FormsModule,
    ToastrModule.forRoot()
  ],
  providers: [
    AuthGuardService
    ...
  ],
  bootstrap: [AppComponent],
  entryComponents: [...]
})
export class AppModule { }
```

**Angular CLI information:**
```
Angular CLI: 6.1.2
Node: 8.9.4
OS: win32 x64
Angular: 6.1.3
... animations, common, compiler, core, forms, http
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.2 (cli-only)
@angular-devkit/core         0.7.2 (cli-only)
@angular-devkit/schematics   0.7.2 (cli-only)
@angular/cdk                 6.4.5
@angular/material            6.4.5
@schematics/angular          0.7.2 (cli-only)
@schematics/update           0.7.2 (cli-only)
rxjs                         6.2.2
```

**Comment by CaerusKaru** [comment] 2018-11-02 02:13
We have no way of determining the root cause without a minimal reproduction repository. It looks likely that your Router guard is at fault, in which case this should be taken up with angular/angular.

**Comment by CaerusKaru** [comment] 2019-02-09 23:18
It's been months, so we're closing this issue. We can reopen if needed.

**Closed by CaerusKaru** 2019-02-09 23:18 UTC
Labels: state: Need repro
