### ISSUE TITLE
Why is the official website all Angular2?

### ISSUE THREAD

**Issue by splincode** [angular/universal#831] opened 2017-10-24 07:40 UTC
https://universal.angular.io/quickstart/

In fact, you no longer need to write about Angular2, because gradually all the repositories are straightened out and include the latest version of Angular. And you directly on the site only about the second version, although the packages for the latest version are referenced. Why?

**Comment by Toxicable** [comment] 2017-10-31 19:12
duplicate of #745

**Closed by Toxicable** 2017-10-31 19:12 UTC
Labels: add-to: Documentation
