### ISSUE TITLE
Angulra 9 SSR refresh

### ISSUE THREAD

**Issue by martinslavov** [angular/universal#1474] opened 2020-01-27 09:14 UTC
Hello everyone,

I have the following problem with angular and SSR. I use angular 9. Everything works fine but when
I click F5 the first thing which I see is the login page of my application and after that I see the page I'm on. I built the application with angular 8 and everything worked fine. Now I decided to migrate to the next version.

Any suggestion?

**Comment by alan-agius4** [comment] 2020-01-28 09:38
@martinslavov, can you provide a reproduction please? As @sod it's probably caused by the fact that the server is not aware if the user is authenticated.

**Comment by alan-agius4** [comment] 2020-02-21 07:09
Closing as the author didn’t get back to us.

If the problem persist please open an issue with a minimal reproduction.

**Closed by alan-agius4** 2020-02-21 07:09 UTC
