### ISSUE TITLE
Using xmlns and version on svg elements breaks builds

### ISSUE THREAD

**Issue by oleersoy** [angular/universal#906] opened 2018-02-22 22:13 UTC
https://github.com/crisbeto/angular-svg-round-progressbar/issues/164

**Comment by CaerusKaru** [comment] 2018-02-22 22:16
Duplicate of https://github.com/angular/angular/issues/21196

**Comment by CaerusKaru** [comment] 2018-02-22 22:16
This will be fixed in angular/angular#22263

**Closed by CaerusKaru** 2018-02-22 22:16 UTC
