### ISSUE TITLE
Universal renders a blank page on synchronous runtime error in ngOnDestroy and without throwing any error.

### ISSUE THREAD

**Issue by Reuvenc** [angular/universal#646] opened 2016-12-18 15:14 UTC
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
- [ X ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [ X ] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**

Report a bug.

* **What is the current behavior?**

When a synchronous error occurs in ngOnDestroy lifecycle hook, universal renders blank page and does not indicate any error.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

Triggering any simple runtime error will lead to such behavior, see the following snippet as an example: https://gist.github.com/Reuvenc/4cf15cf9c3708c889de3016561a5796b

* **What is the expected behavior?**

To throw an error.

* **What is the motivation / use case for changing the behavior?**

Getting a blank page without any error indication makes it impossible to detect an error.

* **Please tell us about your environment:**

- Angular version: 2.3.0
- Browser: Chrome 55
- Language: TypeScript 2.14
- OS: Mac OS X | Windows
- Platform: NodeJs

**Comment by alonp99** [comment] 2016-12-26 14:10
Same for me @gdi2290

**Comment by nitzanshinnies** [comment] 2016-12-26 14:19
Ditto. @gdi2290 please advise.

**Comment by MarkPieszak** [comment] 2016-12-26 16:40
How are you handling errors from the serializer? 
It should ideally just be sending the initial blank App at least.

**Comment by Reuvenc** [comment] 2016-12-27 12:59
@MarkPieszak Yes, I've added a catch on the promise returned from serializeModule(). Also, I'm handling zone errors by running in guard mode - `zone.runGuarded`. I've added onError and onHandleError methods to forked zone, but none of them are invoked).
What do you mean by saying blank App? currently I'm getting a blank page:

```
<html>
    <head></head>
    <body></body>
</html>
```

**Comment by MarkPieszak** [comment] 2016-12-27 13:42
I need to clean this code up, but when errors happen I return what was the original doc, in my case just "app", but at least that way the client bootstrap can take over in this case of failure: https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Client/bootstrap-server.ts#L68

Would that help any?

**Comment by gdi2290** [comment] 2016-12-27 15:27
this was meant to be by design as users wanted to return the index.html without pre-rendered content if there was an error. Everyone seems to be handling errors differently and probably should have added a config for silentErrors

**Comment by Reuvenc** [comment] 2017-01-01 12:59
@MarkPieszak Thanks for the reference, actually the promise doesn't reject in such case but resolves with an empty html.

@gdi2290 I'm also returning the index.html template in case of promise rejection. but when the promise resolved I assume that the pre-render process succeeded, and in the case I've mentioned the promise resolves with a blank html instead of the original index.html.

**Comment by gdi2290** [comment] 2017-01-08 03:57
will be fixed in ng4 
https://github.com/angular/angular/issues/13822

**Closed by gdi2290** 2017-01-08 03:57 UTC
