### ISSUE TITLE
Angular 12 Universal on Google App Engine error: ./my-app/server/main.js: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by shoomkloom** [angular/universal#2309] opened 2021-09-20 13:45 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I have an Angular 12 app that I converted to Universal.
After shmoozing it a bit it works locally as expected.
I deployed to Google AppEngine but get '500 Error: Server Error'.
Looking at the logs I see the error:
./my-app/server/main.js: Syntax error: "(" unexpected.

My app.yaml is simply:
runtime: nodejs14
entrypoint: ./my-app/server/main.js

I tried building with and without --prod but I still get the same error.
Any help will be appreciated...

Update:
When removing the entrypoint from app.yaml I get the error:
Error: Cannot find module '/workspace/server.js' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15) at Function.Module._load (internal/modules/cjs/loader.js

Here is the scripts section of package.json: 
(As generated automatically per instructions in 'https://angular.io/guide/universal')
{
"name": "my-app",
"version": "1.0.0",
"scripts":
{
"ng": "ng",
"start": "ng serve",
"build": "ng build",
"prod-build": "ng build --prod",
"test": "ng test",
"lint": "ng lint",
"e2e": "ng e2e",
"dev:ssr": "ng run my-app:serve-ssr",
"serve:ssr": "node dist/my-app/server/main.js",
"build:ssr": "ng build && ng run my-app:server",
"prerender": "ng run my-app:prerender"
},
...

### Please provide the exception or error you saw

```true
./my-app/server/main.js: Syntax error: "(" unexpected.
```

**Comment by alan-agius4** [comment] 2021-09-21 12:46
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by shoomkloom** [comment] 2021-09-21 12:58
Hi,
I actually got it working by doing the following:

1. I moved and renamed 'main.js' from '<project folder>\my-app\server\main.js' to '<project folder>\server.js'.
So my working folder tree looks like this:
<project folder>
        server.js
        my-app
                browser
2. Removed 'entrypoint' from app.yaml.

It seems the problem is with the universal automatic code generator...

**Comment by alan-agius4** [comment] 2021-09-21 13:01
The server. bundle is named `main.js`, I am not sure from were you got a file named `server.js`.

**Comment by alan-agius4** [comment] 2021-09-21 13:06
Actually, just remember that previously we did use `server.js` but this was about 2-3 years ago. When updating to Angular 9 using `ng update` this should have been replaced with `main.js`.

**Comment by shoomkloom** [comment] 2021-09-21 13:07
I assumed 'main.js' had the code AppEngine expected to find in server.js, and it worked.
See my original post:

> Update:
When removing the entrypoint from app.yaml I get the error:
Error: Cannot find module '**/workspace/server.js**' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15) at Function.Module._load (internal/modules/cjs/loader.js<br/>

**Comment by shoomkloom** [comment] 2021-09-21 13:09
> Actually, just remember that previously we did use `server.js` but this was about 2-3 years ago. When updating to Angular 9 using `ng update` this should have been replaced with `main.js`.

The universal build did produce a 'main.js' file but I guess the Google AppEngine team didn't get the memo... ;-)

**Comment by shoomkloom** [comment] 2021-09-21 13:10
> We don't generate any reference to `server.js`, this seem something custom to the project.

I know, I moved and renamed it manually just to get things to work...

**Comment by alan-agius4** [comment] 2021-09-21 13:16
You need to configuration your Google App Engine to handle the correct folder structure and spawning of node.js



```yaml
runtime: nodejs14
entrypoint: node /my-app/server/main.js
```

See: https://cloud.google.com/appengine/docs/standard/nodejs/config/appref#entrypoint and https://cloud.google.com/appengine/docs/standard/nodejs/runtime#application_startup

Closing since this appears to be a mis-configuration issue in the users project.

**Closed by alan-agius4** 2021-09-21 13:16 UTC
Labels: need: repro steps

**Comment by shoomkloom** [comment] 2021-09-21 13:20
I didn't find any reference to this anywhere in the documentation...
Thanks, I'll give it a try.
