### ISSUE TITLE
App crash After running `npm run server:ssr` 

### ISSUE THREAD

**Issue by waseem-isaac-BBN** [angular/universal#1305] opened 2019-10-23 13:52 UTC
```
npm ERR! file C:\Program Files\git\bin\bash.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! my-project@0.0.0 ssr-only: `ng run my-project:server:production && npm run compile:server && node dist/server`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the my-project@0.0.0 ssr-only script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2019-10-23T13_46_57_862Z-debug.log
```

...
**package.json**

    "@angular/core": "^7.2.7",
    "@angular/platform-server": "^7.2.7",
    "@angular/pwa": "^0.12.4",
    "@angular/service-worker": "^7.2.7",
    "@nguniversal/express-engine": "^7.1.1",
    "@nguniversal/module-map-ngfactory-loader": "^7.1.1",

**server.ts**
 
    ...
    app.engine('html', (_, options, callback) => {
      const engine = ngExpressEngine({
        bootstrap: AppServerModuleNgFactory,
        providers: [
          provideModuleMap(LAZY_MODULE_MAP),
          {provide: 'host', useFactory: () => options.req.get('host'), deps: []}
        ]
      });
      engine(_, options, callback);
    });
    
    app.set('view engine', 'html');
    app.set('views', join(DIST_FOLDER, 'browser'));
    
    // Serve static files from /browser
    app.get('*.*', express.static(join(DIST_FOLDER, 'browser'), {
      maxAge: '1y'
    }));
    
    // All regular routes use the Universal engine
    // app.get('*', (req, res) => {
    //   res.render('index', {req});
    // });
    
    app.get('*', (req, res) => { res.sendFile( join(DIST_FOLDER, 'browser' , 'index.html'), {req}); });
    
**tsconfig.server.json**

   ```
{
  "extends": "./tsconfig.app.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app-server",
    "baseUrl": "."
  },
  "angularCompilerOptions": {
    "entryModule": "app/app.server.module#AppServerModule"
  }
}


```

**angular.json**

   ```
  ....
   "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/server",
            "main": "src/main.server.ts",
            "tsConfig": "src/tsconfig.server.json"
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }
        }
      ....
```

**package.json**

   ```
 "scripts": {
   ...
  "compile:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:ssr": "node dist/server",
    "build:ssr": "npm run build:client-and-server-bundles && npm run compile:server",
    "build:client-and-server-bundles": "ng build --prod && ng run my-project:server:production",
    "ssr-only": "ng run my-project:server:production && npm run compile:server && node dist/server"
   ....
}
```
What's wrong in my project?

**Comment by vikerman** [comment] 2019-10-23 20:41
Can you post the error message log from the logs? Can't see the problem from the current issue.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2019-10-23T13_46_57_862Z-debug.

**Comment by waseem-isaac-BBN** [comment] 2019-10-24 08:19
@vikerman 
The content of the debug-log file

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'serve:ssr'
1 verbose cli ]
2 info using npm@6.12.0
3 info using node@v12.13.0
4 verbose run-script [ 'preserve:ssr', 'serve:ssr', 'postserve:ssr' ]
5 info lifecycle new-project-x@0.0.0~preserve:ssr: new-project-x@0.0.0
6 info lifecycle new-project-x@0.0.0~serve:ssr: new-project-x@0.0.0
7 verbose lifecycle new-project-x@0.0.0~serve:ssr: unsafe-perm in lifecycle true
8 verbose lifecycle new-project-x@0.0.0~serve:ssr: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\zvendo\new-project-x\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files\nodejs\;C:\Users\WaseemIsaacIbrahim\AppData\Local\Microsoft\WindowsApps;C:\Users\WaseemIsaacIbrahim\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\WaseemIsaacIbrahim\AppData\Roaming\npm
9 verbose lifecycle new-project-x@0.0.0~serve:ssr: CWD: D:\zvendo\new-project-x
10 silly lifecycle new-project-x@0.0.0~serve:ssr: Args: [ '-c', 'node dist/server' ]
11 info lifecycle new-project-x@0.0.0~serve:ssr: Failed to exec serve:ssr script
12 verbose stack Error: new-project-x@0.0.0 serve:ssr: `node dist/server`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:210:5)
12 verbose stack     at maybeClose (internal/child_process.js:1021:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
13 verbose pkgid new-project-x@0.0.0
14 verbose cwd D:\zvendo\new-project-x
15 verbose Windows_NT 10.0.17763
16 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve:ssr"
17 verbose node v12.13.0
18 verbose npm  v6.12.0
19 error code ELIFECYCLE
20 error syscall spawn
21 error file C:\Program Files\git\bin\bash.exe
22 error errno ENOENT
23 error new-project-x@0.0.0 serve:ssr: `node dist/server`
23 error spawn ENOENT
24 error Failed at the new-project-x@0.0.0 serve:ssr script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

```

**Comment by waseem-isaac-BBN** [comment] 2019-10-24 11:23
@vikerman 
I just removed some console.logs . the error turned into `ERROR RangeError: Maximum call stack size exceeded` then crashed.
I updated the issue body. Please see the top of the page.
I'm trying to identify what/where the error in my code by following the server.js lines appears on that error message

**Comment by waseem-isaac-BBN** [comment] 2019-10-24 11:44
@vikerman 
when ÷ changeي `res.render('index', { req });` to `res.sendFile(DIST_FOLDER + '/index.html', { req }) `
the website open and the error disappear ... but the pages not server-side compiled (still compiled by the browser).

Do u have any idea?

**Comment by alan-agius4** [comment] 2019-10-25 07:14
That is because of this line `app.set('views', join(DIST_FOLDER, 'browser'));`

**Comment by alan-agius4** [comment] 2019-10-25 07:17
That is because the `.sendFile` will just send the `index.html` as is, without doing any server side rendering of the application.

**Comment by waseem-isaac-BBN** [comment] 2019-10-27 10:48
@alan-agius4 So , what's the problem :)) ?

**Comment by CaerusKaru** [comment] 2019-10-27 10:57
If I had to guess, the issue is that the command that gets added by our schematics is UNIX-based: `dist/server`, which cannot he found for Windows users because that’s not a valid Windows path. If you change it to be Windows-based and go back to `.render` it should work.

@alan-agius4 is this patched in our latest schematics or do we need to fix this?

**Comment by alan-agius4** [comment] 2019-10-27 11:01
That path should also work on Windows.

Just to confirm something, are you running `npm run build:client-and-server-bundles` prior to `npm run serve:ssr`?

**Comment by alan-agius4** [comment] 2019-10-27 11:04
Posix paths should work fine in Windows.

**Comment by waseem-isaac-BBN** [comment] 2019-10-27 11:28
@alan-agius4 Yes

**Comment by alan-agius4** [comment] 2019-10-27 13:00
Can you please share a reproduction?

**Comment by alan-agius4** [comment] 2019-11-30 18:43
Closing as the author didn’t get back to us.

If you are sill experiencing the issue, please feel free to open a new bug report with a minimal reproduction.

**Closed by alan-agius4** 2019-11-30 18:43 UTC
Labels: state: Need repro
