### ISSUE TITLE
Prerendering breaks with nested paths

### ISSUE THREAD

**Issue by fmalcher** [angular/universal#1375] opened 2019-12-10 09:55 UTC
# Bug Report

#### Situation

App routes:

```
{ path: 'dashboard', component: DashboardComponent },
{ path: 'item/:id', component: DetailsComponent },
```

`routes` option for the `prerender` builder is set to (in angular.json):

```
"routes": [
        "/dashboard",
        "/item/bed",
        "/item/garden"
]
```

#### What is the current behavior?

```
Prerendering 3 route(s) to /Users/fmalcher/angular-schule/ssr-playground/dist/browser
CREATE /Users/fmalcher/angular-schule/ssr-playground/dist/browser/dashboard/index.html (3746 bytes)
Unable to render /Users/fmalcher/angular-schule/ssr-playground/dist/browser/item/bed/index.html
Unable to render /Users/fmalcher/angular-schule/ssr-playground/dist/browser/item/garden/index.html
```

⚠️  Works fine if I change it as follows:

App routes:

```
{ path: 'dashboard', component: DashboardComponent },
{ path: 'dashboard/:id', component: DetailsComponent },
```

`routes` option:

```
"routes": [
        "/dashboard",
        "/dashboard/bed",
        "/dashboard/garden"
]
```

=> Seems to be related to nested paths where the intermediate segments don't exist as a route.

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Environment:
```
Angular CLI: 9.0.0-rc.5
Node: 10.15.1
OS: darwin x64

Angular: 9.0.0-rc.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.5
@angular-devkit/build-angular     0.900.0-rc.5
@angular-devkit/build-optimizer   0.900.0-rc.5
@angular-devkit/build-webpack     0.900.0-rc.5
@angular-devkit/core              9.0.0-rc.5
@angular-devkit/schematics        9.0.0-rc.5
@ngtools/webpack                  9.0.0-rc.5
@nguniversal/builders             9.0.0-next.9
@nguniversal/common               9.0.0-next.9
@nguniversal/express-engine       9.0.0-next.9
@schematics/angular               9.0.0-rc.5
@schematics/update                0.900.0-rc.5
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
```

**Comment by vikerman** [comment] 2019-12-10 18:34
Thanks for reporting.

It's a bug in the prerender builder where it is not creating a nested folder first before writing to the index.html. Will be fixed in subsequent release.

**Comment by wagnermaciel** [comment] 2019-12-10 22:41
Thanks again for reporting this!

Just wanted to confirm here that the cause of the issue is with writing the file.

Because of the nested paths, we are incorrectly calling `fs.mkdirSync("/item/bed")` without having created an `item` directory.

All we need to do is add the recursive option
`fs.mkdirSync(outputFolderPath, { recursive: true })`

**Closed** 2019-12-11 22:04 UTC
Labels: comp: builders, type: bug/fix
