### ISSUE TITLE
error after updating to angular 9 | keeps crashing | memory consumption

### ISSUE THREAD

**Issue by GlauberF** [angular/universal#1658] opened 2020-05-03 18:38 UTC
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Description

After updating to version 9 of angular, my files server.ts and webpack.server.config.js

old server.ts file: https://gist.github.com/GlauberF/2c8c6faca4a677be9e2390365c35c76c
new server.ts file: https://gist.github.com/GlauberF/77d9c1dd5967256d78770178fb72d468

In the case of the webpack.server.config.js file, a new one was not created, only the one I had was renamed with .bak
webpack.server.config.js.bak: https://gist.github.com/GlauberF/5e55beb4f988fd34b9c7c2e0df559b02

Now I'm not sure what to do, because before in version 8 it was working 100% with files now renamed .bak

my package.json file: https://gist.github.com/GlauberF/79c30f7e3e1e4016824d50e973249330

if someone can help me, how would these files look.
how to solve problems and be able to compile, because I'm currently stuck, unable to upload new features, because I can't generate build

## 🔥 Exception or Error
The compilation is consuming a lot of memory and reaches 92% of the image below and does not come out of it.
And before upgrading to version 9, everything worked, so something tells me that it may be related to the files that will be modified.
If you can tell me how the files would look, because the way they were, it’s not working

![Captura de Tela_20200503181411](https://user-images.githubusercontent.com/11314585/80957678-0ab14c80-8dda-11ea-8b8a-affd4c584e8b.png)

if I test it in development, it stays at 10% and it doesn't go away.
Problem I have no way of knowing if something is wrong or what is wrong.
![Captura de Tela_selecionar área_20200504103420](https://user-images.githubusercontent.com/11314585/80971040-8f0fc980-8df2-11ea-9f83-cf9e6d9ea4c8.png)

about the memory consumption part, I'm having to put **node --max_old_space_size = 6072 ./node_modules/@angular/cli/bin/ng ...** because before that I had the following errors:
![Captura de Tela_selecionar área_20200504110759](https://user-images.githubusercontent.com/11314585/80974575-49093480-8df7-11ea-8e1b-356ffc19925d.png)

![Captura de Tela_selecionar área_20200504110812](https://user-images.githubusercontent.com/11314585/80974585-4c042500-8df7-11ea-87ac-88ea98f288d8.png)

## 🌍 Your Environment
```
Angular CLI: 9.1.4
Node: 10.15.3
OS: linux x64

Angular: 9.1.3
... animations, common, compiler, core, forms, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.4
@angular-devkit/build-angular      0.901.4
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.4
@angular-devkit/core               9.1.4
@angular-devkit/schematics         9.1.4
@angular/cdk                       9.2.1
@angular/cli                       9.1.4
@angular/compiler-cli              9.1.4
@angular/flex-layout               9.0.0-beta.29
@angular/language-service          9.1.4
@angular/material                  9.2.1
@angular/material-moment-adapter   9.2.1
@ngtools/webpack                   9.1.4
@nguniversal/builders              9.1.0
@nguniversal/common                9.1.0
@nguniversal/express-engine        9.1.0
@schematics/angular                9.1.4
@schematics/update                 0.901.4
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
```

**Comment by alan-agius4** [comment] 2020-05-04 15:04
Duplicate of https://github.com/angular/angular-cli/issues/17620

**Closed by alan-agius4** 2020-05-04 15:04 UTC
