### ISSUE TITLE
package.json does not exist with firebase.

### ISSUE THREAD

**Issue by akilah007** [angular/universal#1513] opened 2020-02-17 11:43 UTC
I have tried with `--bundleDependencies false ` but didn't work. I the issue with firebase. Any help

## 🔥 Exception or Error
<pre><code>
!function(e,a){for(var i in a)e[i]=a[i]}(exports,function(modules){var installedModules={},installedChunks={0:0};function __webpack_require__(moduleId){if(installedModules[moduleId])return installedModules[moduleId].exports;var module=installedModules[moduleId]={i:moduleId,l:!1,exports:{}};return modules[moduleId].call(module.exports,module,module.exports,__webpack_require__),module.l=!0,module.exports}return __webpack_require__.e=function requireEnsure(chunkId){if(0!==installedChunks[chunkId]){var chunk=require("./"+({1:"vendors~firebase-auth"}[chunkId]||chunkId)+".js"),moreModules=chunk.modules,chunkIds=chunk.ids;for(var moduleId in moreModules)modules[moduleId]=moreModules[moduleId];for(var i=0;i<chunkIds.length;i++)installedChunks[chunkIds[i]]=0}return Promise.all([])},__webpack_require__.m=modules,__webpack_require__.c=installedModules,__webpack_require__.d=function(exports,name,getter){__webpack_require__.o(exports,name)||Object.definePro

Error: Cannot find module '/Users/admin/Projects/.../package.json'
    at Object.PsoT.exports.find (/Users/admin/Projects/chartzlk2/dist/chartzlk2/server/main.js:1:2824658)
    at Object.wPNL (/Users/admin/Projects/chartzlk2/dist/chartzlk2/server/main.js:1:5029664)
    at __webpack_require__ (/Users/admin/Projects/chartzlk2/dist/chartzlk2/server/main.js:1:317)
    at Object.XpdW (/Users/admin/Projects/chartzlk2/dist/chartzlk2/server/main.js:1:3420686)
    at __webpack_require__ (/Users/admin/Projects/chartzlk2/dist/chartzlk2/server/main.js:1:317)
    at Object.g1pB (/Users/admin/Projects/chartzlk2/dist/chartzlk2/server/main.js:1:3979274)
    at __webpack_require__ (/Users/admin/Projects/chartzlk2/dist/chartzlk2/server/main.js:1:317)
    at Object.Ou8q (/Users/admin/Projects/chartzlk2/dist/chartzlk2/server/main.js:1:2750244)
    at __webpack_require__ (/Users/admin/Projects/chartzlk2/dist/chartzlk2/server/main.js:1:317)
    at Object.BYZf (/Users/admin/Projects/chartzlk2/dist/chartzlk2/server/main.js:1:1915718)
npm ERR! code ELIFECYCLE
</code></pre>
## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.2
Node: 10.16.3
OS: darwin x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.2
@angular/cdk                      9.0.0
@angular/cli                      9.0.2
@angular/fire                     6.0.0-rc.1
@angular/material                 9.0.0
@ngtools/webpack                  9.0.2
@nguniversal/builders             9.0.0
@nguniversal/common               9.0.0
@nguniversal/express-engine       9.0.0
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by alan-agius4** [comment] 2020-02-17 14:56
Duplicate of https://github.com/angular/universal/issues/1207

See: https://github.com/angular/universal/issues/1207#issuecomment-572051903

**Closed by alan-agius4** 2020-02-17 14:56 UTC
