### ISSUE TITLE
$ is not defined at MzTooltipDirective.module

### ISSUE THREAD

**Issue by jaganchoccy** [angular/universal#1214] opened 2019-08-01 06:51 UTC
# Bug Report
#1209 $ is not defined at MzTooltipDirective.module
#### What is the expected behavior?
I am using ngx-materializecss in my angular application, its working fine in normal ng run but when I run i production issue occurs. in all ngx-materialize module.

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common:
  - express-engine:
  - hapi-engine:
  - module-map-ngfactory-loader:
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

#### Is there anything else we should know?

**Comment by CaerusKaru** [comment] 2019-08-01 07:00
As you know, this is a duplicate of https://github.com/angular/universal/issues/1073

**Closed by CaerusKaru** 2019-08-01 07:00 UTC
