### ISSUE TITLE
TypeError: __webpack_require__(...) is not a function

### ISSUE THREAD

**Issue by jrodl3r** [angular/universal#1195] opened 2019-07-06 20:42 UTC
getting this error on google cloud instance

```
TypeError: __webpack_require__(...) is not a function
    at Function.requireEnsure [as e] (/srv/dist/server.js:142734:49)
```
line 142734
```javascript
var chunk = __webpack_require__(421)("./" + ({"components-_admin-admin-module-ngfactory":
"components-_admin-admin-module-ngfactory"}[chunkId]||chunkId) + ".js");
```

#### What is the expected behavior?
Everything is working fine w/ new angualrfire auth-guards + v8 import-style lazy-loaded routes/modules, just getting this error (as well as #1169).

**Comment by vikerman** [comment] 2019-07-07 19:40
Can you please refer to the version 8 upgrade guide and see if it resolves your issue?

https://github.com/angular/universal/blob/master/docs/v8-upgrade-guide.md

**Comment by jrodl3r** [comment] 2019-07-09 02:43
@vikerman Dude, far out! That cleared all my errors/warnings out : )

**Comment by MarkPieszak** [comment] 2019-07-12 13:41
```
> node dist/server

/app/dist/server/main.js:166877
        throw new Error("package.json does not exist at " + package_json_path);
        ^

Error: package.json does not exist at /app/dist/package.json
```
@jrodl3r 	

Are you trying to access your package.json from your Node server file itself? This seems like it might be something a bit separate from Universal

**Comment by jrodl3r** [comment] 2019-07-15 19:59
> Are you trying to access your package.json from your Node server file itself?

not at all, just stock angular universal setup running on gcloud instance (node 10).

**Comment by vikerman** [comment] 2019-07-30 04:10
The package.json error seems to be a duplicate of #1207 
It seems we need a way to keep certain library as external and not try to bundle them as they don't work well bundled.

Can you provide info on which library the package.json might be referring to?

**Comment by vikerman** [comment] 2019-07-30 17:55
This seems a problem with angularfire. We are going to follow up with them.

Till then the workaround is to remove `--bundleDependencies all` from package.json

**Comment by alamgirqazi** [comment] 2019-12-03 09:06
> This seems a problem with angularfire. We are going to follow up with them.
> 
> Till then the workaround is to remove `--bundleDependencies all` from package.json

Hi, I tried the version upgrade after Upgrading to Angular 8. this one (https://github.com/vikerman/v8-lazy/commit/515239be1b233946e4a1d15a8712a0bc9f5490cc).

Now, when I'm building project, I get this error 

```
> node dist/server

....\node_modules\ng2-al-slim-bar\src\slim-loading-bar.component.js:13
import { Component, Input, ChangeDetectorRef, ChangeDetectionStrategy, ElementRef } from '@angular/core';
       ^

SyntaxError: Unexpected token {

```

I tried adding module: "commonjs" to tsconfig.server.ts but it didnot work. 

I tried it with 

```
--bundleDependencies all

```
and also without it but same response. 

Can you help me out here ? thanks. Surely this isn't a single library issue right?

**Comment by alan-agius4** [comment] 2019-12-03 09:35
@alamgirqazi, the error you are reporting seems to be different from `TypeError: __webpack_require__(...) is not a function` please file a new issue together with a reproduction that we can take a look at.

Thanks.

**Comment by alamgirqazi** [comment] 2019-12-03 09:38
> @alamgirqazi, the error you are reporting seems to be different from `TypeError: __webpack_require__(...) is not a function` please file a new issue together with a reproduction that we can take a look at.
> 
> Thanks.

I found a fix for this. It was just a library issue.

**Comment by alan-agius4** [comment] 2020-01-03 20:31
Let’s continue tracking this in #1207 since there is a repo.

Duplicate of #1207

**Comment by alan-agius4** [comment] 2020-01-03 20:49
Let’s continue tracking this in #1207 since there is a repo.

Duplicate of #1297

**Closed by alan-agius4** 2020-01-03 20:49 UTC
Labels: FAQ
