### ISSUE TITLE
Event is not defined

### ISSUE THREAD

**Issue by ildar-icoosoft** [angular/universal#1106] opened 2018-12-19 10:26 UTC
# Bug Report
When I call node dist/server.js I get error: Event is not defined.
I created simple Ionic application (with command ionic start), and injected angular universal.
Here is my repo: https://github.com/ildar-icoosoft/angular-universal-bug
This is pull request for angular universal: https://github.com/ildar-icoosoft/angular-universal-bug/pull/1
(I already merged it it master branch)
If I call npm run serve:ssr, then I get error: Event is not defined

#### Minimal reproduction with instructions:
1. clone https://github.com/ildar-icoosoft/angular-universal-bug
2. npm run build:ssr
3. npm run serve:ssr

```
Angular CLI: 7.0.7
Node: 11.0.0
OS: darwin x64
Angular: 7.0.4
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/animations               7.1.4
@angular/cli                      7.0.7
@angular/platform-server          7.1.4
@ngtools/webpack                  7.0.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1

**Comment by CaerusKaru** [comment] 2019-02-09 23:14
Duplicate of #844

**Closed by CaerusKaru** 2019-02-09 23:14 UTC
