### ISSUE TITLE
Java web server support

### ISSUE THREAD

**Issue by sergey-morenets** [angular/universal#721] opened 2017-05-23 08:47 UTC
* **I'm submitting a ...**
- [ ] bug report
- [x ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
N/A

* **Do you want to request a *feature* or report a *bug*?**

Request feature

* **What is the current behavior?**

N/A

* **What is the expected behavior?**

Java web servers(Tomcat or Jetty) should support Angular Universal.

* **What is the motivation / use case for changing the behavior?**

I want to use Angular Universal in Java projects.

* **Please tell us about your environment:**

- Angular version: 4.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: [Java]

Hi

Would it be possible to use Angular Universal together with any popular Java web server (Tomcat/Jetty)?  You mentioned in the description about Node.js/ASP.NET support only. If yes can you please supply tutorial/guide to follow?

Thanks

**Comment by wesleycho** [comment] 2017-05-25 06:19
It should theoretically be possible to have it run on a Java server if [Nashorn](http://www.oracle.com/technetwork/articles/java/jf14-nashorn-2126515.html) is utilized, so this is probably a possibility to implement an engine for.

**Comment by MarkPieszak** [comment] 2017-05-29 20:40
Duplicate of #280.

**Closed by MarkPieszak** 2017-05-29 20:40 UTC
