### ISSUE TITLE
Implement cache for other methods in TransferHttpCacheModule

### ISSUE THREAD

**Issue by kirill-chirkov-at-clouty** [angular/universal#1086] opened 2018-10-18 09:31 UTC
# Feature Request

#### What is the desired behavior?
Implement options for state transfer of modifying requests such as POST or PUT, e.g.:
```
imports: [
    TransferHttpCacheModule.forRoot({
        cachedMethods: ['GET', 'POST', 'PUT']
    }),
]
```

#### What is the use-case or motivation for the desired behavior?
On our backend there are certain endpoints that use POST request for searching, because it requires a large JSON in payload. This request is intended to be cached, hovewer it is impossible with current mechanism.

**Comment by CaerusKaru** [comment] 2018-10-18 12:51
Duplicate of #986

**Closed by CaerusKaru** 2018-10-18 12:51 UTC
