### ISSUE TITLE
Hot Module Replacement - Empty App Root after Hot Reload

### ISSUE THREAD

**Issue by Tim-mhn** [angular/universal#2218] opened 2021-07-27 09:21 UTC
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine

### Is this a regression?

No, I have tried with @angular/cli, @angular-devkit/build-angular, @nguniversal/builders and @nguniversal/express-engine 11 and the bug was also present.

### Description

I want to use Angular's built-in Hot Module Replacement feature, that was released with Angular 11. 

I run `ng serve --hmr`. 

The application starts normally and indicates that HMR is enabled: `NOTICE: Hot Module Replacement (HMR) is enabled for the dev server.` Opening my app on the browser works fine.

When I make a change, I can see the hot reload happening on my terminal as well as on my browser's Dev Tools. 
But I get an **empty page and when inspecting elements on Dev Tools, I can see that the `app-root` component is empty**. If I refresh the page (F5), the app is rendered as expected with the changes.

Logs in the Dev Tools:
```
App hot update... reloadApp.js:19
[HMR] Checking for updates on the server... log.js:24
[HMR] Updated modules: log.js:24
[HMR]  - 8549 log.js:24
[HMR]  - 403 log.js:24
[HMR]  - 8847 log.js:24
[HMR]  - 8738 log.js:24
[HMR]  - 4621 log.js:24
[HMR]  - 3370 log.js:24
[HMR]  - 7582
```

This project uses Lazy-loaded routes + Angular Universal. 

**Important**: The issue appeared **after adding Angular Universal to the project** with the following command `ng add @nguniversal/express-engine`

## 🔬 Minimal Reproduction

I have created a simple [repo ](https://github.com/Tim-mhn/angular-universal-hmr) with Angular 12 + Angular Universal that reproduces the bug 

Just run `npm i && ng serve --hmr`

## 🔥 Exception or Error

<pre><code>
No specific error message
</code></pre>

## 🌍 Your Environment

<pre><code>
WSL2 with Ubuntu 20.04.1 LTS 
(I have also been able to reproduce the issue on Window 10 so probably not a WSL specific issue. + my project is within the WSL filesystem)

Angular CLI: 12.1.3
Node: 14.15.5
Package Manager: npm 6.14.11
OS: linux x64
@angular-devkit/architect       0.1201.3
@angular-devkit/build-angular   12.1.3
@angular-devkit/core            12.1.3
@angular-devkit/schematics      12.1.3
@nguniversal/builders           12.1.0
@nguniversal/express-engine     12.1.0
@schematics/angular             12.1.3
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Comment by alan-agius4** [comment] 2021-07-27 09:39
I believe this is caused by the fact that the bootstrapping call is wrapped.

https://github.com/Tim-mhn/angular-universal-hmr/blob/f404231fc080b4d2576823a425e471fac3475073/src/main.ts#L11

**Comment by Tim-mhn** [comment] 2021-07-28 03:54
@alan-agius4 Thanks, that was exactly the source of the issue.

Inspired by [PatrickJS's Angular-HMR](https://github.com/PatrickJS/angular-hmr), I've updated my main.ts file with this piece of code:

```
if (document.readyState === 'complete') {
    main()
  } else {
    document.addEventListener('DOMContentLoaded', main);
  }
```

With this update, it works !

**Comment by alan-agius4** [comment] 2023-01-25 10:12
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.

**Closed by alan-agius4** 2023-01-25 10:12 UTC
