### ISSUE TITLE
Setting CSS custom property on server side using injected Document object throws an error

### ISSUE THREAD

**Issue by ilia-ametov** [angular/universal#2163] opened 2021-06-09 22:50 UTC
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine

### Is this a regression?

No

### Description

I use CSS custom properties to style application based on settings, which loaded from API. This works great in browser but throws exception when running on server side.

## 🔬 Minimal Reproduction

```TypeScript
import { Component, Inject } from '@angular/core';
import { DOCUMENT } from "@angular/common";

@Component({
  selector: 'app-root',
  template: `<h2>document-set-css-variable-bug</h2>`,
  styles: [`
    h2 {
      color: var(--custom-color);
    }
  `]
})
export class AppComponent {
  
  constructor(@Inject(DOCUMENT) documentRef: Document) {
    documentRef.body.style.setProperty("color", "#002c8d"); // this works
    documentRef.body.style.setProperty("--custom-color", "#d40420"); // this line throws an error
  }
  
}
```
GitHub repository with the reproduction of the issue:
https://github.com/ilia-ametov/set-css-custom-property-bug
<code>npm run dev:ssr</code>

## 🔥 Exception or Error

<pre><code>
TypeError: Cannot read property 'type' of undefined
    at TokenStream.LA (C:\Projects\browser\set-css-custom-property-bug\dist\set-css-custom-property-bug\server\main.js:122018:30)
    at TokenStream.advance (C:\Projects\browser\set-css-custom-property-bug\dist\set-css-custom-property-bug\server\main.js:121891:20)
    at Parser._readDeclarations (C:\Projects\browser\set-css-custom-property-bug\dist\set-css-custom-property-bug\server\main.js:124610:42)
    at Parser.parseStyleAttribute (C:\Projects\browser\set-css-custom-property-bug\dist\set-css-custom-property-bug\server\main.js:124789:22)
    at parseStyles (C:\Projects\browser\set-css-custom-property-bug\dist\set-css-custom-property-bug\server\main.js:103796:10)
    at CSSStyleDeclaration.value (C:\Projects\browser\set-css-custom-property-bug\dist\set-css-custom-property-bug\server\main.js:103915:22)
    at new AppComponent (C:\Projects\browser\set-css-custom-property-bug\dist\set-css-custom-property-bug\server\main.js:163822:32)
    at NodeInjectorFactory.AppComponent_Factory [as factory] (C:\Projects\browser\set-css-custom-property-bug\dist\set-css-custom-property-bug\server\main.js:163825:63)
    at getNodeInjectable (C:\Projects\browser\set-css-custom-property-bug\dist\set-css-custom-property-bug\server\main.js:49176:44)
    at instantiateRootComponent (C:\Projects\browser\set-css-custom-property-bug\dist\set-css-custom-property-bug\server\main.js:55747:23)
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.0.3
Node: 14.17.0
Package Manager: npm 7.16.0
OS: win32 x64

Angular: 12.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.3
@angular-devkit/build-angular   12.0.3
@angular-devkit/core            12.0.3
@angular-devkit/schematics      12.0.3
@angular/cli                    12.0.3
@nguniversal/builders           12.0.1
@nguniversal/express-engine     12.0.1
@schematics/angular             12.0.3
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Comment by alan-agius4** [comment] 2021-06-10 05:42
Duplicate of https://github.com/angular/angular/issues/42170

**Closed by alan-agius4** 2021-06-10 05:42 UTC
