### ISSUE TITLE
Heap memory out issue in the new jsdom based SSR engine

### ISSUE THREAD

**Issue by sandeep-venugopal** [angular/universal#2733] opened 2022-07-05 10:50 UTC
**Background**
We recently changed the SSR rendering engine in our angular ssr app from express to clover. (We had to change the rendering engine in order to implement Microfrontends). 

**Issue:**
We are using the new jsdom based ssr engine **clover** via the  `@nguniversal/common`, (12.1.0)  but our app is experiencing Heap memory out issue.

As the requests to the node server increases, we are seeing that heap memory is also increasing  continuously and garbage collection is not happening. At around 400rpm, it is crashing with this error.  We observed that at this requests rate, memory becomes 1GB in one or 2 minutes of running the app.

**FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory**

** version details**
    "@angular/compiler": "12.2.10",
    "@angular/core": "12.2.10",
    "@nguniversal/express-engine": "^11.2.1",
    "@nguniversal/common": "12.1.0",
    "@nguniversal/builders": "11.2.1"

Same app is working fine and is in production with express engine. 

Can anyone help us with any pointers regarding this? 

OR 
can you confirm if clover engine is production ready?

**Comment by alan-agius4** [comment] 2022-07-08 11:12
Clover is still experimental. Would you be able to provide heap snapshots?

**Comment by alan-agius4** [comment] 2022-07-22 11:00
Looks like the contents of the bundles are being retained multiple times. Will continue looking into this in the coming days.

**Comment by alan-agius4** [comment] 2022-07-26 17:59
Looks like this is caused by https://github.com/jsdom/jsdom/issues/3408

See: #2761

**Comment by alan-agius4** [comment] 2022-10-07 18:27
Closing as this is not actionable from our end. See above comment.

**Closed by alan-agius4** 2022-10-07 18:27 UTC
Labels: comp: common
