### ISSUE TITLE
Server side not render http requests [Angular Universal, universal-cli]

### ISSUE THREAD

**Issue by vforv** [angular/universal#674] opened 2017-03-12 14:35 UTC
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [x] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [x] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**
I want to report bug...

* **What is the current behavior?**
I am using universal-cli... Problem is with rendering on server side, http requests not display... Check here live example: http://pushsc.com/show/code/58bc83760a58d602a0b99d14 ... Just 'view source' everthing that comes from http request not displayed like: title, code, description, etc... 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
 Here is live example: http://pushsc.com/show/code/58bc83760a58d602a0b99d14

Exaple of showcode.service.ts:
```
import { Injectable } from '@angular/core';
import { Http, Response } from '@angular/http';
import { environment } from '../../environments/environment';

@Injectable()
export class ShowcodeService {

  constructor(private http: Http) { }

  getCode(id): any{
     return this.http.get(environment.baseUrl + 'code/show/' + id)
        .map((response: Response) => response.json());
  };
  
}

```

`server.ts` I didn't change anything here from universal-cli:

```
/**
 * the polyfills must be the first thing imported
 */
import './polyfills.ts';
import './__2.1.1.workaround.ts'; // temporary until 2.1.1 things are patched in Core
import * as path from 'path';
import * as express from 'express';
import * as compression from 'compression';
import { createEngine } from 'angular2-express-engine';
import { enableProdMode } from '@angular/core';
import { NodeAppModule } from './app/app.node.module';
import { environment } from './environments/environment';
import { routes } from './server.routes';

// App

const app  = express();
const ROOT = path.join(path.resolve(__dirname, '..'));
const port = process.env.PORT || 4200;

/**
 * enable prod mode for production environments
 */
if (environment.production) {
  enableProdMode();
}

/**
 * Express View
 */
app.engine('.html', createEngine({}));
app.set('views', path.join(ROOT, 'client'));
app.set('view engine', 'html');

/**
 * Enable compression
 */
app.use(compression());

/**
 * serve static files
 */
app.use('/', express.static(path.join(ROOT, 'client'), {index: false}));

/**
 * place your api routes here
 */
// app.use('/api', api);

/**
 * bootstrap universal app
 * @param req
 * @param res
 */
function ngApp(req: any, res: any) {
  res.render('index', {
    req,
    res,
    ngModule: NodeAppModule,
    preboot: false,
    baseUrl: '/',
    requestUrl: req.originalUrl,
    originUrl: req.hostname
  });
}

/**
 * use universal for specific routes
 */
app.get('/', ngApp);
routes.forEach(route => {
  app.get(`/${route}`, ngApp);
  app.get(`/${route}/*`, ngApp);
});

/**
 * if you want to use universal for all routes, you can use the '*' wildcard
 */

app.get('*', function (req: any, res: any) {
  res.setHeader('Content-Type', 'application/json');
  const pojo = {status: 404, message: 'No Content'};
  const json = JSON.stringify(pojo, null, 2);
  res.status(404).send(json);
});

app.listen(port, () => {
  console.log(`Listening on port ${port}`);
});
```

* **What is the expected behavior?**
To get rendered http request on server side... And when I view source to see data...

* **What is the motivation / use case for changing the behavior?**
SEO

* **Please tell us about your environment:**

I am using last version of universal-cli

- Angular version: 2.0.0-rc.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: TypeScript X.X
- OS:  Linux 
- Platform: NodeJs

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

http://stackoverflow.com/questions/42742169/server-side-not-render-http-requests-angular-universal?noredirect=1#comment72613523_42742169

**Comment by wesleycho** [comment] 2017-04-08 03:31
Can you clarify what is meant? Is the bug report that the http request is not executed inside Node but on the client?

**Comment by MarkPieszak** [comment] 2017-04-25 14:24
angular2-universal has since moved to @angular/platform-server within Angular Core, can you try upgrading your project and see if this issue has been fixed? Closing this out for now!

Also note the universal-cli has been deprecated, there are some efforts to create some support within the angular-cli but it will be a bit different.

You can check out the upgrade guide from angular2-universal -> platform-server we have here as well: https://github.com/angular/universal/blob/master/UPGRADE-GUIDE.md

**Closed by MarkPieszak** 2017-04-25 14:24 UTC

**Comment by mariohmol** [comment] 2017-04-25 14:31
Hi @MarkPieszak  i was just answergin this.. 

I looked in this link example and seems to be rendering the html inside the `</app-codetree>`. So i think for this case its ok to close.

Actually i'm facing similar problem. My app works pretty good using the univeral, but looking in the requests it shows me on the html somthing like `<body>  <demo-app></demo-app></body>`.
I suppose something is wrong..  so i opened this stack question..

Quite lost what version to use of NgExpressEngine

http://stackoverflow.com/questions/43613514/angular4-universal-server-side-rending-would-return-more-html-rendered-on-reques

**Comment by MarkPieszak** [comment] 2017-04-25 15:13
@mariohmol Use the official `@nguniversal/express-engine`, I'm not sure where the other one came from but it looks like someone took an older version of the engine (when it was a WIP) and published it themselves (?)

The namespace is now going to be `@nguniversal` though so give that one a shot and you should be fine!

**Comment by mariohmol** [comment] 2017-04-25 16:52
Hi!! Thanks for getting in touch!  I opened a issue for this case, if you can follow here please
https://github.com/angular/universal/issues/701#issuecomment-297080994

**Comment by vforv** [comment] 2017-04-25 20:07
I solved this, problem was with intercepotor on node side... But now I don't have authentication on server side, how to solve it?

**Comment by mariohmol** [comment] 2017-04-25 20:28
I have this working but not with SSR working fully.. my problem is that i'm using angular-material.. so i think will wait for the next universal release that will support that to make more changes.. what i have so far https://github.com/mariohmol/ng-universal-demo

**Comment by ofrebourg** [comment] 2017-08-15 15:57
People who landed on this page might be interested on this demo version, which contains an API example retrieving data from an external web service. I also added support for LESS files.
https://github.com/ofrebourg/ng-universal-demo

_However, note that the use of ExtractTextPlugin in webpack.common.js broke the AOT build in that version. webpack.common.js contains a few commented lines with which AOT builds fine, but I'm not a big fan of that solution._

**Comment by merihs** [comment] 2017-08-31 13:52
@ofrebourg Thanks it is a good sample demo. But unfortunately prod build didn't worked. I used "npm run build:prod" command as you write in demo. It creates client js files in dist folder but It doesn't create server js files. I checked FrozenPandaz demos and run the same command and it worked successfully.

**Comment by patrickmichalina** [comment] 2017-08-31 14:04
@merihs try this starter https://github.com/patrickmichalina/fusebox-angular-universal-starter

**Comment by ofrebourg** [comment] 2017-08-31 14:29
@merihs Thanks. The problem with the prod build is the same as with the AOT build. There are comments in webpack.common.js to fix this (i.e. make it build for aot and prod). Maybe it should be the default. I can change that if that helps

**Comment by ofrebourg** [comment] 2017-08-31 14:45
@patrickmichalina Your starter project looks great, I'll have a more in-depth look at it and might rebase my code onto your solution

**Comment by MarkPieszak** [comment] 2017-08-31 15:28
I'd also suggest just using the Angular CLI w/ Universal, that way you can stay in line with everything as it updates. @ofrebourg

**Comment by merihs** [comment] 2017-08-31 15:29
Thanks for your quick responses guys..
@ofrebourg You are right It worked successfully. Thanks
@patrickmichalina It looks great, thanks. I am not familiar with fuse-box but I will check it soon.

**Comment by evgenyetoro** [comment] 2018-03-08 14:37
Have the same issue here. 
I have a component which gets page texts from the service through HTTP call.
After ssr rendering there's no text in page source

**Comment by Toxicable** [comment] 2018-03-08 17:22
@evgenyetoro If you have an issue i'd suggest opening up a ticket with a minimal reproduction of the issue. We don't monitor closed issues

**Comment by chriseugenerodriguez** [comment] 2018-07-14 23:11
Can you paste your solution!

**Comment by chriseugenerodriguez** [comment] 2018-07-31 03:14
The problem is that you need to render your http requests before DOM load. Attach an rxjs attach an observable to route to require http requests render before page is done.

**Comment by intergleam** [comment] 2018-09-20 12:55
ok i did the repo https://github.com/intergleam/universal-starter/commits/master
minimum changes
