### ISSUE TITLE
Wrong behaviour when extends from Http

### ISSUE THREAD

**Issue by thebarada** [angular/universal#611] opened 2016-10-27 22:51 UTC
- **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
- **What modules are related to this Issue?**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [x] universal
- [ ] webpack-prerender
- **Do you want to request a _feature_ or report a _bug_?**
  Report a bug
- **What is the current behavior?**
  Using class for customize http requests and extends from Http
  asynchronous data, that fetched from server, does not rendered (serverside)
  Also, setTimeout does not block application

Current behavior
In response Home component looks like

```
Home component
<p>Hi! My name is </p>
```
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

repo - [thebarada/universal-starter](https://github.com/thebarada/universal-starter)

commit - [thebarada/universal-starter#be67335](https://github.com/thebarada/universal-starter/commit/be67335200491016d5a3b76715cb037e41cf7ff1)

Just run `npm start`
- **What is the expected behavior?**
  In response Home component should looks like

```
Home component
<p>Hi! My name is name after timeout</p>
```
- **What is the motivation / use case for changing the behavior?**
  In my case I tried set meta tags for sharing, but it impossible
- **Please tell us about your environment:**
- Angular version: 2.1.0
- Browser: all
- Language: TypeScript 2.0.2
- OS:  macOs Siera
- Platform: NodeJs

**Comment by MarkPieszak** [comment] 2016-11-22 00:40
I couldn't get your repo working for some reason, but tested it in a different one.

So the problem is that we're already extending `Http` inside Universal, but if you want to extend *that* even further... Just extend our class even further.

```
import { PreloadHttp } from 'angular2-universal';

@Injectable()
export class MyHttpService extends PreloadHttp {
  constructor(backend: XHRBackend, defaultOptions: RequestOptions) {
    defaultOptions.headers.append(
      'Content-Type',
      'application/json; charset=utf-8'
    );
    super(backend, defaultOptions);
  }
}
```

That should do the trick! Let me know if you run into any problems.

**Comment by MarkPieszak** [comment] 2016-11-22 01:14
@gdi2290 Is there another way you'd prefer that people do this?

**Comment by gdi2290** [comment] 2017-01-08 03:49
won't be supported in ng4 
https://github.com/angular/angular/issues/13822

**Closed by gdi2290** 2017-01-08 03:49 UTC
