### ISSUE TITLE
domino uninstalled upgrading to ng 9

### ISSUE THREAD

**Issue by wafflesrg00d** [angular/universal#1499] opened 2020-02-11 01:16 UTC
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [ x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

Yes, the previous version in which this bug was not present was: 8.x

### Description

domino was uninstalled while upgrading to Angular 9 in a Universal project, and I'm no longer able to build, due to the following error: "ReferenceError: document is not defined". Re-adding domino via npm install did not resolve this error, either. Requiring and referencing domino in either server.ts or main.ts also fails.

## 🔬 Minimal Reproduction
Just adding `document.addEventListener(...)` in main.ts produces the described error.

## 🔥 Exception or Error
"ReferenceError: document is not defined"

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.1
Node: 10.16.2
OS: darwin x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@nguniversal/builders             9.0.0
@nguniversal/common               9.0.0
@nguniversal/express-engine       9.0.0
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by jsonpj3wt** [comment] 2020-02-19 05:34
I am also seeing a similar issue with upgrading to ng 9 and using universal - specifically with the prerender.  Previously was able to use domino in server.ts but that seems to not work anymore.

**Comment by alan-agius4** [comment] 2020-02-21 07:08
Can you please share a reproduction? Thanks.

**Comment by jsonpj3wt** [comment] 2020-02-21 23:31
@alan-agius4 I actually ran the steps from Angular documentation and even with `document.*` in main.ts, it did work (prerender and serve).

One thing I noticed when building was the following output:

```Compiling angular-formio : module as esm5
Compiling angular2-notifications : module as esm5
Compiling @angular/forms : es2015 as esm2015
Compiling ng-select2 : es2015 as esm2015
Compiling ngx-google-places-autocomplete : main as umd
Compiling ngx-markdown : es2015 as esm2015
Compiling ngx-pagination : module as esm5
Compiling ngx-xml2json : es2015 as esm2015```

I wonder since those imports do have `document.*` and dependent packages have them as well, could that be the issue?

Basically, if domino can be used, I think this solves this issue.  The problem is it will not import into main.ts because it fails on node modules (path, fs, etc).

**Comment by CaerusKaru** [comment] 2020-06-14 04:44
This is not an issue with Angular Universal, but maybe related to #1675. Either way, closing.

**Closed by CaerusKaru** 2020-06-14 04:44 UTC
Labels: state: Need repro
