### ISSUE TITLE
Meta Update on SSR

### ISSUE THREAD

**Issue by KrGyan** [angular/universal#772] opened 2017-08-08 05:56 UTC
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
```
- [Yes ] bug report

```

* **What modules are related to this Issue?**
```
Meta Module
```
Imported
import { Meta, Title } from '';

DI:
private seoServiceObj: Meta

Meta :
this.seoServiceObj.updateTag({name:'description',content : data.info.meta_desc});
this.seoServiceObj.updateTag({name:'publish-date',content : data.info.published_date1});
this.seoServiceObj.updateTag({name:'modified-date',content : data.info.published_date1});

**Comment by Toxicable** [comment] 2017-08-18 05:44
You havn't described what behaviour you have observed vs expected this services to do

**Comment by Toxicable** [comment] 2017-08-29 00:50
I just tried to reproduce this with the CLI here https://github.com/Toxicable/universal-starter/blob/cli/src/app/app.component.ts#L19
as you can see I am calling the meta service on my ngOnInit and then I run the prerender script which does correctly render the meta tag: `<meta name="author" value="Toxicable">`

If this is still a problem then please make a minimal repo that we can see the issue in

**Comment by gdi2290** [comment] 2017-09-04 05:03
the problem is probably due to the value not being a string

**Comment by Toxicable** [comment] 2017-10-10 19:05
Closing since we need more information to action this. If you still have a problem then open another issue and include a minimal reproduction

**Closed by Toxicable** 2017-10-10 19:05 UTC
