### ISSUE TITLE
Base path and reloading issue.

### ISSUE THREAD

**Issue by md-tanveruzzaman** [angular/universal#1432] opened 2020-01-04 10:43 UTC
The server runs on localhost:4000. when I type localhost:4000 in browser nothing happens. But if I put localhost:4000/index.html, It starting to load fine and return to base localhost:4000. Then every angular route works fine. But if I try to refresh any page it doesn't load anything.
This is probably because I haven't been able to configure my server.ts file properly.

package.json

```
    "@angular/animations": "^8.2.14",
    "@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/forms": "^8.2.14",
    "@angular/http": "^7.2.15",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/platform-server": "^8.2.14",
    "@angular/router": "^8.2.14",
    "@ng-bootstrap/ng-bootstrap": "^5.1.4",
    "@nguniversal/express-engine": "^9.0.0-next.14",
```
app.routing.module.ts
```
    {
        path: 'client',
        loadChildren: () => import('./client/client.module').then(m => m.ClientModule)
    },
    {
        path: '',
        loadChildren: () => import('./home/home.module').then(m => m.HomeModule),
        resolve: {
            settings: HomeResoveService,
            cartCheckL: CartTokenService
        },
        // canActivate: [AppGuardService]
    },
    {
        path: 'not-found',
        loadChildren: () => import('./not-found/not-found.module').then(m => m.NotFoundModule),
        data : { title:'Not Found'} 
    },
    { 
        path: '**',
        redirectTo: 'not-found'
    }
```

server.ts file :
```
import 'zone.js/dist/zone-node';
import { join } from 'path';
import { existsSync } from 'fs';
// ssr DOM
const domino = require('domino');
const fs = require('fs');
// const template = fs.readFileSync(path.join('dist/browser', 'index.html')).toString();
const distFolder = join(process.cwd(), 'dist/browser');
const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index';
const win = domino.createWindow(indexHtml);
global['window'] = win;
Object.defineProperty(win.document.body.style, 'transform', {
  value: () => {
    return {
      enumerable: true,
      configurable: true,
    };
  },
});
global['document'] = win.document;
global['CSS'] = null;
global['Prism'] = null;
import { ngExpressEngine } from '@nguniversal/express-engine';
import * as express from 'express';

import { AppServerModule } from './src/main.server';
import { APP_BASE_HREF } from '@angular/common';
export function app() {
  const server = express();
  server.engine('html', ngExpressEngine({
    bootstrap: AppServerModule,
  }));

  server.set('view engine', 'html');
  server.set('views', distFolder);

  server.get('*.*', express.static(distFolder, {
    maxAge: '1y'
  }));

  server.get('*', (req, res) => {
    res.render(indexHtml, { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] });
  });

  return server;
}

function run() {
  const port = process.env.PORT || 4000;

  // Start up the Node server
  const server = app();
  server.listen(port, () => {
    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

// Webpack will replace 'require' with '__webpack_require__'
// '__non_webpack_require__' is a proxy to Node 'require'
// The below code is to ensure that the server is run only when not requiring the bundle.
declare const __non_webpack_require__: NodeRequire;
const mainModule = __non_webpack_require__.main;
if (mainModule && mainModule.filename === __filename) {
  run();
}
export * from './src/main.server';
````
dist folder has browser and project-name-server folder. Index.html and other static files are in dist/browser folder.

**Comment by alan-agius4** [comment] 2020-01-04 16:08
Ikon fly provide the following;

- output of `ng version`
- share the routes config.
- all the commands that you are executing 

Thanks.

**Comment by md-tanveruzzaman** [comment] 2020-01-06 05:09
@alan-agius4  can you please check. I have added required config.

**Comment by alan-agius4** [comment] 2020-01-07 11:49
I think the problem is in the following lines;
```ts
const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index';
const win = domino.createWindow(indexHtml);
```

`domino.createWindow` requires html content and not the file path of the html document.

Try updating it to the below;
```ts
const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index';
const indexContent = readFileSync(path.join(distFolder, indexHtml), 'utf8');
const win = domino.createWindow(indexContent);
```

Also, `@nguniversal/express-engine` version 9, is meant to be used with Angular and Angular CLI version 9. More info about updating can be found here: https://update.angular.io/#8.0:9.0

**Comment by md-tanveruzzaman** [comment] 2020-01-09 06:29
Thanks for the answer. It did not work. I will try to update the angular core to 9.

**Comment by alan-agius4** [comment] 2020-04-08 15:36
And updates if the above is addressed in v9?

**Comment by CaerusKaru** [comment] 2020-06-14 04:51
Closing since no update for three months. If this is still an issue, we can reopen.

**Closed by CaerusKaru** 2020-06-14 04:51 UTC
Labels: state: Need more info
