### ISSUE TITLE
ngExpressEngine ERROR in server.ts:18:25 - error TS2345:

### ISSUE THREAD

**Issue by ezequieltejada** [angular/universal#1556] opened 2020-03-16 18:49 UTC
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [ ✅ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Description

Cannot serve a local version of a clean app due to compilation errors.

## 🔬 Minimal Reproduction

ng new project --packageManager=yarn
ng add @nguniversal/express-engine
npm run dev:ssr

## 🔥 Exception or Error
<pre><code>
ERROR in server.ts:18:25 - error TS2345: Argument of type '(filePath: string, options: Readonly<RenderOptions>, callback: (err?: Error | null | undefined, html?: string | undefined) => void) => void' is not assignable to parameter of type '(path: string, options: 
object, callback: (e: any, rendered: string) => void) => void'.
      Types of parameters 'callback' and 'callback' are incompatible.
        Types of parameters 'rendered' and 'html' are incompatible.
          Type 'string | undefined' is not assignable to type 'string'.
            Type 'undefined' is not assignable to type 'string'.
    
    18   server.engine('html', ngExpressEngine({
                               ~~~~~~~~~~~~~~~~~
    19     bootstrap: AppServerModule,
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    20   }));
       ~~~~ 

</code></pre>


## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.6
Node: 12.16.1
OS: linux x64

Angular: 9.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.6
@angular-devkit/build-angular     0.900.6
@angular-devkit/build-optimizer   0.900.6
@angular-devkit/build-webpack     0.900.6
@angular-devkit/core              9.0.6
@angular-devkit/schematics        9.0.6
@ngtools/webpack                  9.0.6
@nguniversal/builders             9.0.2
@nguniversal/common               9.0.2
@nguniversal/express-engine       9.0.2
@schematics/angular               9.0.6
@schematics/update                0.900.6
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by ezequieltejada** [comment] 2020-03-16 19:03
I've configured it to use yarn, but using npm it works fine.

**Comment by xmlking** [comment] 2020-03-23 05:21
same issue for me.

**Comment by CaerusKaru** [comment] 2020-03-23 05:31
Minimal reproduction does not create any errors for me. Please make sure that you can reproduce them yourself first.

**Comment by neo** [comment] 2020-03-26 00:03
seeing this too, but if I do a fresh scaffold, it worked...

**Comment by neo** [comment] 2020-03-26 00:08
after an entire afternoon of investigating, I found that if I turn off the strict mode of TypeScript, it worked again!
so it might have something to do with one of the rules the strict mode enable, will investigate more.
but from a library perspective, ideally we don't need to turn off strict mode just for this...

**Comment by neo** [comment] 2020-03-26 14:03
how I fixed it for now:
![image](https://user-images.githubusercontent.com/9028430/77655655-17c05d80-6f49-11ea-9369-99d67300743f.png)

**Comment by neo** [comment] 2020-03-26 14:23
another way to fix for below ts 3.8:
add ` as Parameters<express.Application['engine']>[1]` instead after the `ngExpressEngine` call.

also @CaerusKaru, reproduction steps I found:

```sh
npx @angular/cli new test --routing --skipTests --style=scss
cd test
npx ng add @nguniversal/express-engine
npm run build:ssr
```
Let me know if you'd like a PR to fix it in some way. ❤️

**Comment by xmlking** [comment] 2020-03-27 00:05
temp fix
```
  server.engine(
    'html',
    ngExpressEngine({
      bootstrap: AppServerModule,
    }) as any // FIXME: add `as any`
  );
```

**Comment by alexnoise79** [comment] 2020-05-23 15:57
commenting
`// "strictNullChecks": true,`
in tsconfig.json worked for me

**Comment by CaerusKaru** [comment] 2020-06-14 04:42
@neo Once again I have no issue running the commands you specified. I'm going to close this as working as intended. If someone wants to put together a PR with a fix or to document the issue further, please feel free.

**Closed by CaerusKaru** 2020-06-14 04:42 UTC
Labels: state: Need more info, state: Need repro, type: bug/fix
