### ISSUE TITLE
Setting value to CSS variable using a style-directive does not work

### ISSUE THREAD

**Issue by tommueller** [angular/universal#1853] opened 2020-09-28 08:58 UTC
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine

(not entirely sure about this though)
### Is this a regression?
Don't know.

### Description
I use a couple of style-directives in our App. These work fine when used with Angular Universal. Unless I use them in combination with CSS variables. CSS properties with a `var(something)` value, will not be added to the output of Angular Universal.

## 🔬 Minimal Reproduction
This is my style directive:
```ts
import { Directive, ElementRef } from '@angular/core';

@Directive({
  selector: '[styleDirective]'
})
export class StyleDirective {
  constructor(public elementRef: ElementRef) {

    const newStyles = {
      'color': 'var(--light-text)' // is not added to the output
      // 'color': '#FFF' -> this works
    };

    this.setStyles(newStyles);
  }

  private setStyles(styles: any): void {
    Object.keys(styles).forEach(element => {
      this.elementRef.nativeElement.style.setProperty(`${element}`, styles[element]);
    });
  }
```

## 🔥 Exception or Error
Style is not added.

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.0.6
Node: 10.19.0
OS: linux x64

Angular: 10.0.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.6
@angular-devkit/build-angular     0.1000.6
@angular-devkit/build-optimizer   0.1000.6
@angular-devkit/build-webpack     0.1000.6
@angular-devkit/core              10.0.6
@angular-devkit/schematics        10.0.6
@angular/cdk                      10.1.3
@angular/cli                      10.0.6
@angular/flex-layout              10.0.0-beta.32
@angular/material                 10.1.3
@ngtools/webpack                  10.0.6
@nguniversal/builders             10.0.2
@nguniversal/common               10.0.2
@nguniversal/express-engine       10.0.2
@schematics/angular               10.0.6
@schematics/update                0.1000.6
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Comment by alan-agius4** [comment] 2021-06-10 05:43
Duplicate of https://github.com/angular/angular/issues/42170

**Closed by alan-agius4** 2021-06-10 05:43 UTC
