### ISSUE TITLE
How to deploy Angular Universal on iis?

### ISSUE THREAD

**Issue by yangjunfocus** [angular/universal#1579] opened 2020-03-27 12:17 UTC
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description
1.execute npm run build:ssr
 A clear and concise description of the problem...

## 🔥 Exception or Error
<pre><code>

![image](https://user-images.githubusercontent.com/23710467/77755181-adeaa580-7067-11ea-82d9-e1e9c0a85caf.png)

</code></pre>

## 🌍 Your Environment
<pre><code>

"scripts": {
    "ng": "ng",
    "start": "ng serve --port 8001",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "ssr": "ng run example:serve-ssr",
    "dev:ssr": "ng run example:serve-ssr",
    "serve:ssr": "node dist/example/server/main.js",
    "build:ssr": "ng build --prod && ng run example:server:production",
    "prerender": "ng run example:prerender",
    "postinstall": "ngcc"
  },
Angular CLI: 9.1.0
Node: 10.15.3
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.1.0
@nguniversal/builders             9.0.2
@nguniversal/common               9.0.2
@nguniversal/express-engine       9.0.2
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code></pre>
`<configuration>

         <system.webServer>
           <handlers>
       <add name="iisnode" path="dist/overseas/server/main.js" verb="*" modules="iisnode"/>
     </handlers>
       <rewrite>
       <rules>
            <rule name="LogFile" patternSyntax="ECMAScript" stopProcessing="true">
                 <match url="iisnode"/>
            </rule>
           
            <rule name="StaticContent">
                 <action type="Rewrite" url="{{REQUEST_URI}}"/>
            </rule>
            <rule name="DynamicContent">
                 <conditions>
                      <add input="{{REQUEST_FILENAME}}" matchType="IsFile" negate="True"/>
                 </conditions>
                 <action type="Rewrite" url="overseas/server/main.js"/>
            </rule>
       </rules>
     </rewrite>
     <iisnode devErrorsEnabled="false"
      debuggingEnabled="false"
       loggingEnabled="false" 
       nodeProcessCommandLine="C:\Program Files\nodejs\node.exe" />
  
</system.webServer>
</configuration>`

**Comment by CaerusKaru** [comment] 2020-03-27 14:15
Duplicate of #1280

**Closed by CaerusKaru** 2020-03-27 14:16 UTC
