### ISSUE TITLE
Angular 2 rc5 support

### ISSUE THREAD

**Issue by dotansimha** [angular/universal#519] opened 2016-08-11 10:40 UTC
* **I'm submitting a ...**
- [x] feature request

* **What modules are related to this Issue?**
- [x] universal

* **Do you want to request a *feature* or report a *bug*?**
Support Angular rc-5. At the moment, universal throws errors about missing files in `@angular/core`.

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.5
- Browser: [all  ]
- Language: [all |]
- OS:  [all  ]
- Platform: [NodeJs]

**Comment by maciejsobala** [comment] 2016-08-11 11:01
Duplicate of
#511

**Comment by MarkPieszak** [comment] 2016-08-11 14:07
Thanks @dotansimha, closing as duplicate follow #511 to see the progress, as Maciej said.

**Closed by MarkPieszak** 2016-08-11 14:07 UTC
