### ISSUE TITLE
Environment variables are not replaced in server code

### ISSUE THREAD

**Issue by luckynick** [angular/universal#1175] opened 2019-06-06 13:25 UTC
# Bug Report

#### What is the expected behavior?
When building and running Angular Universall app with
`ng build --configuration=production && ng run webshopclient:server --configuration=production && webpack --config webpack.server.config.js --progress --colors && npm run serve:ssr`
server code should utilize values from environment.production.ts instead of default environment.ts.

#### What is the current behavior?
Server code utilizes environment variables as if they weren't replaced according to supplied configuration.

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [x] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:
angular.json (excerpt)

```
"architect":{  
   "build":{  
      "builder":"@angular-devkit/build-angular:browser",
      "options":{  
         "outputHashing":"media",
         "outputPath":"dist/browser",
         "deployUrl":"/",
         "index":"src/index.html",
         "main":"src/main.ts",
         "tsConfig":"src/tsconfig.app.json",
         "polyfills":"src/polyfills.ts",
         "assets":[  
            "src/favicon.ico"
         ],
         "styles":[  
            "src/styles.scss"
         ],
         "scripts":[  
            "node_modules/jquery/dist/jquery.min.js",
            "node_modules/bootstrap/dist/js/bootstrap.min.js"
         ]
      },
      "configurations":{  
         "production":{  
            "optimization":true,
            "outputHashing":"all",
            "sourceMap":false,
            "extractCss":true,
            "namedChunks":false,
            "aot":true,
            "extractLicenses":true,
            "vendorChunk":false,
            "buildOptimizer":true,
            "fileReplacements":[  
               {  
                  "replace":"src/environments/environment.ts",
                  "with":"src/environments/environment.production.ts"
               }
            ]
         },
         "css2":{  
            "fileReplacements":[  
               {  
                  "replace":"src/environments/environment.ts",
                  "with":"src/environments/environment.css2.ts"
               }
            ]
         }
      }
   },
   "server":{  
      "builder":"@angular-devkit/build-angular:server",
      "options":{  
         "outputHashing":"media",
         "outputPath":"dist/server",
         "main":"src/main.server.ts",
         "deployUrl":"/",
         "tsConfig":"src/tsconfig.server.json"
      },
      "configurations":{  
         "production":{  
            "fileReplacements":[  
               {  
                  "replace":"src/environments/environment.ts",
                  "with":"src/environments/environment.production.ts"
               }
            ]
         },
         "css2":{  
            "fileReplacements":[  
               {  
                  "replace":"src/environments/environment.ts",
                  "with":"src/environments/environment.css2.ts"
               }
            ]
         }
      }
   }
}
```
Above you can see that both "build" and "server" targets have configuration "production".

I've tried different variants of build command. Let's say, that variant in 'What is the expected behavior' section should for sure work. Still, it doesn't work as it should.

`ng build --configuration=production && ng run webshopclient:server --configuration=production && webpack --config webpack.server.config.js --progress --colors && npm run serve:ssr`

To reproduce, print out 'environment.production' in server.ts

```
// Start up the Node server
app.listen(PORT, () => {
  console.log(`Node Express server listening on http://localhost:${PORT}`);
  console.log(`environment.production: ${environment.production}`);
});
```
environment.production will be printed as false.

#### What is the use-case or motivation for changing an existing behavior?
Environment variables are an important tool for customization of building process. They should work in the server environment as it is a part of the application. It is important to have env vars work in server for example when we need to define different API link depending on build configuration.

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common:
  - @angular/common: 7.2.15
  - express-engine: 7.1.1
  - hapi-engine:
  - module-map-ngfactory-loader: 0.0.0

```
Angular CLI: 7.3.9
Node: 8.11.2
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-optimizer   0.12.4
@angular-devkit/build-webpack     0.12.4
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/material                 7.3.7
@ngtools/webpack                  7.2.4
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.2
typescript                        3.2.4
webpack                           4.28.4

Windows 10
```

#### Is there anything else we should know?

Related issue: #991 
I've decided to create a new issue since tips from above issue didn't help in my case.

**Comment by vikerman** [comment] 2019-07-30 04:38
Thanks for the issue. WIll look into this in the 9.0 timeframe.

**Comment by vikerman** [comment] 2019-09-17 18:54
Hi - Can you try running 
`ng run webshopclient:server:production` instead of `ng run webshopclient:server --configuration=production`

**Comment by luckynick** [comment] 2019-09-18 07:26
Hello
I had most certainly done it and the result was the same. Do I have to try with newer version of Universal?

**Comment by vikerman** [comment] 2019-09-25 19:07
Yes - Can you please try it with latest version - though this has been working as intended from the beginning.

**Comment by luckynick** [comment] 2020-03-27 11:22
Checked in Angular version 9 - environment file was replaced correctly.

**Comment by alan-agius4** [comment] 2022-09-15 12:23
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.

**Closed by alan-agius4** 2022-09-15 12:23 UTC
Labels: need: repro steps
