### ISSUE TITLE
v12.1 unable to build - directory not found error

### ISSUE THREAD

**Issue by tsheils** [angular/universal#2186] opened 2021-06-28 13:16 UTC
# 🐞 Bug report

#### What modules are related to this issue?

Unsure
- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
yes ~12.0.1
### Description

 A clear and concise description of the problem...
@nguniversal/express-engine crashes during setup phase with
`An unhandled exception occurred: ENOENT: no such file or directory, stat '/Users/*me*/Desktop/workspace/*project*/dist/*project*/browser'
See "/private/var/folders/k7/p_nrrn1s6l32h1w35lsx5vbc8ys_q3/T/ng-M2C7ZL/angular-errors.log" for further details.
`

Reverting to 12.0.1 for all Angular dependencies fixes the problem.

## 🔬 Minimal Reproduction
Created a brand new angular project - v12.1.0 (built ok)
Added Material (built ok)
Added @nguniversal/express-engine crashes during setup phase

## 🔥 Exception or Error

<pre><code>
An unhandled exception occurred: ENOENT: no such file or directory, stat '/Users/*me*/Desktop/workspace/*project*/dist/*project*/browser'
See "/private/var/folders/k7/p_nrrn1s6l32h1w35lsx5vbc8ys_q3/T/ng-M2C7ZL/angular-errors.log" for further details.
</code></pre>

## 🌍 Your Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.5
Node: 16.2.0
Package Manager: npm 7.13.0
OS: darwin x64

Angular: 12.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.0.5
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.5
@angular/cdk                    12.0.6
@angular/flex-layout            12.0.0-beta.34
@angular/material               12.0.6
@nguniversal/builders           12.0.2
@nguniversal/express-engine     12.0.2
@schematics/angular             12.0.5
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Comment by alan-agius4** [comment] 2021-06-28 13:19
Duplicate of https://github.com/angular/angular-cli/issues/21202

**Closed by alan-agius4** 2021-06-28 13:19 UTC
