### ISSUE TITLE
ReferenceError: location is not defined on Renderer

### ISSUE THREAD

**Issue by mickael-kerjean** [angular/universal#382] opened 2016-05-03 15:30 UTC
Hello,

While trying to find a way to make use of an external library in Angular (Swiperjs), I found that making use of invokeElementMethod was breaking universal:
``` javascript
let dom_attach = this._render.invokeElementMethod(this._el.nativeElement, 'querySelector', ['.swiper-container']);
```
Here is the full stack trace:
```
EXCEPTION: ReferenceError: location is not defined
STACKTRACE:
ReferenceError: location is not defined
    at NodeDomRenderer.invokeElementMethod (/Users/mikeulkeul/Downloads/ng2-universal/node_modules/angular2-universal/dist/node/platform/dom/node_dom_renderer.js:248:64)
    at SliderComponent.ngAfterViewInit (/Users/mikeulkeul/Downloads/ng2-universal/dist/client/app/shared/slider.component.js:48:39)
    at AbstractChangeDetector.ChangeDetector_DetailsComponent_8.afterViewLifecycleCallbacksInternal (viewFactory_DetailsComponent:1287:82)
    at AbstractChangeDetector.afterViewLifecycleCallbacks (/Users/mikeulkeul/Downloads/ng2-universal/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:168:14)
    at AbstractChangeDetector.runDetectChanges (/Users/mikeulkeul/Downloads/ng2-universal/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:88:18)
    at AbstractChangeDetector._detectChangesContentChildren (/Users/mikeulkeul/Downloads/ng2-universal/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:175:18)
    at AbstractChangeDetector.runDetectChanges (/Users/mikeulkeul/Downloads/ng2-universal/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:83:14)
    at AbstractChangeDetector._detectChangesContentChildren (/Users/mikeulkeul/Downloads/ng2-universal/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:175:18)
    at AbstractChangeDetector.runDetectChanges (/Users/mikeulkeul/Downloads/ng2-universal/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:83:14)
    at AbstractChangeDetector._detectChangesContentChildren (/Users/mikeulkeul/Downloads/ng2-universal/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:175:18)
```

As I couldn't find any test that would showcase any working code snippet of invokeElementMethod, I dug into the code and arrived here: https://github.com/angular/universal/blob/master/modules/universal/src/node/platform/dom/node_dom_renderer.ts#L245

The location variable didn't seem to be declare anywhere and is breaking universal. Shouldn't we have something like this instead?
```
return super.invokeElementMethod(renderElement, methodName, args);
```

I tried this but then I came up with the following error:
```
EXCEPTION: Error: not implemented
STACKTRACE:
Error: not implemented
    at Parse5DomAdapter.invoke (/Users/mikeulkeul/Downloads/ng2-universal/node_modules/angular2/src/platform/server/parse5_adapter.js:568:81)
    at NodeDomRenderer.DomRenderer.invokeElementMethod (/Users/mikeulkeul/Downloads/ng2-universal/node_modules/angular2/src/platform/dom/dom_renderer.js:221:27)
    at NodeDomRenderer.invokeElementMethod (/Users/mikeulkeul/Downloads/ng2-universal/node_modules/angular2-universal/dist/node/platform/dom/node_dom_renderer.js:248:53)
    at SliderComponent.ngAfterViewInit (/Users/mikeulkeul/Downloads/ng2-universal/dist/client/app/shared/slider.component.js:48:39)
    at AbstractChangeDetector.ChangeDetector_DetailsComponent_8.afterViewLifecycleCallbacksInternal (viewFactory_DetailsComponent:1287:82)
    at AbstractChangeDetector.afterViewLifecycleCallbacks (/Users/mikeulkeul/Downloads/ng2-universal/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:168:14)
    at AbstractChangeDetector.runDetectChanges (/Users/mikeulkeul/Downloads/ng2-universal/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:88:18)
    at AbstractChangeDetector._detectChangesContentChildren (/Users/mikeulkeul/Downloads/ng2-universal/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:175:18)
    at AbstractChangeDetector.runDetectChanges (/Users/mikeulkeul/Downloads/ng2-universal/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:83:14)
    at AbstractChangeDetector._detectChangesContentChildren (/Users/mikeulkeul/Downloads/ng2-universal/node_modules/angular2/src/core/change_detection/abstract_change_detector.js:175:18)
```

It seems the invokeElementMethod hasn't been implemented yet?

If you need help to investigate it and fix it, I can try to help.

**Comment by jeffwhelpley** [comment] 2016-05-06 19:01
I am talking to Patrick about this, but two things:

First, we should at the very least implement `invokeElementMethod` if nothing else just to throw an error "don't use this one the server side, instead use blah blah blah".

But more to the point is whether the server side should have an implementation of querySelector. My initial impression is no because there is no existing virtual DOM state to run the querySelector logic on. Think about this: on the server we only render once and before you start the rendering logic, there is nothing in the virtual DOM tree (and thus nothing to query). 

Now, I don't know exactly what you are trying to do, but since you are referring to "swipe" I am going to guess that your library is reacting to a user event which means it should only exist in the client browser. If you agree with me on that, then the solution is just a matter of using DI swapping so that `let dom_attach = this._render.invokeElementMethod(this._el.nativeElement, 'querySelector', ['.swiper-container']);` only runs on in the client browser. 

Let me know what you think and if you have any questions.

**Comment by mickael-kerjean** [comment] 2016-05-13 10:41
I initially open this issue as throwing an error with such a weird message wasn't really expected.

> Now, I don't know exactly what you are trying to do

I was trying trying to use a well known slider library called swiperjs ([here a demo](http://idangero.us/swiper/demos/#.VzReIhVcRBc)) that like many other you instantiate doing something like this:
``` javascript
new Plugin(element.querySelector('.element'), {
    option: 'foo'
});
```

The approach in Angular1 if you don't want to reinvent the wheel, is to wrap it up in a directive / component for Angular2.

The same issue would apply for any library that wasn't design specifically with Angular in mind (like all the UI plugin written in jquery and vanilla js that rely on DOM manipulation to do their thing)

> then the solution is just a matter of using DI swapping

Here DI Swapping would only be helpfull to shortcut the problematic piece of code, without achieving the desired features.

> it should only exist in the client browser.

Well, it would be great to be able to use some jquery kinda libraries in the server rendered version made by universal (like the swiperjs slider).

A simple solution I can think of would be to have a public method in Universal that will simply push what it has in argument within a script tag and send it along the page.

In term of code, it could potentially be used that way:

``` typescript
import {Component, Input, ElementRef, Renderer} from 'angular2/core';
import {Platform} from '../abstract/platform';
declare var Swiper:any;

@Component({
    selector:'.slider',
    template:`
<div class="swiper-container">
    <div class="swiper-wrapper">
        <ng-content></ng-content>
    </div>
    <div class="swiper-button-next swiper-button-white"></div>
    <div class="swiper-button-prev swiper-button-white"></div>
</div>
`,
})
export class SliderComponent{
    public swiper: any;

    constructor(private _el: ElementRef, private _render: Renderer, private _platform: Platform){}

    ngAfterViewInit(){
        if(this._platform.is() === 'browser'){ // DI Swapping
            let dom_attach = this._el.nativeElement.querySelector(".swiper-container");
            this.swiper = new Swiper(dom_attach);
        }else if(this._platform.is() === 'server'){
            this.swiper = universal_push_script('new Swiper(".swiper-container")');
        }
    }

    ngOnDestroy(){
        this.swiper && this.swiper.destroy();
    }
}
```

yes it feels very hacky but still it should work

**Comment by jeffwhelpley** [comment] 2016-05-13 11:57
@mickael-kerjean thanks for providing more details. So, if I understand you correctly, the main thing you are trying to do on the server side is to have the initial state of the slider rendered and displayed in the server view. I can totally understand why you would want to do this, but the issue is that jQuery is tightly coupled to the DOM. If you look within the Swiper plugin you will see that it has a number of calls directly to the DOM that just won't work on the server side unless you did some serious monkey patching. Here are the options that you have for accomplishing your goal:

1. If you want to use a jQuery plugin, you need to have a server side implementation for the DOM api calls from that jQuery plugin. You could create your own implementation or use something like jsDom, but I would strongly recommend against this option. The reason is that any solution along these lines is going to be extremely heavyweight and slow. It just isn't worth it IMO.
2. If you absolutely need to have the slider rendered on the server side, you can create your own "vanilla" implementation. If you do this, it would be super easy to split out server side functionality and avoid touching the DOM directly. Also, although this may seem like a pain, it will be less work than option 1.
3. Finally, my recommendation is to not have a true server implementation of the slider and instead create a server-only version of the slider which is really just a "shell". This is a common technique used by Facebook and many sites to have a shape that sort of looks like the thing you are rendering and of the right size in place on the server rendered page and then it is replaced by the actual slider when the client side kicks in.

Let me know if this makes sense or if you have any questions.

**Comment by MarkPieszak** [comment] 2016-05-13 17:18
@jeffwhelpley @gdi2290  Just throwing a wild idea out there... But is there some kind of crazy way we can almost *ignore* DOM manipulation on the server-side somehow? 

Just render whatever we can, and then let the client-side version handle all of those things?

I'm picturing some sort of (server-side) jQuery override that basically returns a blank jQuery selector `$()` does nothing, but keeps jQuery from error-ing out? In theory I feel like it could work somehow, but there could be so many things to monkey-patch... What do you guys think?

**Comment by jeffwhelpley** [comment] 2016-05-13 22:47
Yeah Mark has a decent option number 4 that would essentially be a variation of option number 3. Basically instead of using DI swapping to provide a server implementation, you could do some mocking of the jQuery objects so they are essentially no ops. That is not something we would put in the Universal repo, though because how you want to handle this is highly dependent on your specific use case.

**Comment by mickael-kerjean** [comment] 2016-05-16 06:18
Thank you for your feedback.

> the issue is that jQuery is tightly coupled to the DOM

I understand why it can be tricky to integrate a jquery library from a server perspective. However If universal could provide a hook to inject code directly in the page, there will be no need to generate a shell or simulating the DOM.

In our example, we simply need a way to inject this code somewhere in the view:
``` 
"<script>window.onload = function(){ new Swiper('.swiper-container')}</script>"
```
Considering that universal in its core is generating a string that is sent over the wire, it will come to have a method to append a string into it.
Any way this can be done?

**Comment by jeffwhelpley** [comment] 2016-05-16 09:32
@mickael-kerjean you can add any arbitrary JavaScript to be inlined with the server rendered view using Preboot, but I don't think that will actually solve your problem in this case. Even if you use Preboot to do exactly as you are suggesting, unless I am missing something, I don't think anything would happen since jQuery isn't loaded on the page yet. You would need to inline jQuery and the Swiper jQuery plugin as well...which will add a lot of page weight.

**Comment by mickael-kerjean** [comment] 2016-05-16 10:50
Thank you for the tip, I'll look preboot.

> You would need to inline jQuery and the Swiper jQuery plugin as well

Sure, and what's wrong with that?
```
<head>
    <base href="/">
    <link rel="stylesheet" type="text/css" href="./vendor/swiper.min.css">
    <script async src="vendor/swiper.min.js"></script>
</head>
<body>
    <app></app>

    <script src="vendor/es6-shim.min.js"></script>
    ....... ANGULAR DEPEDENCIES .....

    <script>
        System.config({
          packages: {
              client: {
                  format: 'cjs',
                  defaultExtension: 'js'
              },
          }
        });
        System.import('client/app.js')
            .then(null, console.error.bind(console));
    </script>
    <script>window.onload = function(){ new Swiper('.swiper-container')}</script>
</body>
```

> which will add a lot of page weight
A few kb more, nothing too bad. If you're lucky, the library could even be already on the client's browser using a CDN, and it will come without any extra cost. 
What's wrong with that? 
As I can se it, it will even become super handy if the user has a old IE that will not have support for Angular2.

**Comment by jeffwhelpley** [comment] 2016-05-16 14:43
Ah, so, I think we are talking about two different things. What you are describing in your last message is simply a way of getting the Swiper control working with the client rendered version of your code. That would be no different whether or not you use Angular Universal. The thing I was thinking about in this thread is how to get something displayed in the server rendered view. The difference is that the server view is visible to the user ~1s after initial request. Then (on slower network devices), the client view would be visible ~4-8seconds after initial request. So, Angular Universal let's you display something to the user almost immediately (i.e. after 1 second) while the client downloads in the background and then ultimately displays) another 4+ seconds later). There is absolutely no issue doing what you suggest except that it would be part of the client view (i.e. the one displayed after 4+ seconds) and not the server view (i.e. the one visible right away after 1 second to the user).

Does that make sense?

**Comment by dottodot** [comment] 2016-07-17 10:22
@jeffwhelpley do you know of any examples of creating a "shell" on the server and then replacing when the client is loaded. I have a similar issue where I want to use masonry of the layout but struggling to get my head round it. Or even how to do things on the client only with 3rd party scripts so you don't get issues like `masonry is not defined`

**Comment by jeffwhelpley** [comment] 2016-10-03 21:36
So, there is a way to support this in the future. Closing this in favor of #512

**Closed by jeffwhelpley** 2016-10-03 21:36 UTC
Labels: P0: urgent

**Comment by gdi2290** [comment] 2016-10-05 18:39
this problem is more of the renderer invoking a method on our js dom where the method doesn't exist. The solution is to provide the renderer with a map of methods to use the DomAdaptor on the element so long as this should work on the browser
