### ISSUE TITLE
Angular Universal serve:ssr Server Side Render Builder

### ISSUE THREAD

**Issue by almgwary** [angular/universal#1276] opened 2019-10-13 07:05 UTC
# Feature Request

#### What is the desired behavior?

Server side render not working on development mode yet with hot reload the only serve builder is
`"builder": "@angular-devkit/build-angular:dev-server"`
this builder not serving with server side render for development build

#### What is the use-case or motivation for the desired behavior?

Server side render should work on development mode 

#### Is there anything else we should know?

Stack-overflow issue: https://stackoverflow.com/questions/58361300/angular-universal-servessr-server-side-render-builder

**Comment by alan-agius4** [comment] 2019-10-13 07:27
Duplicate of https://github.com/angular/universal/issues/1202

**Closed by alan-agius4** 2019-10-13 07:27 UTC
