### ISSUE TITLE
404 Exception that crash server

### ISSUE THREAD

**Issue by thebarada** [angular/universal#618] opened 2016-11-10 13:20 UTC
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [x] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [ ] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**
I believe it's bug

* **What is the current behavior?**
Using http service, 404 exception break down server

```
Listening on: localhost:5000
EXCEPTION: Response with status: 404 null for URL: 

.../node_modules/rxjs/Subscriber.js:227
            throw err;
            ^
Response with status: 404 null for URL: 
[nodemon] app crashed - waiting for file changes before starting...

```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
Just call http get request on nonexistent URL

* **What is the expected behavior?**
Server should not breaking down

**Comment by MarkPieszak** [comment] 2016-11-10 14:07
Have you changed the Starter's main functionality in any way, webpack or main files by any chance?

Also do you have the port already in use? Notice this issue here:
https://github.com/angular/universal-starter/issues/94

Just tried, and everything works fine here on my end

       this.http.get('/doesnotexist.aspx').subscribe(result => {}); 
       //

**Comment by thebarada** [comment] 2016-11-10 14:18
@MarkPieszak I tried it on [angular/universal-starter](https://github.com/angular/universal-starter) and getting crash
could you check please
just change 22 line on src/app/home/home.component.ts from
```
this.model.get('/data.json').subscribe(data => {
```
to
```
this.model.get('/unknown/url').subscribe(data => {
```
and, likely, you'll get error such [this](http://take.ms/KXS2m)

**Comment by MarkPieszak** [comment] 2016-11-10 14:59
So this is because the `server` (express) in our case is throwing that 404 error, which ends up breaking everything. If you comment out these lines:

```
app.get('*', function(req, res) {
  res.setHeader('Content-Type', 'application/json');
  var pojo = { status: 404, message: 'No Content' };
  var json = JSON.stringify(pojo, null, 2);
  res.status(404).send(json);
});
```

https://github.com/angular/universal-starter/blob/master/src/server.ts#L80-L85

@gdi2290 I suppose we don't want/need the server to be handling 404's like this, since it does end up breaking down express-server. At least on the .NET side I don't handle 404's I let the client do that. What do you think?

**Comment by Reuvenc** [comment] 2016-11-23 17:10
I'm having the same issue here, while trying to call external api's. Currently, when an endpoint is not found, the server fails for 300+ status errors.

Regarding the same topic, the server crashes for each synchronous error. Is there any method to wrap universal's engine in order to prevent such failures?

Tried to run the forked zone with `zone.runGuarded` instead of `zonr.run` in order to catch errors, but yet, thrown error still crashes the server.

**Comment by crebuh** [comment] 2016-12-06 13:04
I've the same issue within my application. As a workaround you could use the toPromise-Method, then everything is working fine e.g:

Instead of

``
return this.http.get(url, this.globalService.getRequestOptions()).map(response => response.json().data);
``

use

``
   return this.http.get(url, this.globalService.getRequestOptions())
        .toPromise().then(response => response.json().data)
        .catch((error) => {
            console.log('error fetching data', error)
            return (id) ? {} : [];
        });
``

**Comment by marian2js** [comment] 2016-12-26 17:56
I believe the issue is happening because you are not handling the error when you subscribe to the observable.

You can use:
```javascript
this.http.get(url).subscribe(
  data => this.onDataReceived(data),
  error => this.onError(error)
);
```

If you do not define the error parameter, an exception is thrown by default.

**Comment by gdi2290** [comment] 2017-01-08 03:37
might be fixed in ng4 
https://github.com/angular/angular/issues/13822

**Closed by gdi2290** 2017-01-08 03:37 UTC
