### ISSUE TITLE
Angular universal async pipe not found in dynamic component

### ISSUE THREAD

**Issue by diegovegasilva** [angular/universal#1878] opened 2020-10-28 16:43 UTC
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [x] common
- [ ] express-engine
- [ ] hapi-engine

### Is this a regression?
No

### Description

I have an Angular 10 app which uses Angular Universal for SSR. This app also makes http requests to get some html and dynamically render it. When I run the app with ng serve everything works fine, the dynamic content is fetched with a http request and is rendered properly into the page. I've made a component that fetches content with a http request, creates a new component, assigns the fetched content as template, creates a new module and add this component in declarations to allow this to be used. 

This component works fine when the app runs with ng serve, the dynamic content is rendered. The problem comes when I run the app with ssr, using ng run app-name:serve-ssr, all content comes rendered from the server, except this dynamic content component. This content is actually fetched in server as I can see the template stored in a transferState Key in a script html tag,  but I got The pipe 'async' could not be found! error in server console.

After this error, it looks like the browser takes the control, gets the content from the transferState key and renders the content, but ssr is not working with this kind of dynamic content.

## 🔬 Minimal Reproduction

These are my main module and component

**app.module.ts**

<pre><code>export function createCompiler(compilerFactory: CompilerFactory) {
  return compilerFactory.createCompiler();
}

@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule.withServerTransition({ appId: 'serverApp' }),
    BrowserAnimationsModule,
    HttpClientModule,
    BrowserTransferStateModule,
    CoreModule
  ],
  providers: [
    HttpClientModule,
    { provide: COMPILER_OPTIONS, useValue: {}, multi: true },
    { provide: CompilerFactory, useClass: JitCompilerFactory, deps: [COMPILER_OPTIONS] },
    { provide: Compiler, useFactory: createCompiler, deps: [CompilerFactory] }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }</pre></code>

**app.component.ts**

<pre><code>
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements OnInit {
  categories$: Observable<any[]>;
  store$: Observable<any>;
  constructor() {}

  ngOnInit() {
    const cats = [
      { id: 1, name: 'XMAS' },
      { id: 2, name: 'KITCHEN' },
      { id: 3, name: 'DINNING' },
      { id: 4, name: 'BATHROOM' },
      { id: 5, name: 'BEDROOM' },
    ];
    const store = {
      countryCode : 'US',
    }
    this.store$ = of(store);
    this.categories$ = of(cats);
  }
}
</pre></code>

and basic html

```
<p>TEST</p>
<div *ngIf="categories?.length">
  <h2>CATEGORIES</h2>
  <ul *ngFor="let cat of categories">
    <li>{{ cat.name }}</li>
  </ul>
</div>
<footer>
  <app-dynamic-content name="Footer_Sections" [parentContext]="this"></app-dynamic-content>
</footer>
```

And this is the component I've made to render dynamic content fetched from the server

**dynamic-content.component.ts**

```
@Component({
    selector: 'app-dynamic-content',
    template: `        
      <ng-container>
        <ng-template #container></ng-template>
      </ng-container>
    `,
    styleUrls: ['./dynamic-content.component.scss'],
    changeDetection: ChangeDetectionStrategy.OnPush
  })
  export class DynamicContentComponent implements OnInit, OnDestroy, AfterViewInit {
    @Input() name: string;
    @Input() parentContext: any;
    @ViewChild('container', { read: ViewContainerRef }) container: ViewContainerRef;  
    private componentRef: ComponentRef;
    private unsubscribe = new Subject();  
    parsedContent: DynamicContent;
    dynamicContent$: Observable;
    template: string;
  
    constructor(
      private dynamicContentsService: DynamicContentsService,
      private compiler: Compiler,
      private changeDetectorRef: ChangeDetectorRef
    ) { }
  
    ngOnInit(): void {
      this.dynamicContent$ = this.dynamicContentsService.getDynamicContent(this.name).pipe(filter(res => !!res));
    }
  
    ngAfterViewInit() {
      this.dynamicContent$.pipe(take(1))
        .subscribe((response) => {
          if (response && response.dynamicContents.length) {
            this.parsedContent = this.dynamicContentsService.parseDinamycContent(response.dynamicContents as DynamicContent[]);
            this.template = this.parsedContent.value;
            this.createDynamicComponent();
          }
        });
    }
  
    createDynamicComponent() {
      const metadata = new Component({
        selector: 'app-dynamic',
        template: this.template
      });
  
      const factory = this.createComponentFactory(metadata);
      this.componentRef = this.container.createComponent(factory);
      this.changeDetectorRef.detectChanges();
    }
  

    createComponentFactory(metadata: Component): ComponentFactory {
      const self = this;
      const componentClass = class DynamicComponent { context: any = self.parentContext; };
      const moduleClass = class RuntimeComponentModule {};
      const decoratedComponent = Component(metadata)(componentClass);
      const modules = this.getModulesNeeded();
      const decoratedNgModule = NgModule({ imports: modules, declarations: [decoratedComponent] })(moduleClass);
      const module: ModuleWithComponentFactories = this.compiler.compileModuleAndAllComponentsSync(decoratedNgModule);
  
      return module.componentFactories.find(factory => factory.componentType === decoratedComponent);
    }
  
    getModulesNeeded() {
      return [BrowserModule, CommonModule];
    }
  
    ngOnDestroy() {
      this.unsubscribe.next();
      this.unsubscribe.complete();
  
      if (this.componentRef) {
        this.componentRef.destroy();
      }
    }
  }
```

And this is the html fetch in the http request

```
<div class="social" *ngIf="context.store$ | async as store">
  <div class="networks">
    <h3>Follow US</h3>
  </div>
</div>

```

 My universal server is made with the ng add universal command and the only change is a proxy middleware.

**server.ts**

<pre><code>
import 'zone.js/dist/zone-node';
import { createProxyMiddleware, Filter, Options, RequestHandler } from 'http-proxy-middleware';
import { ngExpressEngine } from '@nguniversal/express-engine';
import * as express from 'express';
import { join } from 'path';

import { AppServerModule } from './src/main.server';
import { APP_BASE_HREF } from '@angular/common';
import { existsSync } from 'fs';
import { environment } from 'src/environments/environment';

// The Express app is exported so that it can be used by serverless Functions.
export function app(): express.Express {
  const server = express();
  const distFolder = join(process.cwd(), 'dist/myApp/browser');
  const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index';

  // Our Universal express-engine (found @ https://github.com/angular/universal/tree/master/modules/express-engine)
  server.engine(
    'html',
    ngExpressEngine({
      bootstrap: AppServerModule,
    })
  );

  server.set('view engine', 'html');
  server.set('views', distFolder);
  server.use('/api', createProxyMiddleware({ target: environment?.host, changeOrigin: true }));
  server.get(
    '*.*',
    express.static(distFolder, {
      maxAge: '1y',
    })
  );

  // All regular routes use the Universal engine
  server.get('*', (req, res) => {
    console.log(req.params);
    res.render(indexHtml, { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] });
  });

  return server;
}

function run(): void {
  const port = process.env.PORT || 4000;

  // Start up the Node server
  const server = app();
  server.listen(port, () => {
    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

// Webpack will replace 'require' with '__webpack_require__'
// '__non_webpack_require__' is a proxy to Node 'require'
// The below code is to ensure that the server is run only when not requiring the bundle.
declare const __non_webpack_require__: NodeRequire;
const mainModule = __non_webpack_require__.main;
const moduleFilename = (mainModule && mainModule.filename) || '';
if (moduleFilename === __filename || moduleFilename.includes('iisnode')) {
  run();
}

export * from './src/main.server';
</pre></code>
## 🔥 Exception or Error
<pre><code>
ERROR Error: The pipe 'async' could not be found!
at getPipeDef$1 (C:\app\dist\myapp\server\main.js:1:2321863)
at ɵɵpipe (C:\app\dist\myapp\server\main.js:1:2321915)
at template (ng:///.js:150:9)
at executeTemplate (C:\app\dist\myapp\server\main.js:1:2097798)
at renderView (C:\app\dist\myapp\server\main.js:1:2093138)
at renderComponent (C:\app\dist\myapp\server\main.js:1:2111597)
at renderChildComponents (C:\app\dist\myapp\server\main.js:1:2093514)
at renderView (C:\app\dist\myapp\server\main.js:1:2093555)
at ComponentFactory$1.create (C:\app\dist\myapp\server\main.js:1:2313775)
at R3ViewContainerRef.createComponent (C:\app\dist\myapp\server\main.js:1:2130074)

</code></pre>
## 🌍 Your Environment
<pre><code>
Angular CLI: 10.1.7
Node: 12.14.1
OS: win32 x64

Angular: 10.2.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.7
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            10.1.7
@angular-devkit/schematics      10.1.7
@angular/cdk                    10.2.5
@angular/cli                    10.1.7
@angular/material               10.2.5
@nguniversal/builders           10.1.0
@nguniversal/express-engine     10.1.0
@schematics/angular             10.1.7
@schematics/update              0.1001.7
rxjs                            6.6.3
typescript                      3.9.7

</code></pre>

**Comment by hydra1983** [comment] 2022-01-18 17:33
The `imports: modules` not working. 
A workaround should be `declarations: [decoratedComponent, AsyncPipe]`.
No idea why this happens.

**Comment by cfrezier** [comment] 2022-11-14 12:55
I have the same problem right now also fixed by using declarations.
but imports seems to be working for components.

**Comment by alan-agius4** [comment] 2023-08-29 12:50
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Closed by alan-agius4** 2023-08-29 12:50 UTC
