### ISSUE TITLE
"IDBIndex is not defined" after updating from 13.03 → v13.10 (pre-rendering)

### ISSUE THREAD

**Issue by mazlano27** [angular/universal#2475] opened 2021-12-13 14:29 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

After upgrading to angular 13.10 from 13.03, pre-rending the app fails with the "IDBIndex is not defined" error.

### Please provide the exception or error you saw

```true
IDBIndex is not defined
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.1
Node: 14.17.0
Package Manager: npm 6.14.13
OS: darwin x64

Angular: 13.1.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                          Version
----------------------------------------------------------
@angular-devkit/architect        0.1301.1
@angular-devkit/build-angular    13.1.1
@angular-devkit/core             13.1.1
@angular-devkit/schematics       13.1.1
@angular/cli                     13.1.1
@angular/fire                    7.2.0
@nguniversal/aspnetcore-engine   13.0.1
@nguniversal/builders            13.0.1
@nguniversal/express-engine      13.0.1
@schematics/angular              13.1.1
rxjs                             6.6.7
typescript                       4.4.4

```

### Anything else?

Reverting back to 13.03 resolves this error.

**Comment by rnicholls** [comment] 2021-12-14 02:30
I have been trying to find a solution for this for about 5 days now. I tried downgrading to 13.0.3 but still, get the error. 

If I remember angular/fire for authentication it is resolved. Extremely frustrating.

**Comment by mazlano27** [comment] 2021-12-14 03:13
> I have been trying to find a solution for this for about 5 days now. I tried downgrading to 13.0.3 but still, get the error.
> 
> If I remove angular/fire for authentication it is resolved. Extremely frustrating.

Please check your package-lock.json if your angular version is the version you downgraded to? I sometimes find that the package.json version is different from package-lock.json version and this causes the issue.

The only solution i found was to manually uninstall all the angular packages (npm uninstall @angular/core.....) and then manually installing them again with the desired version (npm install --save @angular/core@13.0.3 ......)

**Comment by rnicholls** [comment] 2021-12-14 12:29
@mazlano27 you just saved my life on this. You were right. lock file had 3.1. Removed and manually added back 3.0.x and now dev:ssr is working!

**Comment by comporell** [comment] 2021-12-20 22:19
> > I have been trying to find a solution for this for about 5 days now. I tried downgrading to 13.0.3 but still, get the error.
> > If I remove angular/fire for authentication it is resolved. Extremely frustrating.
> 
> Please check your package-lock.json if your angular version is the version you downgraded to? I sometimes find that the package.json version is different from package-lock.json version and this causes the issue.
> 
> The only solution i found was to manually uninstall all the angular packages (npm uninstall @angular/core.....) and then manually installing them again with the desired version (npm install --save @angular/core@13.0.3 ......)

I've been stuck on this for days. That saved my ass. Thanks

**Comment by Burgov** [comment] 2021-12-27 09:11
I'm running into this error too. Any solutions?

**Comment by kgajera** [comment] 2021-12-29 02:25
I ran into this issue when upgrading from 12 to 13.1.

My project was not using a custom webpack file, but creating a webpack config file as documented (from 2018...) here solved my problem: https://github.com/angular/angularfire/blob/master/docs/universal/getting-started.md#3-add-a-webpack-config-for-the-express-server

**Comment by mazlano27** [comment] 2021-12-29 05:10
> 

Thank you for sharing. I tried to create the webpack config file but realised it was for SSR (and not pre-rendering). I tried it still and it does not seem to work for pre-rendering.

I tried to add the firebase packages as external dependencies in the angular.json file too - that didn't help either :/

**Comment by mazlano27** [comment] 2021-12-29 08:18
@kgajera thank you for your insight - based on some experimentation, I managed to find the fix! :) 

Solution: Create a custom webpack file which excludes firebase from the server bundle.

Steps:
1. Install @angular-builders/custom-webpack as a dev dependency
2. Create a file "custom-webpack.config.js" in the project root and add the following:

`module.exports = {
    externals: [
        /^firebase/
    ]
}`

3. Update angular.json to incorporate this customer webpack config into the build process

`"server": {
          "builder": "@angular-builders/custom-webpack:server",
          "options": {
            "customWebpackConfig": {
              "path": "./custom-webpack.config.js",
              "replaceDuplicatePlugins": true
            },
            ...
          },
        },`

4. Done!

**Comment by Burgov** [comment] 2021-12-29 13:49
Why is this suddenly necessary? Everything works fine with NG 13.0. I don't really like having to add a custom webpack config

**Comment by CaerusKaru** [comment] 2021-12-29 23:34
This sounds like something very much not an issue with Angular Universal. Can anyone point to something specific in Universal that shows the problem? If it's just a problem with Angular Fire, solved using the workaround they published, then we can either close this, or repurpose this to add docs for how to handle this edge case in the README.

**Comment by mazlano27** [comment] 2021-12-30 04:29
> This sounds like something very much not an issue with Angular Universal. Can anyone point to something specific in Universal that shows the problem? If it's just a problem with Angular Fire, solved using the workaround they published, then we can either close this, or repurpose this to add docs for how to handle this edge case in the README.

@CaerusKaru I'm not sure where this issue arises. It started after the 13.1 update - and I'm unable to point to something specific in Universal that shows the problem. Rolling back to 13.0 resolved the issue.

I think it's useful to document (as an edge case) how we might be able to exclude certain libraries from the universal build pipeline incase these libraries cause errors in the server side node environment?

**Comment by NobodyExceptHim** [comment] 2022-01-02 23:10
Has anyone found a solution? I'am stuck at it and I really don't want to add custom webpack config

**Comment by pedromoto4** [comment] 2022-01-03 02:06
Hello all seems that I'm facing the same problem, and has I have read the most direct solution is to downgrade Angular do 13.03 .
My question is, I need to downgrade all Angular libs to 13.03  ? 
there are any easy way todo this downgrade the right way ?

**Comment by NobodyExceptHim** [comment] 2022-01-03 08:22
> Hello all seems that I'm facing the same problem, and has I have read the most direct solution is to downgrade Angular do 13.03 .
> My question is, I need to downgrade all Angular libs to 13.03 ?
> there are any easy way todo this downgrade the right way ?

I was able to temporarily use mazlano27's solution. It's working and I don't need to downgrade but keep in mind that you would have to reverse this 'fix' in the future.

**Comment by miguelsmuller** [comment] 2022-01-06 14:18
I also have this problem for 2 days. I just found this issue and saw that it's not just me.
Has anyone had any progress in solving this problem?

**Comment by rossanmol** [comment] 2022-01-16 13:38
Downgrading to Node ^14 helped me.

**Comment by houssam98** [comment] 2022-01-23 10:27
I have tried downgrading to 13.0.3 but it still throws the same error. Any solutions yet?

**Comment by Santoshah** [comment] 2022-01-26 09:34
I am facing same issue

ReferenceError: IDBIndex is not defined

after I upgrade the Angular version from 12.0.1 to 13.1.3.

package.json
```
{

  "dependencies": {
    "@angular-material-components/datetime-picker": "6.0.3",
    "@angular/animations": "^13.1.3",
    "@angular/cdk": "^13.1.3",
    "@angular/common": "13.1.3",
    "@angular/compiler": "13.1.3",
    "@angular/core": "13.1.3",
    "@angular/fire": "^6.1.4",
    "@angular/forms": "13.1.3",
    "@angular/material": "13.1.3",
    "@angular/material-moment-adapter": "13.1.3",
    "@angular/platform-browser": "13.1.3",
    "@angular/platform-browser-dynamic": "13.1.3",
    "@angular/platform-server": "13.1.3",
    "@angular/router": "13.1.3",
    "@filestack/angular": "^1.3.0",
    "@fortawesome/fontawesome-free": "^5.15.4",
    "@fullcalendar/angular": "4.4.5-beta",
    "@fullcalendar/core": "4.4.2",
    "@fullcalendar/daygrid": "4.4.2",
    "@fullcalendar/interaction": "4.4.2",
    "@fullcalendar/list": "4.4.2",
    "@fullcalendar/moment": "4.4.2",
    "@fullcalendar/rrule": "4.4.2",
    "@fullcalendar/timegrid": "4.4.2",
    "@nguniversal/express-engine": "^12.0.0",
    "@types/jspdf": "^1.3.3",
    "@types/stripe": "^7.13.25",
    "animate.css": "^4.1.1",
    "aos": "^2.3.4",
    "apexcharts": "^3.26.1",
    "bootstrap": "^5.1.3",
    "crypto-js": "4.0.0",
    "data-uri-to-buffer": "^4.0.0",
    "domino": "^2.1.6",
    "express": "^4.15.2",
    "fetch-blob": "^3.1.4",
    "filestack-js": "^3.23.1",
    "firebase": "^8.10.0",
    "formdata-polyfill": "^4.0.10",
    "highlight.js": "10.7.2",
    "jquery": "^3.6.0",
    "jspdf": "^2.3.1",
    "lodash-es": "4.17.21",
    "moment": "^2.29.1",
    "ng-apexcharts": "^1.5.9",
    "ng-starrating": "^1.0.20",
    "ng-stripe-checkout": "^1.0.4",
    "ng-wistia-components": "0.0.2",
    "ngx-device-detector": "^2.0.8",
    "ngx-infinite-scroll": "^10.0.1",
    "ngx-mat-select-search": "^3.2.0",
    "ngx-moment": "^5.0.0",
    "ngx-quill": "^13.3.1",
    "node-fetch": "^3.2.0",
    "perfect-scrollbar": "1.5.0",
    "quill": "1.3.7",
    "rrule": "2.6.8",
    "rxjs": "7.5.2",
    "stripe": "^8.116.0",
    "stripe-angular": "^1.2.1",
    "tslib": "2.2.0",
    "yum": "^0.1.1",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "13.1.4",
    "@angular/cli": "13.1.4",
    "@angular/compiler-cli": "13.1.3",
    "@angular/language-service": "13.1.3",
    "@nguniversal/builders": "^12.0.0",
    "@ngx-builders/analyze": "^2.3.0",
    "@types/crypto-js": "4.0.1",
    "@types/express": "^4.17.0",
    "@types/highlight.js": "9.12.4",
    "@types/jasmine": "3.6.10",
    "@types/jasminewd2": "2.0.8",
    "@types/lodash-es": "4.17.4",
    "@types/node": "15.0.1",
    "bufferutil": "^4.0.3",
    "codelyzer": "6.0.2",
    "jasmine-core": "3.7.1",
    "jasmine-spec-reporter": "7.0.0",
    "karma": "6.3.2",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage-istanbul-reporter": "3.0.3",
    "karma-jasmine": "4.0.1",
    "karma-jasmine-html-reporter": "1.5.4",
    "ngx-owl-carousel-o": "^6.0.0",
    "protractor": "7.0.0",
    "tailwindcss": "2.1.2",
    "ts-node": "9.1.1",
    "tslint": "6.1.2",
    "typescript": "^4.5.5",
    "utf-8-validate": "^5.0.5",
    "ws": "^8.2.2",
    "xhr2": "^0.2.1"
  }
}

```

**Comment by Santoshah** [comment] 2022-01-27 14:25
> I have tried downgrading to 13.0.3 but it still throws the same error. Any solutions yet?

Delete these 
    package-lock.json 
    node_modules

Update version manually for angular and material. Try matching this package.json 
I did tried downgrade to 13.0.3 and it worked.

package.json

```
  "dependencies": {
    "@angular/animations": "^13.0.3",
    "@angular/cdk": "^13.0.3",
    "@angular/common": "13.0.3",
    "@angular/compiler": "13.0.3",
    "@angular/core": "13.0.3",
    "@angular/fire": "^6.1.4",
    "@angular/forms": "13.0.3",
    "@angular/material": "13.0.3",
    "@angular/material-moment-adapter": "13.0.3",
    "@angular/platform-browser": "13.0.3",
    "@angular/platform-browser-dynamic": "13.0.3",
    "@angular/platform-server": "13.0.3",
    "@angular/router": "13.0.3",
    "@nguniversal/express-engine": "^12.0.0",
    
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "13.0.3",
    "@angular/cli": "^13.0.3",
    "@angular/compiler-cli": "13.0.3",
    "@angular/language-service": "13.0.3",
    ......
```

**Comment by Santoshah** [comment] 2022-01-27 18:02
> @kgajera thank you for your insight - based on some experimentation, I managed to find the fix! :)
> 
> Solution: Create a custom webpack file which excludes firebase from the server bundle.
> 
> Steps:
> 
> 1. Install @angular-builders/custom-webpack as a dev dependency
> 2. Create a file "custom-webpack.config.js" in the project root and add the following:
> 
> ```
> module.exports = {
>      externals: [
>           /^firebase/
>      ]
> }
> ```
> 
> 3. Update angular.json to incorporate this custom webpack config into the build process
> 
> ```
> "server": {
>      "builder": "@angular-builders/custom-webpack:server",
>      "options": {
>           "customWebpackConfig": {
>                "path": "./custom-webpack.config.js",
>                "replaceDuplicatePlugins": true
>           },
>           ...
>      },
> },
> ```
> 
> 4. Done!
> 
> **References:**
> 
> 1. https://alligator.io/angular/Custom-webpack-config/
> 2. https://github.com/angular/angularfire/blob/master/docs/universal/getting-started.md#3-add-a-webpack-config-for-the-express-server
> 3. [WebpackError: ReferenceError: IDBIndex is not defined while building with Gatsby.JS (ver #2.15.21) firebase/firebase-js-sdk#2222 (comment)](https://github.com/firebase/firebase-js-sdk/issues/2222#issuecomment-538072948)

I am getting Error: No template for dependency: PureExpressionDependency errors after following custom webpack configuration.

any idea how to fix this.

[Detail can be found here](https://stackoverflow.com/questions/70883354/error-no-template-for-dependency-pureexpressiondependency)

**Comment by miguelsmuller** [comment] 2022-01-27 18:21
then @Santoshah 

I believe that it may be some incompatibility between the modules and even if you have removed the firebase from the webpack it is necessary... so it is giving an error...

taking firebase completely out of the bundle I don't think it's the ideal solution.

must have some firebase method that angular universal, for being ssr, is not able to execute.

the ideal would be someone from the core of one of the modules to at least open our eyes to what could be.

**Comment by jamesdaniels** [comment] 2022-02-28 20:15
AngularFire maintainer here, the root cause appears to be Firebase JS SDK's usage of the `idb` library. The version of the library that it uses doesn't have exports in it's package.json and expects CJS to be loaded in Node.js. In Angular 13.1+ that means unguarded calls to IndexDB are in your server bundle and causing runtime exceptions on load...

**Comment by jmarlow4** [comment] 2022-03-01 08:31
> AngularFire maintainer here, the root cause appears to be Firebase JS SDK's usage of the `idb` library. The version of the library that it uses doesn't have exports in its package.json and expects CJS to be loaded in Node.js. In Angular 13.1+ (unsure exactly which minor the change was introduced) that means unguarded calls to IndexDB are present in your server bundle, since it's now bundling ESM, and causing runtime exceptions on load...

Are there any plans to correct this?

**Comment by jamesdaniels** [comment] 2022-03-01 20:12
IMO this can be closed now that root cause has been identified as Firebase JS SDK, move conversation there.

**Comment by jamesdaniels** [comment] 2022-03-01 20:13
@jmarlow4 I opened an issue on that repo, I can only say that the team has been made aware. There are plans that would address the root cause at some point, hoping we can prioritize at least a short term fix.

**Comment by miguelsmuller** [comment] 2022-03-18 15:04
I really do not know. I can't do regression due to technical requirements of some dependencies. so i'm waiting for the proper solution.

The issue has already been opened in the appropriate project and I believe they are already looking:
https://github.com/firebase/firebase-js-sdk/issues/6042

**Comment by ohabash** [comment] 2022-03-18 15:09
Our team has all the latest versions of NX and NG (13.2) we were able to get rid of this problem by downgrading one package.

`"@angular-devkit/build-angular": "^13.0.4",`

**Comment by Santoshah** [comment] 2022-03-21 12:32
> Our team has all the latest versions of NX and NG (13.2) we were able to get rid of this problem by downgrading one package.
> 
> `"@angular-devkit/build-angular": "^13.0.4",`

This does the job.

**Closed** 2022-03-21 16:42 UTC
Labels: need: more info

**Comment by gaufranc** [comment] 2022-03-21 18:22
> Our team has all the latest versions of NX and NG (13.2) we were able to get rid of this problem by downgrading one package.
> 
> `"@angular-devkit/build-angular": "^13.0.4",`

This does not work in my case, would you share your full package.json?

**Comment by Santoshah** [comment] 2022-03-24 01:56
> > Our team has all the latest versions of NX and NG (13.2) we were able to get rid of this problem by downgrading one package.
> > `"@angular-devkit/build-angular": "^13.0.4",`
> 
> This does not work in my case, would you share your full package.json?


here is my package.json. I also got error regarding some version mismatch. For that I had to add browser names statically in my package.json to work. After this I was able to run SSR build and SSR serve with no issue. 
Hope you find it helpful. 

```

  "browserslist": [
    "and_chr 97",
    "and_ff 95",
    "and_qq 10.4",
    "and_uc 12.12",
    "baidu 7.12",
    "chrome 97",
    "chrome 96",
    "chrome 95",
    "chrome 94",
    "edge 97",
    "edge 96",
    "firefox 96",
    "firefox 95",
    "firefox 94",
    "firefox 91",
    "firefox 78",
    "ios_saf 15.0-15.1",
    "ios_saf 14.0-14.4",
    "kaios 2.5",
    "op_mini all",
    "op_mob 64",
    "opera 82",
    "safari 13.1",
    "samsung 16.0",
    "samsung 15.0"
  ],
  "resolutions": {
    "webpack": "^5.0.0-beta.30"
  },
  "dependencies": {
    "@angular-material-components/datetime-picker": "6.0.3",
    "@angular/animations": "^13.2.6",
    "@angular/cdk": "^13.2.6",
    "@angular/common": "13.3.0",
    "@angular/compiler": "13.3.0",
    "@angular/core": "13.3.0",
    "@angular/fire": "^6.1.4",
    "@angular/forms": "13.3.0",
    "@angular/material": "13.3.0",
    "@angular/material-moment-adapter": "13.3.0",
    "@angular/platform-browser": "13.3.0",
    "@angular/platform-browser-dynamic": "13.3.0",
    "@angular/platform-server": "13.3.0",
    "@angular/router": "13.3.0",
    "@filestack/angular": "1.4.0",
    "@fortawesome/fontawesome-free": "^5.15.4",
    "@fullcalendar/angular": "4.4.5-beta",
    "@fullcalendar/core": "4.4.2",
    "@fullcalendar/daygrid": "4.4.2",
    "@fullcalendar/interaction": "4.4.2",
    "@fullcalendar/list": "4.4.2",
    "@fullcalendar/moment": "4.4.2",
    "@fullcalendar/rrule": "4.4.2",
    "@fullcalendar/timegrid": "4.4.2",
    "@nguniversal/express-engine": "^12.0.0",
    "@types/jspdf": "^1.3.3",
    "@types/stripe": "^7.13.25",
    "algoliasearch": "^4.12.1",
    "angular-olark": "^1.0.0",
    "aos": "^2.3.4",
    "apexcharts": "^3.26.1",
    "bootstrap": "^5.1.3",
    "crypto-browserify": "^3.12.0",
    "crypto-js": "^4.0.0",
    "domino": "^2.1.6",
    "express": "^4.15.2",
    "filestack-js": "^3.23.1",
    "firebase": "^8.10.1",
    "highlight.js": "10.7.2",
    "jquery": "^3.6.0",
    "jspdf": "^2.5.1",
    "jspdf-autotable": "^3.5.23",
    "lodash-es": "4.17.21",
    "moment": "^2.29.1",
    "ng-apexcharts": "^1.5.9",
    "ng-starrating": "^1.0.20",
    "ng-stripe-checkout": "^1.0.4",
    "ng-wistia-components": "0.0.2",
    "ngx-device-detector": "^2.0.8",
    "ngx-hotjar": "^11.0.0",
    "ngx-infinite-scroll": "^10.0.1",
    "ngx-mat-select-search": "^3.2.0",
    "ngx-moment": "^5.0.0",
    "ngx-quill": "^16.2.0",
    "ngx-tooltip": "0.0.9",
    "node-fetch": "^2.6.1",
    "perfect-scrollbar": "1.5.0",
    "quill": "1.3.7",
    "rrule": "2.6.8",
    "rxjs": "7.5.5",
    "source-map-explorer": "^2.5.2",
    "stripe": "^8.116.0",
    "stripe-angular": "^1.2.1",
    "tslib": "2.2.0",
    "web-animations-js": "2.3.2",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "13.0.4",
    "@angular/cli": "13.3.0",
    "@angular/compiler-cli": "13.3.0",
    "@angular/language-service": "13.3.0",
    "@nguniversal/builders": "^12.0.0",
    "@ngx-builders/analyze": "^2.3.0",
    "@types/crypto-js": "4.0.1",
    "@types/express": "^4.17.0",
    "@types/highlight.js": "9.12.4",
    "@types/jasmine": "3.6.10",
    "@types/jasminewd2": "2.0.8",
    "@types/lodash-es": "4.17.4",
    "@types/node": "15.0.1",
    "bufferutil": "^4.0.3",
    "codelyzer": "6.0.2",
    "jasmine-core": "3.7.1",
    "jasmine-spec-reporter": "7.0.0",
    "karma": "6.3.2",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage-istanbul-reporter": "3.0.3",
    "karma-jasmine": "4.0.1",
    "karma-jasmine-html-reporter": "1.5.4",
    "ngx-owl-carousel-o": "^6.0.0",
    "protractor": "7.0.0",
    "tailwindcss": "2.1.2",
    "ts-node": "9.1.1",
    "tslint": "6.1.2",
    "typescript": "~4.4.0",
    "utf-8-validate": "^5.0.5",
    "ws": "^8.2.2",
    "xhr2": "^0.2.1"
  }
}

```
