### ISSUE TITLE
Create documentation on how to setup unit tests 

### ISSUE THREAD

**Issue by felixfiskare** [angular/universal#1726] opened 2020-06-11 20:02 UTC
# Proposal

#### What is the summary of the proposal?
Create documentation on how to set-up unit tests running in the angular-universal context.

#### What is the proposal?
Lately I've been having some problems with bugs only appearing when my angular application runs in SSR mode. While thinking about this I realized, that all my unit tests only run in the "run angular in a browser" context. Therefore I wanted to set up something to run my unit test in a "run angular in a node context". I've been researching the web for hours now and I haven't found anything which documents anything about this. Maybe it would be good to create some documentation on how to unit test components for SSR.

#### Is there anything else we should know?

**Comment by CaerusKaru** [comment] 2020-06-14 03:40
This is an excellent request, and one that I've wanted to take up for a while. One source of inspiration for you could be the testing setup in the [Angular Layout](https://github.com/angular/flex-layout) repository. There, the `npm run lib:test:ssr` command does what you're looking for, but I understand you're looking for something that can run in an Angular CLI application context.

We'll discuss this an hopefully come up with a design/docs that makes sense for this approach.

**Comment by alan-agius4** [comment] 2023-02-09 16:20
Duplicate of https://github.com/angular/universal/issues/2479

**Closed by alan-agius4** 2023-02-09 16:20 UTC
