### ISSUE TITLE
ApplicationModule_Factory inject() must be called from an injection context

### ISSUE THREAD

**Issue by gvonhagel** [angular/universal#1614] opened 2020-04-11 19:26 UTC
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [x] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

No

### Description

I am trying to write my own Universal rendering handler for Fastify. I used the @nguniversal/express-engine schematic but have attempted to implement my own handler using a Fastify middleware plugin. My logic for the rendering is based off of the express-engine and hapi-engine.

## 🔬 Minimal Reproduction

Run `ng add @nguniversal/express-engine`
Add server.ts in client folder 

```
import 'zone.js/dist/zone-node';
import './main.server';
export * from './main.server';
```

Specify this file in the tsconfig.server.json file

```
...
  "files": [
    "./server.ts"
  ],
```

Run generated build:ssr command (`"build:ssr": "ng build --prod && ng run Hyperion:server:production"`

Attempt to render AppServerModule on the back-end with Fastify. The plugin looks like this:

```
import { StaticProvider } from '@angular/core';
import { renderModule, renderModuleFactory } from '@angular/platform-server';
import { ɵCommonEngine as CommonEngine } from '@nguniversal/common/engine';
import {
  ɵREQUEST as Request,
  ɵRESPONSE as Response,
  ɵORIGIN_URL as Origin,
} from '@nguniversal/common/tokens';
import { NgSetupOptions } from '@server/app/core/angular/universal.interface';
import { FastifyInstance } from 'fastify';
import * as fastifyPlugin from 'fastify-plugin';
import { readFileSync } from 'fs';
import { isNil } from 'lodash';

/**
 * This holds a cached version of each index used.
 */
const templateCache: { [key: string]: string } = {};

/**
 * The CommonEngine with module to facory map in case of JIT.
 */
function fastifyAngularUniversal(fastify: FastifyInstance, options: NgSetupOptions, next: fastifyPlugin.nextCallback) {
  const commonEngine = new CommonEngine(options.bootstrap);
  fastify.decorateReply('renderNG', function () {
    const req = this.request;
    if (isNil(req.raw.url)) {
      throw new Error('URL is undefined');
    }
    const protocol = (req.headers['origin'] || '').startsWith('http') ? 'http' : 'https'; // FIXME Better way?
    const filePath = req.raw.url;
    return new Promise((resolve, reject) => {
      const moduleOrFactory = options.bootstrap;

      if (!moduleOrFactory) {
        return reject(new Error('You must pass in a NgModule or NgModuleFactory to be bootstrapped'));
      }

      options.url = `${protocol}://${req.raw.hostname}${filePath}`;
      options.document = options.document || getDocument(filePath);

      options.providers = options.providers || [];
      options['extraProviders'] = [];
      options.providers = options.providers.concat(getReqProviders(options.req, this));
      return commonEngine.render(options)
        .then(html => this.type('text/html').send(html))
        .catch(err => console.error(err));
    });
  });
  next();
}

function getReqProviders(req: any, res: any): StaticProvider[] {
  const providers: StaticProvider[] = [
    {
      provide: Request,
      useValue: req,
    },
  ];
  providers.push({
    provide: Response,
    useValue: res,
  });
  return providers;
}

/**
 * Get the document at the file path
 */
function getDocument(filePath: string): string {
  return templateCache[filePath] = templateCache[filePath] || readFileSync(filePath).toString();
}

module.exports = fastifyPlugin(fastifyAngularUniversal, {
  fastify: '2.x',
  name: 'fastify-angular-universal',
});
```

AppServerModule is provided to the plugin from this `require` statement:
```
    const bundle = require(join(process.cwd(), 'dist/Hyperion/server/main'));
    const bootstrap = bundle.AppServerModule;
```

## 🔥 Exception or Error
<pre><code>
Error: inject() must be called from an injection context
    at injectInjectorOnly (D:\StreetMetrics\Hyperion\dist\Hyperion\server\main.js:1:4051643)
    at ɵɵinject (D:\StreetMetrics\Hyperion\dist\Hyperion\server\main.js:1:4051959)
    at Object.ApplicationModule_Factory [as factory] (D:\StreetMetrics\Hyperion\dist\Hyperion\server\main.js:1:4457212)
    at R3Injector.hydrate (D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:11583:39)
    at R3Injector.get (D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:11405:37)
    at D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:11345:77
    at Set.forEach (<anonymous>)
    at new R3Injector (D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:11345:35)
    at createInjector (D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:11310:16)
    at new NgModuleRef$1 (D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:24357:33)
    at NgModuleFactory.create (D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:24424:20)
    at D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:28119:47
    at ZoneDelegate.invoke (D:\StreetMetrics\Hyperion\dist\Hyperion\server\main.js:1:3902460)
    at Object.onInvoke (D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:27590:37)
    at ZoneDelegate.invoke (D:\StreetMetrics\Hyperion\dist\Hyperion\server\main.js:1:3902356)
    at Zone.run (D:\StreetMetrics\Hyperion\dist\Hyperion\server\main.js:1:3894874)
    at NgZone.run (D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:27487:32)
    at PlatformRef.bootstrapModuleFactory (D:\StreetMetrics\Hyperion\node_modules\@angular\core\bundles\core.umd.js:28115:27)
    at Object.renderModuleFactory (D:\StreetMetrics\Hyperion\node_modules\@angular\platform-server\bundles\platform-server.umd.js:1117:43)
    at CommonEngine.<anonymous> (D:\StreetMetrics\Hyperion\node_modules\@nguniversal\common\bundles\common-engine.umd.js:75:66)
    at step (D:\StreetMetrics\Hyperion\node_modules\tslib\tslib.js:139:27)
    at Object.next (D:\StreetMetrics\Hyperion\node_modules\tslib\tslib.js:120:57)

</code></pre>

## 🌍 Your Environment
<pre>
<code>
Angular CLI: 9.0.3
Node: 12.16.1
OS: win32 x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular-devkit/schematics-cli    0.13.8
@angular/cdk                      8.2.3
@angular/cli                      9.0.3
@angular/platform-server          9.0.7
@ngtools/webpack                  9.0.3
@nguniversal/builders             9.1.0
@nguniversal/common               9.1.0
@nguniversal/express-engine       9.0.1
@schematics/angular               9.0.3
@schematics/schematics            0.13.8
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.42.1

</code></pre>

**Comment by cherryland** [comment] 2020-04-22 00:28
Duplicate of https://github.com/angular/universal/issues/1504

**Comment by CaerusKaru** [comment] 2020-06-14 04:16
@cherryland is right, closing.

**Closed by CaerusKaru** 2020-06-14 04:16 UTC
