### ISSUE TITLE
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by greg-md** [angular/universal#1169] opened 2019-05-31 13:35 UTC
# Bug Report

Lazy Loading is not working with Angular 8 while using the new behavior of `loadChildren` parameter. But it works with the old approach.

```typescript
const routes: Routes = [
  {
    path: 'home',
    loadChildren: () => import('./home/home.module').then(mod => mod.HomeModule),
    //loadChildren: './home/home.module#HomeModule',
  }
];
```

#### What is the expected behavior?

Should lazy load routes.

#### What is the current behavior?

Getting error:
```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (/my-app/fronttest/dist/server.js:137764:30)
    at Function.requireEnsure [as e] (/my-app/fronttest/dist/server.js:137783:25)
    at ɵ0 (/my-app/fronttest/dist/server.js:137913:38)
    at RouterConfigLoader.loadModuleFactory (/my-app/fronttest/dist/server.js:150015:39)
    at RouterConfigLoader.load (/my-app/fronttest/dist/server.js:150000:35)
    at MergeMapSubscriber.project (/my-app/fronttest/dist/server.js:149003:47)
    at MergeMapSubscriber._tryNext (/my-app/fronttest/dist/server.js:37063:27)
    at MergeMapSubscriber._next (/my-app/fronttest/dist/server.js:37053:18)
    at MergeMapSubscriber.Subscriber.next (/my-app/fronttest/dist/server.js:33575:18)
    at Observable._subscribe (/my-app/fronttest/dist/server.js:35645:20)
    at resolvePromise (/my-app/fronttest/dist/server.js:1000:31)
    at resolvePromise (/my-app/fronttest/dist/server.js:957:17)
    at /my-app/fronttest/dist/server.js:1061:17
    at ZoneDelegate.invokeTask (/my-app/fronttest/dist/server.js:571:31)
    at Object.onInvokeTask (/my-app/fronttest/dist/server.js:28531:33)
    at ZoneDelegate.invokeTask (/my-app/fronttest/dist/server.js:570:60)
    at Zone.runTask (/my-app/fronttest/dist/server.js:343:47)
    at drainMicroTaskQueue (/my-app/fronttest/dist/server.js:749:35)
    at ZoneTask.invokeTask (/my-app/fronttest/dist/server.js:650:21)
    at Server.ZoneTask.invoke (/my-app/fronttest/dist/server.js:635:48) {
  rejection: TypeError: Cannot read property 'call' of undefined
      at __webpack_require__ (/my-app/fronttest/dist/server.js:137764:30)
      at Function.requireEnsure [as e] (/my-app/fronttest/dist/server.js:137783:25)
      at ɵ0 (/my-app/fronttest/dist/server.js:137913:38)
      at RouterConfigLoader.loadModuleFactory (/my-app/fronttest/dist/server.js:150015:39)
      at RouterConfigLoader.load (/my-app/fronttest/dist/server.js:150000:35)
      at MergeMapSubscriber.project (/my-app/fronttest/dist/server.js:149003:47)
      at MergeMapSubscriber._tryNext (/my-app/fronttest/dist/server.js:37063:27)
      at MergeMapSubscriber._next (/my-app/fronttest/dist/server.js:37053:18)
      at MergeMapSubscriber.Subscriber.next (/my-app/fronttest/dist/server.js:33575:18)
      at Observable._subscribe (/my-app/fronttest/dist/server.js:35645:20),
  promise: ZoneAwarePromise [Promise] {
    __zone_symbol__state: 0,
    __zone_symbol__value: TypeError: Cannot read property 'call' of undefined
        at __webpack_require__ (/my-app/fronttest/dist/server.js:137764:30)
        at Function.requireEnsure [as e] (/my-app/fronttest/dist/server.js:137783:25)
        at ɵ0 (/my-app/fronttest/dist/server.js:137913:38)
        at RouterConfigLoader.loadModuleFactory (/my-app/fronttest/dist/server.js:150015:39)
        at RouterConfigLoader.load (/my-app/fronttest/dist/server.js:150000:35)
        at MergeMapSubscriber.project (/my-app/fronttest/dist/server.js:149003:47)
        at MergeMapSubscriber._tryNext (/my-app/fronttest/dist/server.js:37063:27)
        at MergeMapSubscriber._next (/my-app/fronttest/dist/server.js:37053:18)
        at MergeMapSubscriber.Subscriber.next (/my-app/fronttest/dist/server.js:33575:18)
        at Observable._subscribe (/my-app/fronttest/dist/server.js:35645:20)
  },
  zone: Zone {
    _parent: Zone {
      _parent: null,
      _name: '<root>',
      _properties: {},
      _zoneDelegate: [ZoneDelegate]
    },
    _name: 'angular',
    _properties: { isAngularZone: true },
    _zoneDelegate: ZoneDelegate {
      _taskCounts: [Object],
      zone: [Circular],
      _parentDelegate: [ZoneDelegate],
      _forkZS: null,
      _forkDlgt: null,
      _forkCurrZone: [Zone],
      _interceptZS: null,
      _interceptDlgt: null,
      _interceptCurrZone: [Zone],
      _invokeZS: [Object],
      _invokeDlgt: [ZoneDelegate],
      _invokeCurrZone: [Circular],
      _handleErrorZS: [Object],
      _handleErrorDlgt: [ZoneDelegate],
      _handleErrorCurrZone: [Circular],
      _scheduleTaskZS: [Object],
      _scheduleTaskDlgt: [ZoneDelegate],
      _scheduleTaskCurrZone: [Circular],
      _invokeTaskZS: [Object],
      _invokeTaskDlgt: [ZoneDelegate],
      _invokeTaskCurrZone: [Circular],
      _cancelTaskZS: [Object],
      _cancelTaskDlgt: [ZoneDelegate],
      _cancelTaskCurrZone: [Circular],
      _hasTaskZS: [Object],
      _hasTaskDlgt: [ZoneDelegate],
      _hasTaskDlgtOwner: [Circular],
      _hasTaskCurrZone: [Circular]
    }
  },
  task: ZoneTask {
    _zone: Zone {
      _parent: [Zone],
      _name: 'angular',
      _properties: [Object],
      _zoneDelegate: [ZoneDelegate]
    },
    runCount: 0,
    _zoneDelegates: null,
    _state: 'notScheduled',
    type: 'microTask',
    source: 'Promise.then',
    data: ZoneAwarePromise [Promise] {
      __zone_symbol__state: 0,
      __zone_symbol__value: TypeError: Cannot read property 'call' of undefined
          at __webpack_require__ (/my-app/fronttest/dist/server.js:137764:30)
          at Function.requireEnsure [as e] (/my-app/fronttest/dist/server.js:137783:25)
          at ɵ0 (/my-app/fronttest/dist/server.js:137913:38)
          at RouterConfigLoader.loadModuleFactory (/my-app/fronttest/dist/server.js:150015:39)
          at RouterConfigLoader.load (/my-app/fronttest/dist/server.js:150000:35)
          at MergeMapSubscriber.project (/my-app/fronttest/dist/server.js:149003:47)
          at MergeMapSubscriber._tryNext (/my-app/fronttest/dist/server.js:37063:27)
          at MergeMapSubscriber._next (/my-app/fronttest/dist/server.js:37053:18)
          at MergeMapSubscriber.Subscriber.next (/my-app/fronttest/dist/server.js:33575:18)
          at Observable._subscribe (/my-app/fronttest/dist/server.js:35645:20)
    },
    scheduleFn: undefined,
    cancelFn: undefined,
    callback: [Function],
    invoke: [Function]
  }
}
```

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [+] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:

In a new project, follow the steps from https://angular.io/guide/universal and generate a simple lazy loading module.

#### What is the use-case or motivation for changing an existing behavior?

Following the new behavior of Version 8.

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common:
  - express-engine:
  - hapi-engine:
  - module-map-ngfactory-loader:
```
Angular CLI: 8.0.1
Node: 12.3.1
OS: darwin x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.800.1
@angular-devkit/build-angular              0.800.1
@angular-devkit/build-optimizer            0.800.1
@angular-devkit/build-webpack              0.800.1
@angular-devkit/core                       8.0.1
@angular-devkit/schematics                 8.0.1
@angular/cli                               8.0.1
@ngtools/webpack                           8.0.1
@nguniversal/express-engine                7.0.2
@nguniversal/module-map-ngfactory-loader   7.0.2
@schematics/angular                        8.0.1
@schematics/update                         0.800.1
rxjs                                       6.4.0
typescript                                 3.4.5
webpack                                    4.30.0
```

#### Is there anything else we should know?

**Comment by vikerman** [comment] 2019-05-31 16:32
Hi - This is a known issue we are fixing in the next RC - https://github.com/angular/universal/commit/d8be7af200f067a9f65c4f5ab48d8468a4b7ca33

The problem is that there are two copies of Angular in the older way of setting up Universal and it confuses.

Please refer to this commit on a sample project on how you can fix this for your existing project - https://github.com/vikerman/v8-lazy/commit/515239be1b233946e4a1d15a8712a0bc9f5490cc

Essentially we move all dependency on Angular bits from `server.ts` to `main.server.ts`. You can fix this manually for now. We are working on a `ng update` script tp automatically fix up existing projects. Thanks!

**Comment by jrodl3r** [comment] 2019-07-06 20:08
@vikerman getting theses errors when I apply those changes https://gist.github.com/jrodl3r/ca2cf2dfe79cd7cf871609cab386a2c5

```javascript
    “@angular/common": "~8.0.1",
    "@angular/compiler": "~8.0.1",
    "@angular/core": "~8.0.1",
    "@angular/fire": "^5.2.1",
    "@angular/forms": "~8.0.1",
    "@angular/platform-browser": "~8.0.1",
    "@angular/platform-browser-dynamic": "~8.0.1",
    "@angular/platform-server": "~8.0.1",
    "@angular/router": "~8.0.1",
    "@nguniversal/express-engine": "^7.0.2",
    "@nguniversal/module-map-ngfactory-loader": "v7.0.2",
    "express": "^4.15.2",
```

**Comment by PierreChavaroche** [comment] 2019-07-12 08:35
@vikerman 
Thanks for the informations!
What can we do if we are using "libraryTarget: 'umd'"? E.g. for Firebase hosting.
The "externals" configuration of webpack.server.config.ts doesn't seems to work then, because I get the following error:
Error parsing triggers: Cannot find module 'require("./server/main")'

Thank you very much!

**Comment by gotik** [comment] 2019-07-26 01:33
> @vikerman
> Thanks for the informations!
> What can we do if we are using "_libraryTarget: 'umd'_"? E.g. for Firebase hosting.
> The "_externals_" configuration of _webpack.server.config.ts_ doesn't seems to work then, because I get the following error:
> _Error parsing triggers: Cannot find module 'require("./server/main")'_
> 
> Thank you very much!

I'm having the same issue with `libraryTarget: 'commonjs2'` is there a workaround you can think of @vikerman 🙏 ?

**Comment by vikerman** [comment] 2019-07-31 04:14
Need to investigate this since I'm not familiar with setting the libraryTarget. Do you have a sample project I can use?

Can you remove `--bundleDepencies all` in package.json to see whether it fixes your issue?

**Comment by vikerman** [comment] 2019-07-31 04:17
Also can someone point to the info on building for firebase hosting? Why do you need libraryTarget umd in the first place?

**Comment by ponkys** [comment] 2019-08-01 19:21
I had the same issue and it was solved when I added `"module": “commonjs”` in tsconfig.server.json.

**Comment by gotik** [comment] 2019-08-04 02:57
@vikerman removing `--bundleDepencies all` doesn't fix the issue.
We are exporting `app` (in the `server.ts`) file, hence the need for `libraryTarget`, the reason to do that is that we have several places importing it, one of them to create aws lambda functions.
I created a project that shows the problem https://github.com/gotik/cannot-find-module-issue
I also included a `test.js` file to validate that `app` can be imported from the outside.

@ponkys that didn't work for us, could you please elaborate around your fix?

**Comment by chenlitchian** [comment] 2019-08-05 02:48
![image](https://user-images.githubusercontent.com/22153909/62435381-878d9800-b76e-11e9-8306-857ed26c8e21.png)


Same Issue here

**Comment by ponkys** [comment] 2019-08-14 12:59
@gotik I was having the same error with lazy loading. I added "module": “commonjs” in tsconfig.server.json. and the issue was fixed. It worked for some people already. https://github.com/angular/angular/issues/31092

**Comment by gotik** [comment] 2019-08-14 18:34
> @gotik I was having the same error with lazy loading. I added "module": “commonjs” in tsconfig.server.json. and the issue was fixed. It worked for some people already. [angular/angular#31092](https://github.com/angular/angular/issues/31092)

Thank you @ponkys we already have `module: commonjs` https://github.com/gotik/cannot-find-module-issue/blob/master/tsconfig.server.json#L5,  the problem is that the oficial fix for the `TypeError: Cannot read property 'call' of undefined` error doesn't work when the project uses a `libraryTarget` https://github.com/angular/universal/issues/1169#issuecomment-510802226

**Comment by killian2301** [comment] 2019-10-02 12:08
> @vikerman
> Thanks for the informations!
> What can we do if we are using "_libraryTarget: 'umd'_"? E.g. for Firebase hosting.
> The "_externals_" configuration of _webpack.server.config.ts_ doesn't seems to work then, because I get the following error:
> _Error parsing triggers: Cannot find module 'require("./server/main")'_
> 
> Thank you very much!

Did you figured this out? @PierreChavaroche . I'm having the exact same problem...

**Comment by PierreChavaroche** [comment] 2019-10-07 13:35
@killian2301 
Unfortunately not. We are using the old lazy loading syntax at the moment.

**Comment by karocksjoelee** [comment] 2019-12-03 13:59
Any solution on this ?   
I tried --bundleDependencies all, but got `Error: No NgModule metadata found for '[object Object]'.`

**Comment by karocksjoelee** [comment] 2019-12-03 14:32
I just figured out , it just hit me during shower lol. 
For those whom are facing this problem : 
Since we are using Server side rendering, we doesn't need to use lazy load module , ( it doesn't make sense to use it ) every page of your is already sending by the server. 

But it will be better to provide a smooth solution for this. ( In case that some project need to be use both on CSR and SSR )

**Comment by lukaszgodula** [comment] 2019-12-03 16:28
It's not truth. Server side rendered is only first page user visits, then we have rehydration and again csr, so lady load is still very good idea to make bundles chnked and smaller.

**Comment by JayPSaadeDev** [comment] 2019-12-10 15:08
> @vikerman
> Thanks for the informations!
> What can we do if we are using "_libraryTarget: 'umd'_"? E.g. for Firebase hosting.
> The "_externals_" configuration of _webpack.server.config.ts_ doesn't seems to work then, because I get the following error:
> _Error parsing triggers: Cannot find module 'require("./server/main")'_
> 
> Thank you very much!

Any updates on how to fix this?

**Comment by vikerman** [comment] 2019-12-12 04:23
Please follow the version 8 migration guide at https://github.com/angular/universal/blob/master/README.md#version-8 . That should avoid the above issue.

**Comment by gotik** [comment] 2019-12-17 20:23
@vikerman I created a project that reproduces the issue, it has the changes described in the Angular 8 migration guide https://github.com/angular/universal/blob/master/docs/v8-upgrade-guide.md#fix but the issue is still present,  please keep in mind the issue happens when `libraryTarget` is set to `commonjs` or `umd`

**Comment by PierreChavaroche** [comment] 2020-04-16 19:44
Are there any other informations we could provide for helping to fix the problem?
Due to this problem we've to decide between Angular 9 (Ivy) and SSR 😔🤔

Thank you very much!

**Comment by ponkys** [comment] 2020-04-16 21:25
Hey pierre, I had the same problem last year and I fixed it by changing some configuration in the tsconfig.server.json file. We can take a look at your specific problem together if you want. I can make some time as I was in your same situation a year ago and I know how it feels.

**Comment by gotik** [comment] 2020-06-03 16:36
I wasn't able to use Angular 8 + dynamic import syntax + `libraryTarget: "commonjs"`, still, I decided to try Angular 9 and it works just fine (with dynamic import syntax!) I guess  https://github.com/angular/universal/blob/master/modules/express-engine/schematics/install/files/__serverFileName%40stripTsExtension__.ts#L50-L58 and `@nguniversal/express-engine` no longer using `@nguniversal/module-map-ngfactory-loader` had something to do.

**Comment by alan-agius4** [comment] 2023-02-09 13:25
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases.

**Closed by alan-agius4** 2023-02-09 13:25 UTC
