### ISSUE TITLE
material 2 in angular 4.3 breaks

### ISSUE THREAD

**Issue by hakobpogh** [angular/universal#764] opened 2017-07-31 04:23 UTC
I have tested material 2 in angular 4.3.x and it's not working. But your documentation says that in angular 4.1+ material 2 should fully work...

After build, when the express should start it throws an error "Unexpected token import" in file "/dist/ngfactory/node_modules/@angular/material/typings/index.ngfactory.ts:9/"

please help me to find out a solution...

**Comment by Toxicable** [comment] 2017-08-18 10:58
Looks like an issue with Material not totally covering Universal support yet
Issue for tracking looks like this one https://github.com/angular/material2/issues/308

**Comment by dockleryxk** [comment] 2017-08-24 13:50
Are you importing MaterialModule or are you importing the modules individually?

**Comment by hakobpogh** [comment] 2017-08-27 14:14
I'm including all the component modules individually @dockleryxk.

@Toxicable, when the material.angular will cover the universal? and when it'll be finally released? It looks like to be too long in beta version... and I looked at Polymer it looks like that its components are more pretty and more bugless. So maybe the material.angular team can work with Polymer team to finally give any release. Or can even take a look at their codes for fixing some UI issues.

**Comment by Toxicable** [comment] 2017-09-14 21:21
@hakobpogh is still this an issue on the latest release of Material?

**Comment by hakobpogh** [comment] 2017-09-18 20:27
I've tested it for beta-10 release and the issue still exists.

**Comment by Toxicable** [comment] 2017-09-18 20:37
@hakobpogh What issue? What error do you get with Universal?

**Comment by patrickmichalina** [comment] 2017-09-18 21:09
I have it working here https://angular.patrickmichalina.com

**Comment by hakobpogh** [comment] 2017-09-18 21:15
Thank you @patrickmichalina. But have you tested it with angular 4.* and not angular 5. Becuase the angular 5 is in beta yet so I'll prefer to use stable version instead.

**Comment by patrickmichalina** [comment] 2017-09-18 21:22
@hakobpogh yes angular 4.3 was how I started.

**Comment by Toxicable** [comment] 2017-10-10 19:08
This should be fixed on the latest versions of Material.
If you still have an issue then open it up on the Material repo since that's where the root cause is

**Closed by Toxicable** 2017-10-10 19:08 UTC
