### ISSUE TITLE
Error handling for prerender

### ISSUE THREAD

**Issue by vikerman** [angular/universal#1371] opened 2019-12-09 23:57 UTC
# Bug Report

When there is an error in a prerendered route(like invalid route), just the error stack is printed on the console and there is no good error handling

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [X] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:
ng new univ
cd univ
ng add @nguniversal/express-engine@next
ng run univ:prerender --routes /about   (/about is an invalid route)

This produces an error stack in the console and the /about prerender page is still written.

**Comment by wagnermaciel** [comment] 2020-01-21 17:14
@vikerman and I discussed this separately but for the sake of documentation:

There is no good way to determine if an error happened. Angular already implements its own error handler and it is too high up the tree for us to provide our own. We would need to make a change to angular/angular to allow us to pass in our own error handler.

**Comment by chris13524** [comment] 2020-02-09 01:28
@wagnermaciel what's the code [here](https://github.com/angular/universal/blob/v9.0.0/modules/builders/src/prerender/index.ts#L85) supposed to do, then?

I also get errors logged to the console but it doesn't tell me from which route it originated from (like the code above is supposed to).

**Comment by s2young** [comment] 2020-03-03 19:04
Maybe the issue is actually [here](https://github.com/angular/universal/blob/3aa454d132a761027da2908a2cc2c1f37dabd847/modules/builders/src/prerender/index.ts#L89).  Instead of just rejecting the promise, can that error be stringified and logged?  I have no idea what is going wrong in my rendering because all I get is [Error] in the output.

**Comment by wagnermaciel** [comment] 2020-03-05 17:55
@chris13524 First - sorry for the delayed response! The code in [index.ts](https://github.com/angular/universal/blob/v9.0.0/modules/builders/src/prerender/index.ts#L85) happens if we send a message with `success: false`. This kind of message only gets sent from [render.ts](https://github.com/angular/universal/blob/v9.0.0/modules/builders/src/prerender/render.ts#L79) when there is an error writing the rendered html to the file system.

So in summary, the code you pointed out is catching & logging errors that happen when writing the rendered output to the file system. What we want is to catch errors that happen [while we are rendering the output](https://github.com/angular/universal/blob/v9.0.0/modules/builders/src/prerender/render.ts#L59), but angular is already catching these errors and there's currently no way for us to detect them.

@s2young  Likewise, the errors you get when rendering would be originating from [here](https://github.com/angular/universal/blob/v9.0.0/modules/builders/src/prerender/render.ts#L59).  The errors caught [here](https://github.com/angular/universal/blob/v9.0.0/modules/builders/src/prerender/index.ts#L90) won't be providing you info about what's going wrong in the rendering.

**Comment by s2young** [comment] 2020-03-06 18:08
Thanks for the response.  I guess the bigger issue for me right now is [17021](https://github.com/angular/angular-cli/issues/17021).  I can't use prerendering at all until it's actually building output like ng build.

**Comment by craheb** [comment] 2020-09-16 19:20
Depending on your scenario, this script maybe be a hack/workaround for detecting an error.

```sh
#!/usr/bin/env bash
result=$(ng run univ:prerender --routes /about 2>&1)

if [[ $result == *"ERROR"* ]]; then
    echo "There was an error in prerendering:"
    echo "$result"
    exit 1
fi
```

**Comment by alan-agius4** [comment] 2023-05-22 18:53
Duplicate of https://github.com/angular/angular/issues/33642

**Closed by alan-agius4** 2023-05-22 18:53 UTC
Labels: area: builders, type: bug/fix
