### ISSUE TITLE
Angular CLI builder for a devserver/live reload

### ISSUE THREAD

**Issue by vikerman** [angular/universal#1202] opened 2019-07-12 17:47 UTC
Need to create an Angular CLI Architect builder that can provide development server that builds in watch mode and live reloads whenever the project changes.

We can consider replacing `ng serve` with this builder as part of the @nguniversal schematics.

**Comment by almgwary** [comment] 2019-10-15 22:13
Any updates ?

**Comment by alan-agius4** [comment] 2019-11-11 14:00
Also related to https://github.com/angular/universal/issues/1022

Hi @almgwary, this is something that we are currently looking at.

**Comment by alan-agius4** [comment] 2019-12-03 09:37
Let's close this in favour of https://github.com/angular/universal/issues/1202 since there is more discussion over there.

Duplicate of https://github.com/angular/universal/issues/1202

**Closed by alan-agius4** 2019-12-03 09:37 UTC
