### ISSUE TITLE
Documentation "Finished Sample Code" does not appear to work

### ISSUE THREAD

**Issue by mindingdata** [angular/universal#1530] opened 2020-02-28 22:43 UTC
# 🐞 Bug report

### Description

The documentation example zip either does not work as intended, or the instructions are not complete. 

## 🔬 Minimal Reproduction

- Go to https://angular.io/guide/universal
- Click the link " Download the finished sample code" and download completed zip. 
- Run "npm install" to install dependencies
- Run "npm run build:ssr && npm run serve:ssr". 
- No error message. Last line is : 
<pre>
> angular-io-example@1.0.0 serve:ssr C:\Users\me\Downloads\universal
> node dist/server.js
</pre>
- Attempt to open localhost:4000. Does not appear to listen on this port. 

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.25
Node: 12.13.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, upgrade

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.800.0
@angular-devkit/build-angular              0.800.0
@angular-devkit/build-optimizer            0.800.0
@angular-devkit/build-webpack              0.800.0
@angular-devkit/core                       8.0.0
@angular-devkit/schematics                 8.3.25
@angular/cli                               8.3.25
@ngtools/webpack                           8.0.0
@nguniversal/express-engine                8.2.6
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        8.3.25
@schematics/update                         0.803.25
rxjs                                       6.5.4
typescript                                 3.4.5
webpack                                    4.30.0
</code></pre>

**Comment by alan-agius4** [comment] 2020-02-29 11:46
Duplicate of https://github.com/angular/angular/issues/35289

**Closed by alan-agius4** 2020-02-29 11:46 UTC
