### ISSUE TITLE
twice load images in *ngFor in ssr

### ISSUE THREAD

**Issue by shomid** [angular/universal#1596] opened 2020-04-02 09:36 UTC
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [x] builders
- [x] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

Is this a regression?

Yes, the previous version(angular 8) in which this bug was not present was: this problem is angular 9 with ivy

### Description
i have a array of images and i want to show with *ngFor but images twice load in ssr.
once with `index(parser)` and Once upon a time `platform-browser.js`.

sample code:

     <div *ngFor="let cat of serviceRecentList; trackBy: trackById">
       <img [src]="cat.picPath">
       <h3>{{ cat.Title }}</h3>
     </div>

![Screenshot from 2020-04-02 12-54-36](https://user-images.githubusercontent.com/8733354/78232923-3646cb80-74ea-11ea-97cd-2c8b00399696.png)

## 🔬 Minimal Reproduction
this is source of my project : [source](https://drive.google.com/open?id=1njCJ84JQA7frEQrP9VONEFlIBS0P9BbN) for build and test.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>
{
  "name": "amyar24site",
  "version": "2.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points",
    "compile:server_bak": "webpack --config webpack.server.config.js --progress --colors",
    "build:ssr_bak": "npm run build:client-and-server-bundles && npm run compile:server",
    "serve:ssr_bak": "node dist/server",
    "build:client-and-server-bundles_bak": "ng build --prod && ng run amyar24site:server:production --bundleDependencies all",
    "dev:ssr": "ng run amyar24site:serve-ssr",
    "serve:ssr": "node dist/server/main.js",
    "build:ssr": "ng build --prod && ng run amyar24site:server:production",
    "prerender": "ng run amyar24site:prerender"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.0",
    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "~9.1.0",
    "@angular/forms": "~9.1.0",
    "@angular/http": "~7.2.16",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/platform-server": "~9.1.0",
    "@angular/router": "~9.1.0",
    "@ng-select/ng-select": "^3.7.2",
    "@nguniversal/common": "~9.1.0",
    "@nguniversal/express-engine": "^9.1.0",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "animate.css": "^3.7.2",
    "bootstrap": "^4.4.1",
    "compression": "^1.7.4",
    "core-js": "^3.6.4",
    "domino": "^2.1.4",
    "express": "^4.17.1",
    "hover.css": "^2.3.2",
    "intersection-observer": "^0.7.0",
    "memory-cache": "^0.2.0",
    "moment": "2.24.0",
    "moment-jalaali": "0.9.2",
    "ng-in-viewport": "^6.0.3",
    "ng-lazyload-image": "^7.1.0",
    "ngx-bootstrap": "^5.6.1",
    "ngx-cookie-service": "^3.0.3",
    "ngx-device-detector": "^1.4.1",
    "rxjs": "~6.5.4",
    "tslib": "^1.11.1",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.0",
    "@angular/cli": "^9.1.0",
    "@angular/compiler-cli": "~9.1.0",
    "@angular/language-service": "~9.1.0",
    "@nguniversal/builders": "^9.1.0",
    "@types/express": "^4.17.3",
    "@types/jasmine": "~3.5.10",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "^13.9.2",
    "codelyzer": "^5.2.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.1",
    "karma-jasmine": "~3.1.1",
    "karma-jasmine-html-reporter": "^1.5.3",
    "protractor": "~5.4.3",
    "ts-loader": "6.2.2",
    "ts-node": "~8.8.1",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3",
    "webpack-cli": "3.3.11"
  }
}
</code></pre>

**Comment by CaerusKaru** [comment] 2020-06-14 04:21
Please provide a minimal reproduction on GitHub. This would be something that has as minimal drift from an `ng new` application as possible.

**Comment by alan-agius4** [comment] 2021-10-14 17:55
Closing due to lack of communication.

**Closed by alan-agius4** 2021-10-14 17:55 UTC
Labels: need: repro steps
