### ISSUE TITLE
No NgModule metadata found for '[object Object]'

### ISSUE THREAD

**Issue by DigambarPradhan** [angular/universal#2111] opened 2021-05-17 14:17 UTC
Locally working as expected. But when i deploy on server i am getting the error {"status":500,"message":"You must pass in a NgModule or NgModuleFactory to be bootstrapped","name":"Error" in angular 10 application.

**Comment by alan-agius4** [comment] 2021-05-17 16:30
Duplicate of https://github.com/angular/universal/issues/1067#issuecomment-842336431

**Closed by alan-agius4** 2021-05-17 16:30 UTC
