### ISSUE TITLE
styles not loaded on ssr

### ISSUE THREAD

**Issue by akshata456** [angular/universal#1751] opened 2020-07-01 05:40 UTC
we want to load styles.scss in serverside page load.Here we used angular 7 framework.How we achieved that?
check this issue also for reference
https://github.com/angular/universal/issues/974#issue-319061018

**Comment by CaerusKaru** [comment] 2020-07-03 05:51
Duplicate of #974

**Closed by CaerusKaru** 2020-07-03 05:51 UTC
