### ISSUE TITLE
Events are not called

### ISSUE THREAD

**Issue by GeorgeHulpoi** [angular/universal#1263] opened 2019-09-27 17:01 UTC
# Bug Report

#### What is the expected behavior?

I tried to convert my own project to SSR, but I had a strange bug, my event callbacks of window were never called, even if the global window variable was defined. After few tries to reproduce the problem, I've seen that if the main component (the bootstrapped component) has the selector "body", well the events will not work.
The solution is to use another selector ("app-root" for example).

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [x] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:

Just create a new project, with a bootstrap component with selector "body"

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine:  -
  - common: -
  - express-engine: 8.1.1
  - hapi-engine: -
  - module-map-ngfactory-loader: 8.1.1
```
Angular CLI: 8.2.2
Node: 10.16.3
OS: win32 x64
Angular: 8.2.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.802.2
@angular-devkit/build-angular              0.802.2
@angular-devkit/build-optimizer            0.802.2
@angular-devkit/build-webpack              0.802.2
@angular-devkit/core                       8.2.2
@angular-devkit/schematics                 8.2.2
@angular/cli                               8.2.2
@ngtools/webpack                           8.2.2
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.2.2
@schematics/update                         0.802.2
rxjs                                       6.4.0
typescript                                 3.5.3
webpack                                    4.38.0
```

#### Is there anything else we should know?

**Comment by vikerman** [comment] 2019-10-01 19:07
What sort of events are you expecting to be fired? In general we don't really want to fire or handle events during SSR.

**Comment by GeorgeHulpoi** [comment] 2019-10-01 19:11
@vikerman browsers events like scroll or resize.

**Comment by vikerman** [comment] 2019-10-01 21:05
Ok - These will not be fired on the server since there is no actual window on the server.

**Comment by GeorgeHulpoi** [comment] 2019-10-01 21:19
@vikerman did you read what I wrote? "even if the global window variable was defined".

**Comment by CaerusKaru** [comment] 2019-10-01 21:21
@GeorgeHulpoi What @vikerman means is that there is no defined screen on the server. The `Window` object has no size, does not get resized, etc. All paint events (resize, scroll) are ignored on the server in Angular's SSR DOM provider.

**Comment by vikerman** [comment] 2019-10-01 21:21
But it's not a functioning window. What does firing scroll or resize on the server mean?

**Comment by GeorgeHulpoi** [comment] 2019-10-03 20:52
> @GeorgeHulpoi What @vikerman means is that there is no defined screen on the server. The `Window` object has no size, does not get resized, etc. All paint events (resize, scroll) are ignored on the server in Angular's SSR DOM provider.

The problem still persists even if I inject the Window Object with Domino. As I said, everything works fine if the application bootstrap component is not the "body". Do you want to make 2 projects to see the differences?

**Comment by CaerusKaru** [comment] 2019-10-03 21:05
If this is more than a philosophical issue about Events on the server, your problem may be better handled on the Domino side, since we don’t really do much on top of their interface.

**Comment by yunusyerli1** [comment] 2022-06-30 14:15
Does HostListener works with Angular Universal?

**Comment by alan-agius4** [comment] 2023-04-12 07:05
Closing as this is working as intended.

**Closed by alan-agius4** 2023-04-12 07:05 UTC
Labels: need: investigation, area: common
