### ISSUE TITLE
Prerender doesn't use the build options setting for the default "index.html" name

### ISSUE THREAD

**Issue by vmasek** [angular/universal#1585] opened 2020-03-28 22:10 UTC
# 🐞 Bug report

Prerender builder seems to ignore the build options setting the default "index.html" name/location.

#### What modules are related to this issue?
- [x] builders

### Is this a regression?
No

### Description
From what I've seen the prerender 
## 🔬 Minimal Reproduction
1. Rename your `index.html` to something else, for example: `index.original.html`
2. Set the correct name in `angular.json` configuration for `projects.name.architect.build.options.index`
   - in this case `"index": "src/index.original.html",`
3. Try to prerender your application

## 🔥 Exception or Error
<pre><code>
An unhandled exception occurred: ENOENT: no such file or directory, open 'C:\Users\user-name\WebstormProjects\my-project\dist\browser\index.html'
</code></pre>
This is expected as `dist\browser\index.html` does not exist, but `dist\browser\index.original.html` does.

## Possible solution
Replacing `browserIndexOutputPath` at line `https://github.com/angular/universal/blob/f0a78c4792ebd6e4e920cda60552be123f7c6810/modules/builders/src/prerender/index.ts#L111`
with `path.join(outputPath, 'index.original.html')` seems to fix the error, but only the "default" route is rendered and I don't even have it specified in routes I want to render.

It would be ideal if the prerender builder respected the setting set in the build options.

I'm open to PR but I need guidance determining the best solution and on how to get the builder options to the `_renderUniversal` function.

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.0
Node: 12.16.1
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.6
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.0.6
@angular-devkit/schematics        9.1.0
@angular/cdk                      9.2.0
@angular/flex-layout              9.0.0-beta.29
@ngtools/webpack                  9.1.0
@nguniversal/builders             9.0.2
@nguniversal/common               9.0.2
@nguniversal/express-engine       9.0.2
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Comment by wagnermaciel** [comment] 2020-03-31 00:16
Hey @vmasek, thank you for your bug report. I don't believe this was ever an option for the prerender builder. You can see the list of options that the prerender builder has available by viewing [`schema.ts`](https://github.com/angular/universal/blob/master/modules/builders/src/prerender/schema.ts) or [`schema.json`](https://github.com/angular/universal/blob/master/modules/builders/src/prerender/schema.json).

@alan-agius4 I do think this is a perfectly valid feature request, though. What are your thoughts?

**Comment by alan-agius4** [comment] 2020-03-31 05:59
Indeed this is a bug as this line https://github.com/angular/universal/blob/f0a78c4792ebd6e4e920cda60552be123f7c6810/modules/builders/src/prerender/index.ts#L110 as using a hard coded to use `index.html` and not using the index from the index provided in browser builder options.

**Comment by wagnermaciel** [comment] 2020-03-31 18:17
Ah, I see. I did not catch that this option was coming from the `browser` builder. Thank you for the clarification!

**Comment by wagnermaciel** [comment] 2020-04-03 00:39
I have a fix for this - Should be ready by tomorrow 👍

**Comment by wagnermaciel** [comment] 2020-04-04 00:19
Hey, just discussed this with Minko and we quickly realized that the expected behavior here might not be so clear.

@vmasek can you provide some clarification on why users change the default html document? I want to familiarize myself with this use case before trying to make this change.

Also, I'd like to hear your opinions on what should happen if a user sets their base html document as `"src/home.html"` and tries to prerender the route `"/"`. Should we prerender it as `"home.html"`?

**Comment by alan-agius4** [comment] 2020-04-04 06:16
I think the following option should be honoured https://github.com/angular/angular-cli/blob/29660aa8edf23c416c8c82677136b642c4992c2d/packages/angular_devkit/build_angular/src/browser/schema.json#L293

Meaning the input/output of the index should be gather from this option.

I don’t know that’s the usecase in this case for changing the index file but I did see in the past different indexes for different environments, themes etc..

**Comment by wagnermaciel** [comment] 2020-04-04 22:56
I agree that the `index` option from `angular_devkit` should continue to be used, but the question still stands - if someone has sets the `index` option to point to a different file (e.g. `"src/home.html"`) should prerendering the route `"/"` generate the static file for `"home.html"` or `"index.html"`?

**Comment by alan-agius4** [comment] 2020-04-05 06:41
The pretending behaviour shouldn’t change.

The difference is the the input file and the output file name.

Let’s take this offline.

**Comment by vmasek** [comment] 2020-04-05 11:02
@wagnermaciel It might be fixable by some workaround.

My use-case is this.

There is a website served by a cloud function. on the base root `"/"` it automatically detects a preferred language and redirects to that language route.

Code example for express server
```
  server.get('/', (req: express.Request, res: express.Response): void => {
    if (req.acceptsLanguages('cs', 'sk')) {
      res.redirect(302, '/cs/homepage');
    } else {
      res.redirect(302, `/en/homepage`);
    }
  });
```

So for the base `"/"` route we don't want any HTML response, just the redirect.

Express static server will server the `"/"` route with the `/index.html` if not disabled in config.
There are two possibilities to solve this. Disable it or rename the index Angular uses to render app.
But we cannot disable only the base `/index.html`, it disables all of them, so no pre-rendering with this disabled.

If we rename the "base" index, we will end up at this problem.

What I thought of as a workaround would be to exclude  `"/"` route and the rename the `/index.html` in dist after the pre-rendering has been done to `/index.original.html`. Or include the  `"/"` route (don't care about what it renders) and than remove the base `/index.html` in dist so it is not picked up by the static serve.

**Comment by wagnermaciel** [comment] 2020-04-08 21:53
@alan-agius4 It seems like the express-engine server has not honored this feature either. See how in [`express-engine's server.ts schematic`](https://github.com/angular/universal/blob/master/modules/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts#L15) we only render using `"index"` or `"index.original.html"`.

Should we add support for this feature as part of this PR or as a separate PR?

**Comment by wagnermaciel** [comment] 2020-04-08 21:54
The same issue is true for [`hapi-engine's server.ts schematic`](https://github.com/angular/universal/blob/master/modules/hapi-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts#L24).

**Comment by wagnermaciel** [comment] 2020-04-08 22:29
@alan-agius4 Also, I am a bit confused about the functionality of the browser builder's `index` option. If you specify a _string_, e.g. `"src/home.html"` then the output index file is `"dist/app_name/browser/home.html"`. But if you specify an _object_, e.g. `{ input: "src/home.html", output: "src/home.html" }`, then the output index file is `"dist/app/app_name/browser/src/home.html"`.

This is caused by the way [`getIndexOutputFile`](https://github.com/angular/angular-cli/blob/29660aa8edf23c416c8c82677136b642c4992c2d/packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts#L237) was written.

Is this divergence intentional? I couldn't find any documentation for it. In fact, [the documentation that I could find for this feature](https://angular.io/cli/build) is a little empty.

**Comment by alan-agius4** [comment] 2020-04-09 16:18
@wagnermaciel, that is indented and expected when specifying using `output`, as whatever specified their is respected.

When no output is specified only the file name is taken into consideration.

**Closed** 2020-04-15 10:16 UTC
Labels: comp: builders, effort1: hours, type: bug/fix
