### ISSUE TITLE
There is no opportunity to render Angular to string

### ISSUE THREAD

**Issue by DmitrySobolevski** [angular/universal#1503] opened 2020-02-12 10:35 UTC
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

I'm trying to render Angular to string even at empty project to modify the response, but get an error. 

Here is my server.ts:
```
import 'zone.js/dist/zone-node';

import * as express from 'express';
import { join } from 'path';
import { renderModuleFactory } from '@angular/platform-server';
import { readFileSync } from 'fs';

const app = express();

const PORT = process.env.PORT || 4000;
const DIST_FOLDER = join(process.cwd(), 'dist/browser');

const { AppServerModuleNgFactory, LAZY_MODULE_MAP, ngExpressEngine, provideModuleMap } = require('./dist/server/main');

app.set('view engine', 'html');
app.set('views', DIST_FOLDER);

const template = readFileSync(join(DIST_FOLDER, 'index.html')).toString();

app.get('*', (req, res) => {
  renderModuleFactory(AppServerModuleNgFactory, {
    url: req.url,
    document: template,
    extraProviders: [provideModuleMap(LAZY_MODULE_MAP)]
  }).then(html => {
    console.log(html);
    res.send('it works');
  });
});

app.listen(PORT, () => {
  console.log(`Node Express server listening on http://localhost:${ PORT }`);
});
```

## 🔬 Minimal Reproduction
```
npm run build:client-and-server-bundles
npm run build:ssr
npm run serve:ssr
```

## 🔥 Exception or Error
<pre><code>
 TypeError: Cannot read property 'subscribe' of undefined
     at new core_ApplicationRef (/home/dzmitry/Work/ng-cli-universal/dist/server/main.js:73198:37)
     at _createClass (/home/dzmitry/Work/ng-cli-universal/dist/server/main.js:63871:20)
     at _createProviderInstance (/home/dzmitry/Work/ng-cli-universal/dist/server/main.js:63825:26)
     at initNgModule (/home/dzmitry/Work/ng-cli-universal/dist/server/main.js:63731:32)
     at new NgModuleRef_ (/home/dzmitry/Work/ng-cli-universal/dist/server/main.js:64841:9)
     at Object.createNgModuleRef (/home/dzmitry/Work/ng-cli-universal/dist/server/main.js:64824:12)
     at NgModuleFactory_.create (/home/dzmitry/Work/ng-cli-universal/dist/server/main.js:78167:25)
     at /home/dzmitry/Work/ng-cli-universal/dist/server.js:60802:43
     at ZoneDelegate.invoke (/home/dzmitry/Work/ng-cli-universal/dist/server.js:540:26)
     at Object.onInvoke (/home/dzmitry/Work/ng-cli-universal/dist/server.js:60310:33)
</code></pre>

## 🌍 Your Environment
<pre><code>
"dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/platform-server": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@nguniversal/express-engine": "^8.2.6",
    "@nguniversal/module-map-ngfactory-loader": "v8.2.6",
    "express": "^4.15.2",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  }

</code></pre>

**Comment by alan-agius4** [comment] 2020-02-12 16:44
Duplicate of https://github.com/angular/universal/issues/1485#issuecomment-581805693

**Closed by alan-agius4** 2020-02-12 16:44 UTC
