### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:63336

### ISSUE THREAD

**Issue by ImTung** [angular/universal#2227] opened 2021-08-04 08:33 UTC
After upgrade to v12, I run: `npm run dev:ssr`:
```
connect ECONNREFUSED 127.0.0.1:63336
```

but run without ssr, it's worked

# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error
My log file
<pre><code>
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '~/.nvm/versions/node/v14.17.0/bin/node',
1 verbose cli   '~/.nvm/versions/node/v14.17.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev:ssr'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose run-script [ 'predev:ssr', 'dev:ssr', 'postdev:ssr' ]
5 info lifecycle project@2.0.0~predev:ssr: project@2.0.0
6 info lifecycle project@2.0.0~dev:ssr: project@2.0.0
7 verbose lifecycle project@2.0.0~dev:ssr: unsafe-perm in lifecycle true
8 verbose lifecycle project@2.0.0~dev:ssr: PATH: ~/.nvm/versions/node/v14.17.0/lib/node_modules/...
9 verbose lifecycle project@2.0.0~dev:ssr: CWD: ~/Documents/project/kyzook/web.eat.chat
10 silly lifecycle project@2.0.0~dev:ssr: Args: [ '-c', 'ng run ineons:serve-ssr' ]
11 silly lifecycle project@2.0.0~dev:ssr: Returned: code: 1  signal: null
12 info lifecycle project@2.0.0~dev:ssr: Failed to exec dev:ssr script
13 verbose stack Error: project@2.0.0 dev:ssr: `ng run ineons:serve-ssr`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (~/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:376:20)
13 verbose stack     at ChildProcess.<anonymous> (~/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:376:20)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid project@2.0.0
15 verbose cwd ~/Documents/project/kyzook/web.eat.chat
16 verbose Darwin 20.6.0
17 verbose argv "~/.nvm/versions/node/v14.17.0/bin/node" "~/.nvm/versions/node/v14.17.0/bin/npm" "run" "dev:ssr"
18 verbose node v14.17.0
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error project@2.0.0 dev:ssr: `ng run ineons:serve-ssr`
22 error Exit status 1
23 error Failed at the project@2.0.0 dev:ssr script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.1.4
Node: 14.17.0
Package Manager: npm 6.14.13
OS: darwin arm64

Angular: 12.1.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, google-maps, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.4
@angular-devkit/build-angular   12.1.4
@angular-devkit/core            8.3.29
@angular-devkit/schematics      8.3.29
@nguniversal/builders           12.1.0
@nguniversal/express-engine     12.1.0
@schematics/angular             8.3.29
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Comment by jsanta** [comment] 2022-02-23 23:50
Same error  using v13.1.14 different port though.

**Comment by vrapalis** [comment] 2022-04-04 11:17
Any updates here? Same thing :(

**Comment by vincepunkrock** [comment] 2022-04-05 12:32
It think it's related to this issue? https://github.com/angular/universal/issues/1848

**Comment by UrinStone** [comment] 2022-04-07 22:26
Same here on v10.1.0

**Comment by alan-agius4** [comment] 2022-04-13 06:58
Duplicate of https://github.com/angular/universal/issues/1848

**Closed by alan-agius4** 2022-04-13 06:58 UTC
