### ISSUE TITLE
Bad Performance when update @nguniversal/express-engine from 11.1 to 12.1

### ISSUE THREAD

**Issue by Aventrue** [angular/universal#2230] opened 2021-08-05 14:25 UTC
After we updated the @nguniversal/express-engine from 11.1 to 12.1 we have much slower performance.
With 11.1 we have a average response time from 750ms and with the new version it is about 1600ms.
What can cause this problem and how can we solve it?

**Comment by alan-agius4** [comment] 2021-08-05 14:38
Duplicate of https://github.com/angular/universal/issues/2106

**Closed by alan-agius4** 2021-08-05 14:38 UTC
