### ISSUE TITLE
Strict mode creates error in server.ts

### ISSUE THREAD

**Issue by jorgjanke** [angular/universal#1750] opened 2020-06-29 05:09 UTC
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Description
 A clear and concise description of the problem or missing capability...
When enabling strict mode, ng build results in
```
ERROR in server.ts:22:25 - error TS2345: Argument of type '(filePath: string, options: Readonly<RenderOptions>, callback: (err?: Error | null | undefined, html?: string | undefined) => void) => void' is not assignable to parameter of type '(path: string, options: object, callback: (e: any, rendered?: string | undefined) => void) => void'.
  Types of parameters 'options' and 'options' are incompatible.
    Type '{}' is missing the following properties from type 'Readonly<RenderOptions>': req, bootstrap

22   server.engine('html', ngExpressEngine({
                           ~~~~~~~~~~~~~~~~~
23     bootstrap: AppServerModule,
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
24   }));
   ~~~~
```

I tried to set "strict": false in **tsconfig.server.json** and also changed the "extends" to tsconfig.base.json 
and just set strict in tsconfig.app.json - ng build creates the error.

tsconfig.server.json:
```
{
  "extends": "./tsconfig.base.json", // changed
  "compilerOptions": {
    "outDir": "./out-tsc/app-server",
    "types": [
      "node"
    ],
    "target": "es2016",
    "strict": false // ignored
  },
  "files": [
    "src/main.server.ts",
    "server.ts"
  ],
  "angularCompilerOptions": {
    "entryModule": "./src/app/app.server.module#AppServerModule"
  }
}
```

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
Ideally, the offending code should be made 'strict'
```
  server.engine('html', ngExpressEngine({
    bootstrap: AppServerModule,
  }));

```
... unfortunately, I didn't manage to do that 

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

could not get the tsconfig to work either.

**Comment by CaerusKaru** [comment] 2020-06-29 05:10
Duplicate of #1744

**Closed by CaerusKaru** 2020-06-29 05:10 UTC
