### ISSUE TITLE
node_modules Resolution error in SSR setup with Nested Directories

### ISSUE THREAD

**Issue by wendyplacko** [angular/universal#932] opened 2018-03-16 20:50 UTC
* **I'm submitting a ...**
```
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

I've recreated an express server following the tutorial exactly but for one small change. I would like to nest all angular files in a subdirectory and have the dist folder in the root directory. Doing so throws an error when I run webpack:server. I'm getting errors for all modules, here is an example:

ERROR in ../dist/server/main.bundle.js
Module not found: Error: Can't resolve '@angular/common' in '/Users/placko/Sites/angular-recaptcha-test/dist/server'
 @ ../dist/server/main.bundle.js 1:35611-35637
 @ ./server.ts

It is clear that the build can't find the node_modules file inside of the subdirectory I have placed Angular in, called "lib." But, I can't figure out how to tell the script to look for node_modules in lib. Is this something that could be added to the script documentation?

* **Please tell us about your environment:**

- Angular version: 5.2.9
- Browser: [all]
- Language: [Typescript 2.4.2]
- OS:  [Mac OS X]
- Platform: [NodeJS]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us 
to have context, eg. stackoverflow, gitter, etc)

[Channels]: https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question
[preboot]: https://github.com/angular/preboot

**Comment by Toxicable** [comment] 2018-03-16 21:05
Im not certain what you're trying to achieve by the description give.
Could you provide a minimal reproduction?

**Comment by wendyplacko** [comment] 2018-03-16 21:46
Here is a repo:
https://github.com/wendyplacko/angular-ssr-error

The build works fine and puts everything in dist, but I get errors when I run webpack:server

**Comment by Toxicable** [comment] 2018-03-16 22:02
Oh I see what you mean now.
Yeah that wont work.
Your files must be in a directly equal or below the location of node_modules, otherwise nodejs will not be able to find the dependencies there.
This isn't configurable

**Comment by Toxicable** [comment] 2018-03-22 21:40
closing due to the above description

**Closed by Toxicable** 2018-03-22 21:40 UTC
Labels: state: Need repro
