### ISSUE TITLE
Unable to bundle node_modules with webpack

### ISSUE THREAD

**Issue by euberdeveloper** [angular/universal#1125] opened 2019-02-11 19:09 UTC
# Bug Report

#### What is the expected behavior?

Everything should be bundled in the dist folder, with two dirs (browser and server) and a file (server.js).
I should be able to have only this folder to run my server and serve the pages, without have the weight of node_modules

#### What is the current behavior?

I got an error when I lunch the server:

```
Cannot find module '../lib/utils.js'
    at Function.webpackEmptyContext [as resolve] (
```

The only way I found to resolve the problem is change to externals with this on the webpack configuration:

```javascript
var nodeExternals = require('webpack-node-externals');

module.exports = {
     externals: [nodeExternals()], //Old value was /node_modules/
     //The rest of the conf
}
```

The problem is that to run the express server I need also the node_modules folder, and it weights.

**Comment by CaerusKaru** [comment] 2019-02-11 19:11
Duplicate of https://github.com/angular/angular-cli/issues/8616

**Closed by CaerusKaru** 2019-02-11 19:11 UTC
