### ISSUE TITLE
ERROR in ./src/app1/main.server.ts, Module not Found Error: Can't resolve 'app/.../...module.ngfactory.js' ( in latest CLI )

### ISSUE THREAD

**Issue by nekkon** [angular/universal#854] opened 2017-11-28 13:01 UTC
Hello. I have a repo which you can clone and reproduce the issue (https://github.com/nekkon/angular-cli-library). After you install the node modules run `npm run app1:ssr:build` and you will see the errors. If you build the browser version of the app `npm run app1:build` everything gets built properly. Any suggestion/tip of what the problem could be? Any help would be greatly appreciated @gdi2290 + @Toxicable   Thanks in advance for your great work so far.

Just to add more info about the errors: I think it has to do with lazy loading the modules in the app.routing.ts . They are lazy loaded properly when app is served or built, but they can not be found when they are built for server side rendering. Not sure what causes this. An example of the error shown `ERROR in ./src/app1/main.server.ts, Module not Found Error: Can't resolve 'app/.../...module.ngfactory.js' `

**Comment by beeman** [comment] 2017-12-04 14:42
@nekkon I just had a similar issue and in my case the solution was to make sure I imported `ModuleMapLoaderModule` as the last module in the `imports` array of my `ModuleMapLoaderModule`.

So this worked:

```typescript
import {NgModule} from '@angular/core';
import {ServerModule} from '@angular/platform-server';
import {ModuleMapLoaderModule} from '@nguniversal/module-map-ngfactory-loader';

import {AppModule} from './app.module';
import {AppComponent} from './app.component';

@NgModule({
  imports: [
    AppModule,
    ServerModule,
    ModuleMapLoaderModule,
  ],
  bootstrap: [AppComponent],
})
export class AppServerModule {}
``` 

while this failed:

```typescript
import {NgModule} from '@angular/core';
import {ServerModule} from '@angular/platform-server';
import {ModuleMapLoaderModule} from '@nguniversal/module-map-ngfactory-loader';

import {AppModule} from './app.module';
import {AppComponent} from './app.component';

@NgModule({
  imports: [
    ServerModule,
    ModuleMapLoaderModule,
    AppModule,
  ],
  bootstrap: [AppComponent]
})
export class AppServerModule {}
```

I'm not sure if this is the fix to your issue but it might :-)

**Comment by nekkon** [comment] 2017-12-05 07:25
@beeman Thanks for the tip. I checked my server.module.ts and the modules were in the correct order. I believe it is something else.

**Comment by christofferskog** [comment] 2017-12-11 07:56
Ye I tried `ModuleMapLoaderModule` as well but with no luck.

**Comment by igmdvc** [comment] 2018-03-15 15:06
+1 on this issue. Non universal lazy load is working fine with enabled AOT. the universal compilation is failing and the ModuleMapLoaderModule sorting proposal is not working for me

**Comment by gfaganli** [comment] 2018-04-21 21:26
the same error in case of applying Universal + lazyload. Pls let me know if its is solved or not

**Comment by Toxicable** [comment] 2018-04-22 18:45
@igmdvc I don't have any issues with using lazy modules.
The order of imports is important, double check that.
Also double check here https://github.com/angular/universal-starter  to ensure you have it setup correctly.
If the issue still persists then please make a minimal reproduction.

**Comment by Toxicable** [comment] 2018-05-10 08:59
Since no minimal reproduction has been produced im going to close this off.
If you still have an issue feel free to open another issue with a minimal reproduction

**Closed by Toxicable** 2018-05-10 08:59 UTC
Labels: state: Need repro

**Comment by Iar0** [comment] 2018-05-20 21:08
Having the exact same problem...@nekkon did you solved it?

**Comment by ymchandra** [comment] 2019-04-16 08:28
Any help to resolve this problem? I have added ModuleMapLoaderModule and in correct order as well. Still no luck.

**Comment by eyho** [comment] 2019-04-30 23:34
For me, as beeman mentioned, adding _ModuleMapLoaderModule_ to _app.server.module.ts_ solved the issue. The order of the imported modules did matter also.
