### ISSUE TITLE
Golang Adapter for SSR

### ISSUE THREAD

**Issue by ZheyangSong** [angular/universal#781] opened 2017-08-22 22:43 UTC
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
```
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
N/A

* **Do you want to request a *feature* or report a *bug*?**
I'm requesting a feature.

* **What is the current behavior?**
There is currently no support for SSR on a Golang server.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

* **What is the expected behavior?**
I should be able to use all functionalities provided by this repo on a Golang server.

* **What is the motivation / use case for changing the behavior?**
Golang gets more popular and should be supported by this repo for wider technology stack choices when using Angular.

* **Please tell us about your environment:**

- Angular version: 4.X
- Browser: all
- Language: Typescript 2.4.2
- OS:  Mac OS X
- Platform: Golang

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Toxicable** [comment] 2017-08-25 05:04
duplicate of #391

**Comment by MarkPieszak** [comment] 2017-08-25 18:59
Thanks @Toxicable closing as duplicate

**Closed by MarkPieszak** 2017-08-25 18:59 UTC
