### ISSUE TITLE
Server Side rendering with hot reload?

### ISSUE THREAD

**Issue by sushrest** [angular/universal#1123] opened 2019-02-09 23:01 UTC
# Feature Request
ServerSide rendering with hotreload like in CSR we have ng serve --watch

#### What is the desired behavior?
SSR reloads on file change on the browser at port 4000

#### What is the use-case or motivation for the desired behavior?
Speeds up development

#### Is there anything else we should know?

**Comment by CaerusKaru** [comment] 2019-02-09 23:07
Duplicate of #1022

**Closed by CaerusKaru** 2019-02-09 23:07 UTC
