### ISSUE TITLE
router-outlet causes error on server, does not render content

### ISSUE THREAD

**Issue by jeffbcross** [angular/universal#180] opened 2016-01-11 00:04 UTC
Using `router-outlet` causes [this error](https://gist.github.com/jeffbcross/17b22435de4324d923ec) on the server with a simple component:

```
TypeError: Cannot read property 'viewManager' of null
    at ElementInjector.getViewContainerRef (universal-starter/node_modules/angular2/src/core/linker/element_injector.js:374:80)
...
```
(See [full stacktrace](https://gist.github.com/jeffbcross/17b22435de4324d923ec))

The client routes correctly.

See [this branch](https://github.com/jeffbcross/universal-starter/tree/router-outlet) of universal-starter to reproduce.

FWIW I tried applying a similar approach to [this patch](https://github.com/SteveSandersonMS/universal/commit/ab82e4e54cf4a8e098eae79fad7fdb46f7dbfdad) in `server/src/platform/node.js` with no effect: 

```js
//bootstrap()
...
var platformRef = core_1.platform(exports.NODE_PROVIDERS);
    platformRef.componentTypes = [appComponentType];

    return platformRef
        .application(appProviders)
        .bootstrap(appComponentType, componentProviders);
...
```

This problem is also mentioned #123

CC @jeffwhelpley @gdi2290 @SteveSandersonMS

**Comment by alexpods** [comment] 2016-01-16 23:55
@jeffbcross @jeffwhelpley @gdi2290

The cause of the error is:
1. An injector creates `RootRouter`
2. `RouterRouter` calls `navigateToUrl` [here](https://github.com/angular/angular/blob/master/modules/angular2/src/router/router.ts#L462)
3. `appRef.dispose()` is called in `renderToString` [here](https://github.com/angular/universal/blob/master/modules/universal/server/src/render.ts#L76).  (the `html` at that time doesn't contain rendered routes)
4. That results in element injectors dehydrations
5. Router calls `_navigate` [here](https://github.com/angular/angular/blob/master/modules/angular2/src/router/router.ts#L179), but the app component is already disposed.

**Comment by gdi2290** [comment] 2016-01-18 07:32
@alexpods that makes a lot more sense now :+1: The problem is that there's async code we're not keeping track of since it's triggered during the construction of the RootRouter. It might be a good idea for the Router to provide a token for us to resolve on the initial route otherwise we have to resort to `zone.js`. It might also be a good idea for us to provide a token that other integrations can hook into for us to resolve otherwise we're always falling back on `zone.js`. At the moment a simple setTimeout will work for now until we privide a better way to capture this

PS: You should attend our community meetings on Friday about Universal if you want to help more with the project

issue fixed via workaround https://github.com/angular/universal/commit/76aade1b11b86bafe8b6377b29b582ce2f01c56d

**Closed by gdi2290** 2016-01-18 07:32 UTC
Labels: comp: universal, effort3: medium (day), P0: urgent, type: bug

**Comment by alexpods** [comment] 2016-01-19 09:02
@gdi2290 I can't promise, but I'll try my best to attend it. Friday at noon PST right?

**Comment by jeffwhelpley** [comment] 2016-01-19 10:02
Yep, will send out invite tomorrow.
