### ISSUE TITLE
Fatal error - heap of memory

### ISSUE THREAD

**Issue by kovaletsyurii** [angular/universal#1339] opened 2019-11-22 09:27 UTC
Hi, I have one issue with serving universal build. 
I have run the server using `node --max-old-space-size=12288 dist/server` and after 20-22 hours after starting my server crashed with the next error: 
**FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory**

Probably, this is not an angular universal issue. Do you have been every seen this error in your console's output?

**Comment by alan-agius4** [comment] 2019-11-25 19:03
Hi @kovaletsyurii, I personally have never seen such error when spawning the server. However without a minimal reproduction we cannot say for certain what is the root cause and if Angular universal it at fault.

**Comment by kovaletsyurii** [comment] 2019-11-26 08:35
Hi @alan-agius4 , thanks for replying, I don't have minimal reproduction repo, because I had this error at production server, with thousands of visitors.

**Comment by kovaletsyurii** [comment] 2019-11-26 08:36
Probably it can be issues with optimization and performance of code, but I really cant do refactor all my codebase)

**Comment by alan-agius4** [comment] 2020-02-21 07:17
Closing as this seems not to be actionable by us.

Most likely you might be having a memory leak in your application. Also, there are some node versions that suffer from memory issues. Try to use Node 12.4+

**Closed by alan-agius4** 2020-02-21 07:17 UTC
Labels: state: Need repro
