### ISSUE TITLE
IMPORTANT!! -> error TS2307: Cannot find module '@nguniversal/common/clover/server/src/custom-resource-loader'

### ISSUE THREAD

**Issue by veer345** [angular/universal#2598] opened 2022-04-05 10:32 UTC
![Screenshot from 2022-04-05 15-55-37](https://user-images.githubusercontent.com/14336679/161734775-9ff90fe5-1790-4785-b107-402bb94acb37.png) 
    
Hi Folks,
I am getting this error while building the application 
angular version-13
angular/common version -"@nguniversal/common": "^13.0.0",

I notice there is no custom-resource-loader filer inside clover , Infact there is not folder of src inside clover/server.I am in middle of development , solution of this issue would help me a lot . Thanks in advance.

**Comment by alan-agius4** [comment] 2022-04-05 13:06
Duplicate of https://github.com/angular/universal/issues/2543

**Closed by alan-agius4** 2022-04-05 13:06 UTC
