### ISSUE TITLE
Create a common abstract Store for future management of state transfer between client/server

### ISSUE THREAD

**Issue by zakhenry** [angular/universal#489] opened 2016-07-20 00:02 UTC
## Background

There is a need to be able to have a common `@Injectable` class for storing persistent data between "sessions" and handling the state transfer with universal of server to client when after the client has bootstrapped angular.

For now, a common interface needs to be agreed apon, and implementations created for in-memory and localstorage. Future implementations could include redis, elasticache etc
## Considerations
- Entire store should be serializable to json for transport to client
- Deserialization of stored objects will need to be up to the developer implementation
- Methods should be async where there is a possibility that an implementing class cannot be sync
## Draft implementation

``` ts
export abstract class Store<K, V> {

  constructor() {}

  public abstract get(key: K): Observable<V>;
  public abstract set(key: K, value: V): Promise<V>;
  public abstract has(key: K): Observable<boolean>;
  public abstract delete(key: K): Promise<V>;

  public abstract entries(): Observable<[K, V]>;
  public abstract keys(): Observable<K>;
  public abstract values(): Observable<V>;

  public abstract size(): Observable<number>;
  public abstract clear(): Promise<void>;

}
```

Please note I haven't yet thought in depth about the `Observable` and `Promise` generics, so the draft as it stands is probably wrong, but the idea is there.

Once the general idea is agreed I'll create a `MemoryStore extends Store` implementation with tests to work out what the actual generics need to be

**Comment by zakhenry** [comment] 2016-07-20 00:08
cc @gdi2290 @jeffwhelpley @FrozenPandaz

**Comment by FrozenPandaz** [comment] 2016-07-31 23:36
Here is a draft implementation.

Universal Version
```typescript
import {BehaviorSubject} from 'rxjs';

/**
 * An abstract store which is meant to be transferred to client.
 */
export abstract class Store {

  constructor() {}

  protected data = {};

  private subjects = {};

  getSnapshot(key: string) {
    return this.data[key];
  }

  get(key: string) {
    this.subjects[key] = this.subjects[key] || new BehaviorSubject(this.getSnapshot(key));
    return this.subjects[key];
  }

  set(key: string, value: any): Store {
    this.data[key] = value;
    if (this.subjects[key]) {
      this.subjects[key].next(value);
    }
    return this;
  }

  delete(key: string) {
    delete this.data[key];
    if (this.subjects[key]) {
      this.subjects[key].next(undefined);
      delete this.subjects[key];
    }
  }

  clear() {
    for (let key in this.data) {
      if (this.data[key]) {
        delete(this.data[key]);
      }
    }
  }

}
```

Node Version:
```typescript
import {getDOM} from '@angular/platform-browser/src/dom/dom_adapter';

import {Store} from '../common/store.ts';

/**
 * An abstract store which is meant to be transferred to client.
 */
export abstract class NodeStore extends Store {
  
  transferToClient(name: string, componentRef: any, document) {
    const DOM: any = getDOM();
    let el = componentRef.location.nativeElement;
    let code = `window.UNIVERSAL_DATA = ${JSON.stringify(this.data)}`;
    let scriptTag = DOM.createScriptTag('type', 'text/javascript', document);
    DOM.setInnerHTML(scriptTag, code);
    DOM.insertAfter(el, scriptTag);
  }

}
```

**Comment by MarkPieszak** [comment] 2016-08-01 02:21
I like it, so is the general idea to be able to not hit the server again but re-use the data the server side already retrieved?

Or, is this more of a platform specific Store only? There's an abstract Class in Common as well at the moment.

**Comment by FrozenPandaz** [comment] 2016-08-01 02:30
Yeah at least very least, it would be to optimize and to take a lot of the load off of your stack by not having to hit the API twice per hit of the Universal Server.. and also to provide some things that the server has which the browser just doesn't have access to.

**Comment by zakhenry** [comment] 2016-08-03 19:32
@FrozenPandaz hmm on looking at your impl I realise that the strong typing with generics isn't going to help much if the stored items are of unlike types, which is actually probably the most common case. 

On your implementation, it's probably cleaner to have the local store of `data` and `subjects` as a `Map` instance rather than an `Object`. 

One thought is that a stored object *must* be serializable, and there is a somewhat unexpected behaviour when transporting to the client as a class instance will deserialize to a plain object. Perhaps there should be a guard that throws a `TypeError` if the object is not perfectly serializable. How do you even check that reliably?

**Comment by FrozenPandaz** [comment] 2016-08-07 16:32
Refactored to use a Map.
```typescript
import {BehaviorSubject} from 'rxjs';

export interface StoreItem {
  value: any;
  subject?: BehaviorSubject<any>;
}

/**
 * An abstract store which is meant to be transferred to client.
 */
export abstract class Store {

  constructor() {}

  private storeMap = new Map<string, StoreItem>();

  get(key: string): any {
    let subject = this.getSubject(key) || new BehaviorSubject(this.getSnapshot(key));
    this.storeMap.set(key , {
      value: this.storeMap.get(key).value,
      subject: subject
    });
    return this.getSubject(key);
  }

  set(key: string, value: any): Store {
    let success = false;
    try {
      JSON.stringify(value);
      success = true;
      this.storeMap.set(key, {
        value: value,
        subject: this.getSubject(key)
      });
      this.getSubject(key).next(value);
    } catch (e) {
      let err = new Error(`Values set in the store must be serializable into JSON.\n
                  The value: ${value} could not be serialized in to a JSON.`);
      throw err;
    }
    return this;
  }

  delete(key: string): void {
    let subject = this.getSubject(key);
    if (subject) {
      subject.next(undefined);
      subject.complete();
    }
    this.storeMap.delete(key);
  }

  clear(): void {
    let keys = this.storeMap.keys(),
        current = keys.next();

    while (!current.done) {
      this.delete(current.value);
      current = keys.next()
    }
  }

  getSnapshot(key: string): any {
    if (!this.storeMap.get(key)) {
      return undefined;
    }
    return this.storeMap.get(key).value;
  }

  private getSubject(key: string): BehaviorSubject<any> {
    if (!this.storeMap.get(key)) {
      return undefined;
    }
    return this.storeMap.get(key).subject;
  }

}

```

**Comment by LGabAnnell** [comment] 2016-08-12 18:49
Hi guys, does it really have to be that complicated?

Preboot does the state transfer fine. The flicker mentioned in #514 comes from the fact that preboot gets done doing the transfering *before* the http calls are done.

As for the "cache" to transfer the http calls from server to client I just took the `preload_cache_*` files that are already in the angular2-universal source and modified them a bit,

Node: 
```javascript
@Injectable()
export class NgPreloadCacheHttpCustom extends Http {
	_async: number = 0;
	_callId: number = 0;
	_rootNode;
	_activeNode;
	_renderer: Renderer;

	constructor(
		protected _backend: ConnectionBackend,
		protected _defaultOptions: RequestOptions,
		@Inject(PRIME_CACHE) private prime: boolean,
		private render: RootRenderer,
		private ngZone: NgZone,
		private cache: CacheService
	) {
		super(_backend, _defaultOptions);
		let type = new RenderComponentType("" + Math.random(), "", 0, ViewEncapsulation.None, []);
		this._renderer = render.renderComponent(type);
		var _rootNode: HTMLElement = this._renderer.createElement(this._renderer.selectRootElement("mycache"), "script");
		this._rootNode = _rootNode;
		this._activeNode = _rootNode;
		if (this.prime) {
			this._renderer.createText(this._rootNode, "window.myowncache = {};");
		}
	}

	preload(url, factory) {
		var obs = new EventEmitter(false);
		var currentNode = null;

		if (this.prime) {
			if (isPresent(this._activeNode)) {
				currentNode = {name: "hello", type: "tag", parent: this._rootNode, children: [], data: "aloha", res: null};
				this._activeNode.children.push(currentNode);
			}
		}

		// We need this to ensure all ajax calls are done before rendering the app
		this._async += 1;
		var request = factory();
		request
			.subscribe({
				next: (response) => {
					if (this.prime) {
						let headers = response.headers.toJSON();
						// TODO(gdi2290): fix Http to include the url
						let res = (<any>Object).assign({}, response, { headers, url });
						// currentNode.res = res;
						this._renderer.createText(this._rootNode, this.cache.addObject(url, res));
					}
					obs.next(response);
				},
				error: (e) => {
					obs.error(e);
					this._async -= 1;
				},
				complete: () => {
					obs.complete();
					this._async -= 1;
				}
			});
		return obs;
	}

	request(url: string | Request, options?: RequestOptionsArgs): Observable<Response> | EventEmitter<any> {
		return this.preload(url, () => super.request(url, options));
	}

	get(url: string, options?: RequestOptionsArgs): Observable<Response> | EventEmitter<any> {
		return this.preload(url, () => super.get(url, options));
	}
	post(url: string, body: string, options?: RequestOptionsArgs): Observable<Response> | EventEmitter<any> {
		return this.preload(url, () => super.post(url, body, options));
	}
	put(url: string, body: string, options?: RequestOptionsArgs): Observable<Response> | EventEmitter<any> {
		return this.preload(url, () => super.put(url, body, options));
	}
	delete(url: string, options?: RequestOptionsArgs): Observable<Response> | EventEmitter<any> {
		return this.preload(url, () => super.delete(url, options));
	}
	patch(url: string, body: string, options?: RequestOptionsArgs): Observable<Response> | EventEmitter<any> {
		return this.preload(url, () => super.patch(url, body, options));
	}
	head(url: string, options?: RequestOptionsArgs): Observable<Response> | EventEmitter<any> {
		return this.preload(url, () => super.head(url, options));
	}
}

export const CUSTOM_NODE_HTTP_PROVIDERS = [
	...NODE_HTTP_PROVIDERS_COMMON,
	{provide: BrowserXhr, useClass: NodeXhr},
	{provide: ConnectionBackend, useClass: NodeBackend},
	{provide: PRIME_CACHE, useValue: true},
	{provide: Http, useFactory: (xhrBackend, defaultOptions, prime, rootrenderer, ngZone, cache) => {
		return new NgPreloadCacheHttpCustom(xhrBackend, defaultOptions, prime, rootrenderer, ngZone, cache);
	}, deps: [ConnectionBackend, RequestOptions, PRIME_CACHE, RootRenderer, NgZone, CacheService]},
];
```

CacheService:

```javascript
import {Injectable} from "@angular/core";
@Injectable()
export class CacheService {
	object: any[] = [];

	addObject(url, obj):string {
		return `window.myowncache['${url}'] = {res: ${JSON.stringify(obj)}, used: 0};`;
	}

	has(url) {
		if ((<any>window).myowncache) {
			return !!(<any>window).myowncache[url];
		} else return false;
	}

	get(url) {
		return (<any>window).myowncache[url];
	}

	remove(url) {
		delete (<any>window).myowncache[url];
	}
}
```

And http "override" for client side: 

```javascript

@Injectable()
export class NgBrowserPreloadCacheHttp extends Http {
	prime: boolean = true;
	constructor(
		protected _backend: ConnectionBackend,
		protected _defaultOptions: RequestOptions,
		private _cache: CacheService
	) {
		super(_backend, _defaultOptions);
	}

	preload(method, url): Observable<any> | EventEmitter<any> {
		if (this._cache.has(url) && this._cache.get(url).used === 0) {
			let obj = this._cache.get(url);
			if (!obj.res.json) {
				obj.res.json = () => {
					return JSON.parse(obj.res._body);
				}
			}
			if (!obj.res.text) {
				obj.res.text = () => {
					return obj.res._body;
				}
			}
			obj.used = 1;
			return new Observable<any>((observer) => {
				observer.next(obj.res);
				observer.complete();
			});
		}
		return new Observable<any>((observer) => {
			let subscription: Subscription = method().subscribe(
				(response) => {
					observer.next(response);
				},
				(err) => {
					observer.error(err);
				},
				() => {
					subscription.unsubscribe();
					observer.complete();
				}
			);
		});
	}

	request(url: string, options?): Observable<Response> | EventEmitter<any> {
		return this.prime ? this.preload(() => super.request(url, options), url) : super.request(url, options);
	}

	get(url: string, options?): Observable<Response> | EventEmitter<any> {
		return this.prime ? this.preload(() => super.get(url, options), url) : super.get(url, options);
	}

	post(url: string, body: string, options?): Observable<Response> | EventEmitter<any> {
		return this.prime ? this.preload(() => super.post(url, body, options), url) : super.post(url, body, options);
	}

	put(url: string, body: string, options?): Observable<Response> | EventEmitter<any> {
		return this.prime ? this.preload(() => super.put(url, body, options), url) : super.put(url, body, options);
	}

	delete(url: string, options?): Observable<Response> | EventEmitter<any> {
		return this.prime ? this.preload(() => super.delete(url, options), url) : super.delete(url, options);
	}

	patch(url: string, body: string, options?): Observable<Response> | EventEmitter<any> {
		return this.prime ? this.preload(() => super.patch(url, body, options), url) : super.patch(url, body, options);
	}

	head(url: string, options?): Observable<Response> | EventEmitter<any> {
		return this.prime ? this.preload(() => super.head(url, options), url) : super.head(url, options);
	}
}

export const CUSTOM_HTTP_PROVIDERS = [
	{ provide: Http, useFactory: (xhrBackend: XHRBackend, requestOptions: RequestOptions, cache) => {
		return new NgBrowserPreloadCacheHttp(xhrBackend, requestOptions, cache);
	}, deps: [XHRBackend, RequestOptions, CacheService] },
	BrowserXhr,
	{ provide: RequestOptions, useClass: BaseRequestOptions },
	{ provide: ResponseOptions, useClass: BaseResponseOptions },
	XHRBackend,
	{ provide: XSRFStrategy, useValue: new CookieXSRFStrategy() }
];
```

It's obviously not completed and there's some code that's not needed in there, but I did it as a quick fix to solve the flickering caused by the HTTP calls being done again when the application is loaded client-side.

As for the "store", there really isn't any need for the store, because you just serialize it server-side, and then `window.ngCache` or whatever is your store.

**Comment by gdi2290** [comment] 2016-11-15 16:05
right now this is in universal-starter as CacheService with sync methods and everything wired up
https://github.com/angular/universal-starter

**Comment by gdi2290** [comment] 2017-01-08 04:01
won't be supported officially 
https://github.com/angular/angular/issues/13822

**Closed by gdi2290** 2017-01-08 04:01 UTC
