### ISSUE TITLE
After migrating from angular universal 8 to 9, the page is in eternal loading and does not load anything

### ISSUE THREAD

**Issue by GlauberF** [angular/universal#1711] opened 2020-05-29 00:56 UTC
# 🐞 bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Description
after I upgraded from angular 8 to angular 9, Angular SSR stopped working.
it compiles everything right, when I open it in the browser it keeps trying to load and can't, there is no error in the browser console and I have no error in the terminal, I no longer know what to do.
For several weeks I have been trying to solve this, but there is no way to identify what is happening and it is something related to the update..

## 🔬 Minimal Reproduction
https://github.com/GlauberF/minimal-reproduction

## 🔥 Exception or Error
![ezgif-3-c3d591a12da4](https://user-images.githubusercontent.com/11314585/83208806-153ad980-a12d-11ea-8e5d-b0c9c8a652c0.gif)

## 🌍  Your Environment

```ts
Angular CLI: 9.1.7
Node: 12.16.3
OS: linux x64

Angular: 9.1.4
... animations, common, compiler, core, forms, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.7
@angular-devkit/build-angular      0.901.7
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.7
@angular-devkit/core               9.1.7
@angular-devkit/schematics         9.1.7
@angular/cdk                       9.2.2
@angular/cli                       9.1.7
@angular/compiler-cli              9.1.9
@angular/flex-layout               9.0.0-beta.29
@angular/language-service          9.1.9
@angular/material                  9.2.2
@angular/material-moment-adapter   9.2.2
@ngtools/webpack                   9.1.7
@nguniversal/builders              9.1.1
@nguniversal/common                9.1.0
@nguniversal/express-engine        9.1.0
@schematics/angular                9.1.7
@schematics/update                 0.901.7
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0

```

**Comment by GlauberF** [comment] 2020-06-05 09:59
is there any way to debug the terminal when the server goes up, to see if I can get any logs that are causing this problem?

**Comment by dev-assassin** [comment] 2020-06-08 14:03
@GlauberF 
in my side, it works well.
when i start the project with `npm start`, login dashboard is opened.

[https://gofile.io/d/XhjChN](url)
please check it, let me know.

**Comment by GlauberF** [comment] 2020-06-08 14:07
@dev-assassin My problem is not with npm start, but with the build and angular universal.
- npm run build: ssr (Works)
- npm run serves: ssr (does not work)

**Comment by dev-assassin** [comment] 2020-06-08 14:11
@GlauberF  as seeing your package.json, `npm run serves: ssr` command is not existed.

**Comment by GlauberF** [comment] 2020-06-08 14:12
@dev-assassin I wrote it wrong,
- npm run serve:ssr (does not work)

**Comment by dev-assassin** [comment] 2020-06-08 14:16
> @dev-assassin I wrote it wrong,
> 
> * npm run serve:ssr (does not work)

[https://gofile.io/d/5NHOqL](url)

**Comment by GlauberF** [comment] 2020-06-08 14:17
@dev-assassin does this link redirect me to the issues?
![Captura de Tela_selecionar área_20200608111746](https://user-images.githubusercontent.com/11314585/84041013-b28ddd00-a979-11ea-9355-2c8185601331.png)

**Comment by dev-assassin** [comment] 2020-06-08 14:21
sorry.

https://gofile.io/d/5NHOqL

**Comment by GlauberF** [comment] 2020-06-08 14:26
@dev-assassin excuse me, add in package.json:
<pre><code>
"serve:ssr": "node dist/server/main.js",
"build:ssr": "ng build --prod && ng run vimbo:server:production",
</code></pre>

**Comment by dev-assassin** [comment] 2020-06-08 14:37
when you run that command, did you get `dist` folder?

**Comment by GlauberF** [comment] 2020-06-08 15:21
@dev-assassin  The correct flow is for you to do the buil first (build:ssr) and then upload the server (serve:ssr).

if you run the server before, it will really give an error, because there is no build yet.

This is the basic build flow of an application, universal angular

**Comment by rmcsharry** [comment] 2020-06-08 15:35
@GlauberF Just jumping in here to confirm that we see the exact same issue. We have narrowed it down to using async pipe with ngIf or ngFor.

If we remove the async pipe from all uses of those structural directives and instead use subscriptions in the ts file, then SSR works and loads the site.

Why that should be, I have no *£F?*&^!! idea.

https://stackoverflow.com/questions/62246010/angular-rxjs-pipe-async-does-not-work-with-ssr?noredirect=1#comment110112454_62246010

**Comment by GlauberF** [comment] 2020-06-08 15:42
I'm not sure if it's the same problem, I'll check

**Comment by dev-assassin** [comment] 2020-06-08 16:01
> @dev-assassin The correct flow is for you to do the buil first (build:ssr) and then run the server (serve:ssr)
> 
> if you run the server before, it will really give an error, because there is no build yet.
> 
> This is the basic build flow of an application, universal angular

well. i know the flow. before running `npm run serve:ssr`, i am sure i built it at first. :)

**Comment by GlauberF** [comment] 2020-06-08 16:37
@dev-assassin I don't have the same error that you mention here

**Comment by GlauberF** [comment] 2020-06-08 17:13
@rmcsharry I have almost the same problem, it doesn't load 4000, but if I put /index.html it redirects me to 40o0 and then opens the app.

But I do not work with observable in * ngIf or * ngFor and locastorage also checked and I did not find any place that could give the problem, because in all of them I put a check to see if it is a server that does not execute.

so, I don't know what the error could be.

**Comment by rmcsharry** [comment] 2020-06-09 11:32
@GlauberF Thanks for checking and reporting back. Let's hope someone with more expertise of the library can help figure this out.

**Comment by sadriddin** [comment] 2020-06-17 08:11
Same happened to me. After upgrade, lazyload modules stopped working with SSR, but eager load modules work

**Comment by rmcsharry** [comment] 2020-06-17 14:12
Some further information.

All our components were using the `OnPush` strategy and we would use `ChangeDetectorRef` to decide when to trigger change detection.

After removing OnPush so that components used the default, SSR mode started working again. We were still able to use the async pipe with ngIf and ngFor.

So either we remove use of async pipe OR we remove OnPush. But using them together (not necessarily in the same component) caused this problem for us.

**Comment by GlauberF** [comment] 2020-06-18 09:46
let's wait for @alan-agius4 or any member of the team, if the problem is in the universal library.

**Comment by tobysmith568** [comment] 2020-06-23 20:47
I'm not using `OnPush` or async pipes, but I'm also experiencing this. I successfully get console.logs which are in the `APP_INITIALIZER` provider factory, but not console.logs which are in my `AppComponent` constructor. Currently my app has all HTML commented out in an effort to find out where the issue as come from but that hasn't helped.

**Comment by GlauberF** [comment] 2020-06-25 18:41
i'm in this same fight for several days @tobysmith568 , as i already said i believe it is the library's mistake and i'm waiting for the team behind the angular universal or @alan-agius4 .
And for me what bother me a lot, I don't get an error on the browser console or the terminal

**Comment by GlauberF** [comment] 2020-07-01 17:22
@alan-agius4 any progress?
I tried to update to version 10, believing it could solve the problem, but the error of continuous loading continues.

**Comment by GlauberF** [comment] 2020-07-13 19:01
@rmcsharry, @sadriddin e @tobysmith568 managed to come up with a solution and what solution did they use?

Why stop using OnPush, ChangeDetectorRef can not.

And I did not receive feedback from the team, I am thinking of closing the issue, since there was no explanation for example of why this happens and why there is no error in the browser and terminal console

**Comment by rmcsharry** [comment] 2020-07-14 10:21
@GlauberF I did not come up with a solution, just a temporary workaround which is to NOT use OnPush OR to NOT use the Async pipe.

For me that is not an acceptable 'solution'.

Please do not close the issue, let's wait and see what the team says.

**Comment by tobysmith568** [comment] 2020-07-14 10:23
@GlauberF I also did not come up with a solution. I cannot use SSR until this is resolved.

**Comment by sadriddin** [comment] 2020-07-14 10:26
@GlauberF  I also did not come up with a solution.

**Comment by GlauberF** [comment] 2020-07-14 11:36
@alan-agius4 , we need to know from you if this error is really from the library, because like me I have other users facing the same problem, as can be seen here in the issue.

I believe that you @CaerusKaru be part of the core of the team, if you can help us.

**Comment by SyedUmerHasan** [comment] 2020-08-18 07:17
I had been working with Angular SSR with version 10(.NET CORE)
I just get to know that from Angular 8 onwards, 
Angular has introduces a new version of compiler which is Angular IVY [see more](https://angular.io/guide/ivy)
and is open by default, so when you work with SSR with Angular 8 version, it perfectly work fine. 
but as you upgrade or create project with Angular 9 it stop working.
So you need to add below configuration in **tsconfig.base.json**
`

> "angularCompilerOptions": {
>     "enableIvy": false
>   }

`
**NOTE: It works perfectly in my case**

**Comment by DMZakaria** [comment] 2020-08-18 09:57
> I had been working with Angular SSR with version 10(.NET CORE)
> I just get to know that from Angular 8 onwards,
> Angular has introduces a new version of compiler which is Angular IVY [see more](https://angular.io/guide/ivy)
> and is open by default, so when you work with SSR with Angular 8 version, it perfectly work fine.
> but as you upgrade or create project with Angular 9 it stop working.
> So you need to add below configuration in **tsconfig.base.json**
> `
> 
> > "angularCompilerOptions": {
> > "enableIvy": false
> > }
> 
> `
> **NOTE: It works perfectly in my case**

This is also a workaround, you disable the most important feature of Angular. I think there is an issue with Angular and SSR. 
I am in the same team of @rmcsharry and after few days of investigation, we disable onPush and the project works ^^, but it is a temporary workaround because like @GlauberF said, we need to know from the universal team if the error is coming from the library or from Angular itself.

**Comment by GlauberF** [comment] 2020-08-18 10:02
Hi @DMZakaria ,
I'm already messing around waiting for an angular team position and still nothing.
It seems to me that this issue has been overlooked.

**Comment by GlauberF** [comment] 2020-09-09 14:21
awaiting position of staff from the core team

**Comment by tobysmith568** [comment] 2020-09-18 13:37
I appreciate it might not be an option for all, but Angular 10 appears to have fixed this issue for me.

**Comment by hanstf** [comment] 2020-09-22 12:06
@tobysmith568 I have the same issue, which version 10 do you use ?

**Comment by tobysmith568** [comment] 2020-09-22 15:45
> @tobysmith568 I have the same issue, which version 10 do you use ?

```json
"dependencies": {
    "@angular/animations": "~10.0.14",
    "@angular/cdk": "^10.1.3",
    "@angular/common": "~10.0.14",
    "@angular/compiler": "~10.0.14",
    "@angular/core": "~10.0.14",
    "@angular/forms": "~10.0.14",
    "@angular/platform-browser": "~10.0.14",
    "@angular/platform-browser-dynamic": "~10.0.14",
    "@angular/platform-server": "~10.0.14",
    "@angular/router": "~10.0.14",
    "@ionic/angular": "^5.3.2",
    "@nguniversal/express-engine": "^10.0.2"
},
"devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.8",
    "@angular/cli": "~10.0.8",
    "@angular/compiler-cli": "~10.0.14",
    "@nguniversal/builders": "^10.0.2"
}
```

**Comment by GlauberF** [comment] 2020-09-23 11:03
I tried to update, a document usage error appeared, I adjusted it.
But the eternal loading continues, and the browser console does not return an error and there is also no error on the terminal console.

Looking more deeply at the documentation, I arrived at this file https://github.com/angular/universal/blob/master/docs/gotchas.md, according to the file, for my case everything indicates that it has some active macrotasks / micro-tasks.

like @CaerusKaru , @alan-agius4  can I debug to see if he got into any macrotask / microtask and know how long it is taking to be solved.
Anyway, I need to know how to debug somehow better, why am I unable to come up with a solution for this and I have been involved with this problem for 4 months, why I don't get an error anywhere so I don't know what to "fix".

**Comment by alan-agius4** [comment] 2020-09-23 12:36
Hi @GlauberF, 

Sorry for the late reply but got side tracked by other tasks.

Unfortunately, we cannot possibly debugging a reproduction this size, we can only look at minimal reproductions. Also, you are likely more familiar with your application architecture and what can cause the "infinite loading" behaviour.

I think the most straight-ward way to debug this is using the good old profiler, inspector and debugger. I'd start by running the server in inspect mode and pause the program from the inspector UI when it seems to be hanging to see where the stack is currently is, from here you can possible narrow the issue down.

> why I don't get an error anywhere so I don't know what to "fix".?

Because there is nothing to error on, consider this as an initiate loop of 2 minutes (Unless you are changing the server timeout). https://nodejs.org/dist/latest-v6.x/docs/api/http.html#http_server_timeout

**Comment by GlauberF** [comment] 2020-09-23 15:41
Right @alan-agius4  .
But there are some things that I still don't understand about all this, sorry for my ignorance, because I am no expert.

1 - How can it be an error of my application, if it works normally in a normal build for production without the universal angle.
2 - In the angle 8 I used the universal angle without any problems and this started to cause problems starting with ivy in version 9 or more.
3 - About startup time, which could be what causes "infinite loading", caused by macrotasks / micro-tasks, Why this doesn't happen in a normal build, as my application can be seen here https: //app.vimbo .com.br and was generated through a normal build.
4 - Lastly, it is not just me that is facing this problem, here in this issue you can see several similar reports.

I believe that it would be of great help not only for min, but for all the people who reported something similar here, that was investigated.
As much as perhaps the reproduction that I spent is not so small, you may encounter some problem that before in small applications (small reproductions) it will not appear.

**Comment by hanstf** [comment] 2020-09-23 15:50
Hi @GlauberF, in my case, it was solved by updating the server.ts file following this guide https://www.ganatan.com/tutorials/server-side-rendering-with-angular-universal

**Comment by GlauberF** [comment] 2020-09-23 20:44
@alan-agius4  , after a lot of work, comments and debugging I got to the problem.
See if you can help me, if you can I am grateful.
Today in my main module file (AppModule) I lazily call some folders and inside these folders there are other system modules.
And I have a standard route and one when typing something that doesn't exist.
see the image below
![Captura de Tela_selecionar área_20200923172303](https://user-images.githubusercontent.com/11314585/94066911-7fa21480-fdc3-11ea-8f9c-0bef35552a56.png)
![Captura de Tela_selecionar área_20200923172328](https://user-images.githubusercontent.com/11314585/94067059-b37d3a00-fdc3-11ea-9f5f-b0a623f4e5e8.png)

These last two routes selected below are causing "infinite loading", he is not managing to solve.
Perhaps because the default route has not yet been loaded, as it is inside the app folder, which is called when you pass the url / app/...
```typescript
{
        path: '',
        redirectTo: 'apps/dashboard/company',
        pathMatch: 'full'
    }
```
And it happens with the error page too, because it is inside the page/...
```typescript
{
        path: '**',
        redirectTo: 'pages/error/error-404'
    }
```

What should be the approach to address this?

**Comment by alan-agius4** [comment] 2020-09-24 12:26
@GlauberF, I am not quite sure how are you setting up the nested routes. I did try to replicate the issue by configuring nested lazy routing and it worked as expected. At this point, without a minimal reproduction we'll not be able to investigate this issue any further.

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by sadriddin** [comment] 2020-10-29 11:55
@alan-agius4  Here https://github.com/sadriddin/angular-universal-10-loading-issue a minimal repro. It has one protected route with the guard. If you run `npm run dev:ssr` and navigate to `http://localhost:4200/protected` it loads infinitely.

It's working in Angular V8. Here is https://github.com/sadriddin/angular-univerasal-v8-example working example in Angular V8

**Comment by GlauberF** [comment] 2020-10-29 16:49
you know that now that you commented on @sadriddin, really where I have canActivate, canLoad is loading endlessly and where I don’t have the route to publish example, login, it works and for me it also worked in v8

**Comment by GlauberF** [comment] 2020-11-12 17:37
@alan-agius4 Any updates ?

**Comment by naouaro** [comment] 2020-11-16 05:13
This is very strange @GlauberF, I am also facing the same issue, in my case cancling the loading of the page and calling it again solve the problem, funny it happens just the first time after the server runs, after that everything works just fine !

**Comment by GlauberF** [comment] 2020-11-17 19:14
we certainly have a problem with the library or the compiler(ivy) and it has to do with canLoad, canActivate as @sadriddin reported.
For me in version 8 or less, it works perfectly, as reported by @sadriddin  .
The complicated that this problem has lasted for several and several months, and applications without making use of the angular universal, why activate the error.

**Comment by naouaro** [comment] 2020-11-17 19:28
@GlauberF I just wonder when you run the app and the page tries to load the page, if you stop the loading, reload it again does it open ? or keeps trying to load ?

**Comment by GlauberF** [comment] 2020-11-18 18:37
It doesn't solve, problem continues.

**Comment by Judp0m** [comment] 2020-12-21 06:41
I ran into a very similar problem (SSR server hangs indefinitely on Angular 11 Ivy). Please take a look at this in case it helps you:
https://stackoverflow.com/questions/65388261/angular-11-firebase-server-side-rendering-infinite-loading-pending

**Comment by GlauberF** [comment] 2020-12-21 19:52
It has nothing to do with the problem I face, as already mentioned @sadriddin , created a repository with the problem and the problem only happens where there is canLoad, canActiv.

**Comment by Womballs** [comment] 2021-01-06 11:55
@GlauberF same problem here upgrade from angular 8 to 1, infite load but from /index.html works fine. Is there any update or it still bugged ?

**Comment by GlauberF** [comment] 2021-01-06 21:15
@Womballs is still in trouble.
almost one turning into a movie that already.

another 4 months closes 1 year that the problem exists.

**Comment by rmcsharry** [comment] 2021-01-07 00:10
I first commented in June 2020 that my project also has this issue, so I am just reporting that 7 months later I am still here with the same problem, waiting to find out at least some info about the root cause. A solution ofc would be a nice new year gift :)

**Comment by Ashvin-Pal** [comment] 2021-01-26 12:45
Not sure if this is of much help. But for now to get mine working I used the sample below. It works locally and also after deploying to firebase hosting.

`    let x =this.afs
      .collection<shopsDetails>('shops')
      .snapshotChanges()
      .subscribe((data) => {
        data.forEach((shop) => this.shops.push(shop.payload.doc.data()));
        x.unsubscribe();
      });
`

**Comment by GlauberF** [comment] 2021-01-26 12:51
@Ashvin-Pal  I didn't understand what you mean by your code exactly.
you can send more details (in which file is this code, as it was before the change), even though I think we are talking about different things here in this issue.

**Comment by DMZakaria** [comment] 2021-01-27 11:09
I want to give you update about our issue (with @rmcsharry). 

I upgraded the project to angular 11 and activated `onPush` with `async` and SSR works like magic. That's good news but unfortunately, we did not know why it was not working in the previous versions.

Another advice about SSR with angular (it might help you...) , we decide to drop the Flex-layout library because it was not designed to work with SSR (even with the FxLayoutServerModule...). The style are injected dynamically so on page loads the layout is always mangled , and sometimes we got infinite loading.

Good luck

**Comment by GlauberF** [comment] 2021-02-01 11:47
@DMZakaria could pass the exact version you are using, I will do the test

**Comment by DMZakaria** [comment] 2021-02-01 12:31
This is my version, hope it will help you 
`Angular CLI: 11.0.7
Node: 14.15.0
OS: win32 x64

Angular: 11.0.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.7
@angular/cdk                    11.0.4
@angular/cli                    11.0.7
@angular/fire                   6.1.4
@angular/flex-layout            11.0.0-beta.33
@angular/material               11.0.4
@angular/youtube-player         11.0.4
@nguniversal/builders           11.1.0-next.0
@nguniversal/express-engine     11.1.0-next.0
@schematics/angular             11.0.7
@schematics/update              0.1100.7
rxjs                            6.6.3
typescript                      4.0.5`

**Comment by GlauberF** [comment] 2021-02-01 16:30
Today my version is 11.0.3 and the problem continues, but this week I will update to the latest version and see if the problem has been fixed.

**Comment by GlauberF** [comment] 2021-02-11 01:27
updated and for min the infinite loading continues.
I am already coming to the conclusion that I will no longer be able to use angular universal.

**Comment by DMZakaria** [comment] 2021-02-11 09:49
@GlauberF did you try to get ride of the flex-lyout module, in my side it causes me a lot of issues.

**Comment by GlauberF** [comment] 2021-02-11 11:34
No, because I use it throughout the system.
What I did was remove the FlexLayoutServerModule from the app.server.module.ts file.

**Comment by GlauberF** [comment] 2021-03-23 12:07
@alan-agius4 did you check the repositories provided by @sadriddin ?
We need to be sure what changed from versions 8 to 10 or more, which created this infinite loading effect.
Where I believe it is something in canLoad and canActivate.

**Comment by DelRioOscar** [comment] 2021-05-18 15:23
I found a solution and maybe I don't know if it's the best but it works.

The problem is that it barely gets up and is loading and works only when the path is placed /index.html

then to always force the entry to index.html as soon as the server is up, you have to make the following modification in server.ts


`import 'zone.js/dist/zone-node';

import { ngExpressEngine } from '@nguniversal/express-engine';
import express, { Request, Response } from 'express';
import { join } from 'path';

import { AppServerModule } from './src/main.server';
import { existsSync, readFileSync } from 'fs';
const domino = require('domino');
const path = require('path')

const distFolder = join(process.cwd(), 'dist/chatroom/browser');
const template = readFileSync(path.join(distFolder, 'index.html')).toString();
const win = domino.createWindow(template.toString());


global['window'] = win;
Object.defineProperty(win.document.body.style, 'transform', {
  value: () => {
    return {
      enumerable: true,
      configurable: true,
    };
  },
});
(global as any)['document'] = win.document;
(global as any)['CSS'] = null;
(global as any)['Prism'] = null;

// The Express app is exported so that it can be used by serverless Functions.
export function app(): express.Express {
  const server = express();
  const distFolder = join(process.cwd(), 'dist/chatroom/browser');
  const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index.html';

  // Our Universal express-engine (found @ https://github.com/angular/universal/tree/master/modules/express-engine)
  server.engine('html', ngExpressEngine({
    bootstrap: AppServerModule,
  }));

  server.set('view engine', 'html');
  server.set('views', distFolder);

  // Example Express Rest API endpoints
  // server.get('/api/**', (req, res) => { });
  // Serve static files from /browser
  server.get('*.*', express.static(distFolder, {
    maxAge: '1y'
  }));

  // All regular routes use the Universal engine
  server.get('*', (req: Request, res: Response) => {
    res.redirect(indexHtml);
  });

  return server;
}

function run(): void {
  const port = process.env.PORT || 4000;

  // Start up the Node server
  const server = app();
  server.listen(port, () => {
    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

// Webpack will replace 'require' with '__webpack_require__'
// '__non_webpack_require__' is a proxy to Node 'require'
// The below code is to ensure that the server is run only when not requiring the bundle.
declare const __non_webpack_require__: NodeRequire;
const mainModule = __non_webpack_require__.main;
const moduleFilename = mainModule && mainModule.filename || '';
if (moduleFilename === __filename || moduleFilename.includes('iisnode')) {
  run();
}

export * from './src/main.server';
`



you must make two modifications:

1) change const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index';
TO
 const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index.html';

2) replace // All regular routes use the Universal engine
  server.get('*', (req, res) => {
    res.render(indexHtml, { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] });
  });

with  // All regular routes use the Universal engine
  server.get('*', (req, res) => {
    res.redirect(indexHtml);
  });

and open a new tab private...

**Comment by GlauberF** [comment] 2021-05-21 12:25
At least this issue could be closed, because my problem after investigating thoroughly.
It was a third-party library.
If anyone still has this problem, let me know in the comments, otherwise I will close.

**Comment by sadriddin** [comment] 2021-05-22 10:47
@GlauberF Still having this problem in angular v12

**Comment by GlauberF** [comment] 2021-05-25 20:56
ok @sadriddin , leave it open.
Thanks for the feedback.

**Comment by YugasVasyl** [comment] 2021-05-25 21:24
Used Angular 7 with one AppModule for the entire app. Changed router to use lazy-loading, and now SSR stuck. Upgraded to 8th Angular, and having exactly the same issue there.

**Comment by popovicititus** [comment] 2021-06-29 23:33
@GlauberF could you let us know which 3rd-party if it's a known one? Was it flex-layout as suggested above?

**Comment by GlauberF** [comment] 2021-06-30 12:02
actually my problem was with electron.
as my platform ran web and desktop with electron, electrom's lib itself was the problem.
then we chose to remove and work in a slightly different way than we had been working.

**Comment by OZZlE** [comment] 2021-12-21 08:42
For me I run `npm run dev:ssr` and it works initially, I modify some code like css, after the thrid edit or so the page reloads and then it just loads forever and I have to quit npm and restart it..

My project is pretty boilerplate, I haven't installed any modules, latest Angular version core v. 12.2.15. nguniversal/express-engine v. 12.1.3

I have Angular routing and som resolvers but they currently don't do anything

    import { Injectable } from '@angular/core';
    import { Resolve } from '@angular/router';
    import { HttpClient, HttpErrorResponse, HttpParams } from '@angular/common/http';

    @Injectable()
        export class PageResolver {
        constructor(private http: HttpClient) { }

        resolve() {
            const params = new HttpParams();

            /*
            // a graphql request
            const query = `{
            filters
            }`;
            const body = JSON.stringify({ query });
            return this.http.post('https://example.com/graphql/', body, { params }).toPromise();

            */
        }
    }

**Comment by OZZlE** [comment] 2021-12-21 09:09
Seems to happen more often if I save too quickly, if I wait like 30s between saves it doesn't happen as much...

**Comment by alan-agius4** [comment] 2023-02-09 16:04
Closing as original issue is solved and was caused by a 3rd party. 

If the problem persists in your application, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.

**Closed by alan-agius4** 2023-02-09 16:04 UTC
Labels: need: investigation
