### ISSUE TITLE
Refactor universal folder structure

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#191] opened 2016-01-14 23:26 UTC
currently
```
universal/
  client/
  dist/
    client/
    server/
  server/
```
which should be 
```
universal/
  src/
    client/
    server/
  dist/
    client/
    server/
```

**Comment by gdi2290** [comment] 2016-01-15 04:03
the file paths need to be consistent for browser field metadata spec https://github.com/defunctzombie/package-browser-field-spec and `examples/` folder

**Comment by jeffwhelpley** [comment] 2016-02-07 11:29
Duplicate of #194

**Closed by jeffwhelpley** 2016-02-07 11:29 UTC
Labels: comp: universal, effort1: easy (hour), P1: required
