### ISSUE TITLE
Feature Request: Universalize the title element in the header so that document.title isn't being used

### ISSUE THREAD

**Issue by Quixomatic** [angular/universal#572] opened 2016-10-03 21:04 UTC
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [x] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**
feature

* **What is the current behavior?**
TitleService from @angular/common currently just sets document.title instead of changing the actual title element. This makes bots crawl and detect the wrong title names.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
Not a bug

* **What is the expected behavior?**
Serve up the header element with a title tag that correctly corresponds to the current page

* **What is the motivation / use case for changing the behavior?**
Bots will better be able to crawl sites

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by jeffwhelpley** [comment] 2016-10-03 22:06
This is a dupe of #309 where we are in the process of working on this feature.

**Closed by jeffwhelpley** 2016-10-03 22:06 UTC

**Comment by Quixomatic** [comment] 2016-10-04 00:36
Ah gotcha, sorry for duplicating a known issue.

**Comment by Quixomatic** [comment] 2016-10-05 04:25
As posted in the general slack channel, this is a seo solution inspired by andresantos123

```
import { Injectable, Inject, ElementRef, Renderer } from '@angular/core'
import { DOCUMENT } from '@angular/platform-browser'

@Injectable()
export class InterfaceService {    
    //--------------------------------------------
    //! Set the variables to their default values
    //--------------------------------------------
    constructor (@Inject(DOCUMENT) private document) {
	}
				 
	//----------------------------
    //! Set the title of the page
    //----------------------------
    setTitle (title: string) {
        this.document.title = title
    }
}
```
